// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * OpenDialogResult 打开对话框结果
 */
export class OpenDialogResult {
    "canceled": boolean;
    "filePaths": string[];

    /** Creates a new OpenDialogResult instance. */
    constructor($$source: Partial<OpenDialogResult> = {}) {
        if (!("canceled" in $$source)) {
            this["canceled"] = false;
        }
        if (!("filePaths" in $$source)) {
            this["filePaths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenDialogResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenDialogResult {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filePaths" in $$parsedSource) {
            $$parsedSource["filePaths"] = $$createField1_0($$parsedSource["filePaths"]);
        }
        return new OpenDialogResult($$parsedSource as Partial<OpenDialogResult>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
