// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 站点 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../../lvfeng-z/library-squirrel-plugin-sdk/dto/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除站点
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2412603777, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<dto$0.SiteDTO | null> | null> {
    return $Call.ByID(3918720310, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetByName 根据名称获取
 */
export function GetByName(siteName: string): $CancellablePromise<model$0.ApiResponse<dto$0.SiteDTO | null> | null> {
    return $Call.ByID(4204078944, siteName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: model$0.Page<dto$0.SiteDTO> | null, query: $models.SiteQueryDTO): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.SiteDTO> | null> | null> {
    return $Call.ByID(1393573905, page, query).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * QuerySelectItemPage 分页查询选择项
 */
export function QuerySelectItemPage(page: model$0.Page<dto$0.SelectItem> | null, query: $models.SiteQueryDTO): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.SelectItem> | null> | null> {
    return $Call.ByID(2991076938, page, query).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * Save 保存站点
 */
export function Save(site: dto$0.SiteDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(3287502339, site).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * Update 更新站点
 */
export function Update(site: dto$0.SiteDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2051714543, site).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = dto$0.SiteDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.Page.createFrom($$createType2);
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.ApiResponse.createFrom($$createType7);
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = dto$0.SelectItem.createFrom;
const $$createType11 = model$0.Page.createFrom($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = model$0.ApiResponse.createFrom($$createType12);
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType16 = $Create.Nullable($$createType15);
