// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../../pkg/query/models.js";

/**
 * PluginQueryDTO 插件查询条件
 */
export class PluginQueryDTO {
    /**
     * 公开ID（精确匹配）
     */
    "publicId": query$0.QueryAttribute<string>;

    /**
     * 插件名称（精确匹配）
     */
    "name": query$0.QueryAttribute<string>;

    /**
     * 作者（精确匹配）
     */
    "author": query$0.QueryAttribute<string>;

    /**
     * 版本号（精确匹配）
     */
    "version": query$0.QueryAttribute<string>;

    /**
     * 激活类型（精确匹配）
     */
    "activationType": query$0.QueryAttribute<string>;

    /**
     * 是否已卸载（0=未卸载，1=已卸载）
     */
    "uninstalled": query$0.QueryAttribute<boolean>;

    /**
     * 插件名称（模糊匹配）
     */
    "nameStr": query$0.QueryAttribute<string>;

    /**
     * 作者（模糊匹配）
     */
    "authorStr": query$0.QueryAttribute<string>;

    /**
     * 创建时间（可用于排序）
     */
    "createTime": query$0.QueryAttribute<number>;

    /**
     * 更新时间（可用于排序）
     */
    "updateTime": query$0.QueryAttribute<number>;

    /** Creates a new PluginQueryDTO instance. */
    constructor($$source: Partial<PluginQueryDTO> = {}) {
        if (!("publicId" in $$source)) {
            this["publicId"] = (new query$0.QueryAttribute());
        }
        if (!("name" in $$source)) {
            this["name"] = (new query$0.QueryAttribute());
        }
        if (!("author" in $$source)) {
            this["author"] = (new query$0.QueryAttribute());
        }
        if (!("version" in $$source)) {
            this["version"] = (new query$0.QueryAttribute());
        }
        if (!("activationType" in $$source)) {
            this["activationType"] = (new query$0.QueryAttribute());
        }
        if (!("uninstalled" in $$source)) {
            this["uninstalled"] = (new query$0.QueryAttribute());
        }
        if (!("nameStr" in $$source)) {
            this["nameStr"] = (new query$0.QueryAttribute());
        }
        if (!("authorStr" in $$source)) {
            this["authorStr"] = (new query$0.QueryAttribute());
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = (new query$0.QueryAttribute());
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = (new query$0.QueryAttribute());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginQueryDTO {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("publicId" in $$parsedSource) {
            $$parsedSource["publicId"] = $$createField0_0($$parsedSource["publicId"]);
        }
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField1_0($$parsedSource["name"]);
        }
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField2_0($$parsedSource["author"]);
        }
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField3_0($$parsedSource["version"]);
        }
        if ("activationType" in $$parsedSource) {
            $$parsedSource["activationType"] = $$createField4_0($$parsedSource["activationType"]);
        }
        if ("uninstalled" in $$parsedSource) {
            $$parsedSource["uninstalled"] = $$createField5_0($$parsedSource["uninstalled"]);
        }
        if ("nameStr" in $$parsedSource) {
            $$parsedSource["nameStr"] = $$createField6_0($$parsedSource["nameStr"]);
        }
        if ("authorStr" in $$parsedSource) {
            $$parsedSource["authorStr"] = $$createField7_0($$parsedSource["authorStr"]);
        }
        if ("createTime" in $$parsedSource) {
            $$parsedSource["createTime"] = $$createField8_0($$parsedSource["createTime"]);
        }
        if ("updateTime" in $$parsedSource) {
            $$parsedSource["updateTime"] = $$createField9_0($$parsedSource["updateTime"]);
        }
        return new PluginQueryDTO($$parsedSource as Partial<PluginQueryDTO>);
    }
}

// Private type creation functions
const $$createType0 = query$0.QueryAttribute.createFrom($Create.Any);
const $$createType1 = query$0.QueryAttribute.createFrom($Create.Any);
const $$createType2 = query$0.QueryAttribute.createFrom($Create.Any);
