// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 搜索 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../../lvfeng-z/library-squirrel-sdk/dto/models.js";

/**
 * QuerySearchConditionPage 查询搜索条件分页
 */
export function QuerySearchConditionPage(page: number, pageSize: number, query: dto$0.SearchConditionQuery | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.SelectItem> | null> | null> {
    return $Call.ByID(1327794153, page, pageSize, query).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * QueryWorkPage 查询作品分页
 */
export function QueryWorkPage(pageNumber: number, pageSize: number, conditions: (dto$0.SearchCondition | null)[]): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.WorkFullDTO> | null> | null> {
    return $Call.ByID(4122454371, pageNumber, pageSize, conditions).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * QueryWorkSetPage 查询作品集分页（通过搜索条件筛选）
 */
export function QueryWorkSetPage(page: model$0.Page<dto$0.WorkSetWithCoverDTO> | null, conditions: (dto$0.SearchCondition | null)[]): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.WorkSetWithCoverDTO> | null> | null> {
    return $Call.ByID(1462328131, page, conditions).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * UpdateLastUsed 更新最后使用时间
 */
export function UpdateLastUsed(used: { [_ in dto$0.SearchType]?: number[] }): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2154720907, used).then(($result: any) => {
        return $$createType16($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.SelectItem.createFrom;
const $$createType1 = model$0.Page.createFrom($$createType0);
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = model$0.ApiResponse.createFrom($$createType2);
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = dto$0.WorkFullDTO.createFrom;
const $$createType6 = model$0.Page.createFrom($$createType5);
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.ApiResponse.createFrom($$createType7);
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = dto$0.WorkSetWithCoverDTO.createFrom;
const $$createType11 = model$0.Page.createFrom($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = model$0.ApiResponse.createFrom($$createType12);
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType16 = $Create.Nullable($$createType15);
