// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../database/sql/models.js";

/**
 * PluginWithExtension 带贡献点的插件
 */
export class PluginWithExtension {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "publicId": sql$0.NullString;
    "author": sql$0.NullString;
    "name": sql$0.NullString;
    "version": sql$0.NullString;
    "contractVersion": sql$0.NullInt64;

    /**
     * 插件声明的配置 schema 版本（plugin.json configSchemaVersion；0=legacy/未管理）
     */
    "configSchemaVersion": sql$0.NullInt64;
    "capabilities": sql$0.NullString;
    "description": sql$0.NullString;
    "changelog": sql$0.NullString;
    "entryPath": sql$0.NullString;
    "rootPath": sql$0.NullString;
    "backupId": sql$0.NullInt64;
    "sortNum": sql$0.NullInt64;
    "uninstalled": sql$0.NullBool;
    "activationType": sql$0.NullString;

    /**
     * 来源枚举 bundled/local/url/marketplace，由主程序按安装入口判定（不由插件声明）
     */
    "source": sql$0.NullString;

    /**
     * 来源详情（安装包路径或 URL），供追溯
     */
    "sourceDetail": sql$0.NullString;

    /**
     * 包级 SHA256(hex)，安装时对原始 zip 计算，纯追溯存档
     */
    "integrityHash": sql$0.NullString;

    /**
     * 信任标记：bundled=true，第三方经用户确认后 true；false 则不运行（运行门控）
     */
    "trusted": sql$0.NullBool;

    /**
     * 贡献点类型
     */
    "ExtensionKey": string;

    /**
     * 贡献点ID
     */
    "ExtensionID": string;

    /** Creates a new PluginWithExtension instance. */
    constructor($$source: Partial<PluginWithExtension> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("publicId" in $$source)) {
            this["publicId"] = (new sql$0.NullString());
        }
        if (!("author" in $$source)) {
            this["author"] = (new sql$0.NullString());
        }
        if (!("name" in $$source)) {
            this["name"] = (new sql$0.NullString());
        }
        if (!("version" in $$source)) {
            this["version"] = (new sql$0.NullString());
        }
        if (!("contractVersion" in $$source)) {
            this["contractVersion"] = (new sql$0.NullInt64());
        }
        if (!("configSchemaVersion" in $$source)) {
            this["configSchemaVersion"] = (new sql$0.NullInt64());
        }
        if (!("capabilities" in $$source)) {
            this["capabilities"] = (new sql$0.NullString());
        }
        if (!("description" in $$source)) {
            this["description"] = (new sql$0.NullString());
        }
        if (!("changelog" in $$source)) {
            this["changelog"] = (new sql$0.NullString());
        }
        if (!("entryPath" in $$source)) {
            this["entryPath"] = (new sql$0.NullString());
        }
        if (!("rootPath" in $$source)) {
            this["rootPath"] = (new sql$0.NullString());
        }
        if (!("backupId" in $$source)) {
            this["backupId"] = (new sql$0.NullInt64());
        }
        if (!("sortNum" in $$source)) {
            this["sortNum"] = (new sql$0.NullInt64());
        }
        if (!("uninstalled" in $$source)) {
            this["uninstalled"] = (new sql$0.NullBool());
        }
        if (!("activationType" in $$source)) {
            this["activationType"] = (new sql$0.NullString());
        }
        if (!("source" in $$source)) {
            this["source"] = (new sql$0.NullString());
        }
        if (!("sourceDetail" in $$source)) {
            this["sourceDetail"] = (new sql$0.NullString());
        }
        if (!("integrityHash" in $$source)) {
            this["integrityHash"] = (new sql$0.NullString());
        }
        if (!("trusted" in $$source)) {
            this["trusted"] = (new sql$0.NullBool());
        }
        if (!("ExtensionKey" in $$source)) {
            this["ExtensionKey"] = "";
        }
        if (!("ExtensionID" in $$source)) {
            this["ExtensionID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginWithExtension instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginWithExtension {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType0;
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType1;
        const $$createField16_0 = $$createType2;
        const $$createField17_0 = $$createType0;
        const $$createField18_0 = $$createType0;
        const $$createField19_0 = $$createType0;
        const $$createField20_0 = $$createType0;
        const $$createField21_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("publicId" in $$parsedSource) {
            $$parsedSource["publicId"] = $$createField3_0($$parsedSource["publicId"]);
        }
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField4_0($$parsedSource["author"]);
        }
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField5_0($$parsedSource["name"]);
        }
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField6_0($$parsedSource["version"]);
        }
        if ("contractVersion" in $$parsedSource) {
            $$parsedSource["contractVersion"] = $$createField7_0($$parsedSource["contractVersion"]);
        }
        if ("configSchemaVersion" in $$parsedSource) {
            $$parsedSource["configSchemaVersion"] = $$createField8_0($$parsedSource["configSchemaVersion"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField9_0($$parsedSource["capabilities"]);
        }
        if ("description" in $$parsedSource) {
            $$parsedSource["description"] = $$createField10_0($$parsedSource["description"]);
        }
        if ("changelog" in $$parsedSource) {
            $$parsedSource["changelog"] = $$createField11_0($$parsedSource["changelog"]);
        }
        if ("entryPath" in $$parsedSource) {
            $$parsedSource["entryPath"] = $$createField12_0($$parsedSource["entryPath"]);
        }
        if ("rootPath" in $$parsedSource) {
            $$parsedSource["rootPath"] = $$createField13_0($$parsedSource["rootPath"]);
        }
        if ("backupId" in $$parsedSource) {
            $$parsedSource["backupId"] = $$createField14_0($$parsedSource["backupId"]);
        }
        if ("sortNum" in $$parsedSource) {
            $$parsedSource["sortNum"] = $$createField15_0($$parsedSource["sortNum"]);
        }
        if ("uninstalled" in $$parsedSource) {
            $$parsedSource["uninstalled"] = $$createField16_0($$parsedSource["uninstalled"]);
        }
        if ("activationType" in $$parsedSource) {
            $$parsedSource["activationType"] = $$createField17_0($$parsedSource["activationType"]);
        }
        if ("source" in $$parsedSource) {
            $$parsedSource["source"] = $$createField18_0($$parsedSource["source"]);
        }
        if ("sourceDetail" in $$parsedSource) {
            $$parsedSource["sourceDetail"] = $$createField19_0($$parsedSource["sourceDetail"]);
        }
        if ("integrityHash" in $$parsedSource) {
            $$parsedSource["integrityHash"] = $$createField20_0($$parsedSource["integrityHash"]);
        }
        if ("trusted" in $$parsedSource) {
            $$parsedSource["trusted"] = $$createField21_0($$parsedSource["trusted"]);
        }
        return new PluginWithExtension($$parsedSource as Partial<PluginWithExtension>);
    }
}

// Private type creation functions
const $$createType0 = sql$0.NullString.createFrom;
const $$createType1 = sql$0.NullInt64.createFrom;
const $$createType2 = sql$0.NullBool.createFrom;
