// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * taskSnapshotDTO 快照推送 DTO，包含 Manager 实时快照 + 被移除任务的缓冲区
 */
export class taskSnapshotDTO {
    "tasks": (taskSnapshotItem | null)[];
    "parentTasks": (taskSnapshotItem | null)[];
    "removedTasks": (taskSnapshotItem | null)[];
    "removedParentTasks": (taskSnapshotItem | null)[];

    /** Creates a new taskSnapshotDTO instance. */
    constructor($$source: Partial<taskSnapshotDTO> = {}) {
        if (!("tasks" in $$source)) {
            this["tasks"] = [];
        }
        if (!("parentTasks" in $$source)) {
            this["parentTasks"] = [];
        }
        if (!("removedTasks" in $$source)) {
            this["removedTasks"] = [];
        }
        if (!("removedParentTasks" in $$source)) {
            this["removedParentTasks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new taskSnapshotDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): taskSnapshotDTO {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField0_0($$parsedSource["tasks"]);
        }
        if ("parentTasks" in $$parsedSource) {
            $$parsedSource["parentTasks"] = $$createField1_0($$parsedSource["parentTasks"]);
        }
        if ("removedTasks" in $$parsedSource) {
            $$parsedSource["removedTasks"] = $$createField2_0($$parsedSource["removedTasks"]);
        }
        if ("removedParentTasks" in $$parsedSource) {
            $$parsedSource["removedParentTasks"] = $$createField3_0($$parsedSource["removedParentTasks"]);
        }
        return new taskSnapshotDTO($$parsedSource as Partial<taskSnapshotDTO>);
    }
}

/**
 * taskSnapshotItem 快照中的单个任务条目
 */
export class taskSnapshotItem {
    "id": number;
    "taskName": string;
    "status": number;
    "total": number;
    "finished": number;

    /** Creates a new taskSnapshotItem instance. */
    constructor($$source: Partial<taskSnapshotItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("taskName" in $$source)) {
            this["taskName"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("finished" in $$source)) {
            this["finished"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new taskSnapshotItem instance from a string or object.
     */
    static createFrom($$source: any = {}): taskSnapshotItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new taskSnapshotItem($$parsedSource as Partial<taskSnapshotItem>);
    }
}

// Private type creation functions
const $$createType0 = taskSnapshotItem.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
