// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 作品 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../../lvfeng-z/library-squirrel-sdk/dto/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除作品
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2804424335, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取作品
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<dto$0.WorkDTO | null> | null> {
    return $Call.ByID(761599000, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetBySiteAndSiteWorkID 根据站点ID和站点作品ID获取作品
 */
export function GetBySiteAndSiteWorkID(siteId: number, siteWorkId: string): $CancellablePromise<model$0.ApiResponse<dto$0.WorkDTO | null> | null> {
    return $Call.ByID(4252213572, siteId, siteWorkId).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetFullWorkInfoByIds 批量获取完整作品信息
 */
export function GetFullWorkInfoByIds(ids: number[]): $CancellablePromise<model$0.ApiResponse<(dto$0.WorkFullDTO | null)[]> | null> {
    return $Call.ByID(3702036189, ids).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListRankedLocalAuthorWithWorkIdByWorkIds 根据作品ID列表获取带排名的本地作者
 */
export function ListRankedLocalAuthorWithWorkIdByWorkIds(workIds: number[]): $CancellablePromise<model$0.ApiResponse<(dto$0.RankedLocalAuthor | null)[]> | null> {
    return $Call.ByID(3147867833, workIds).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: model$0.Page<dto$0.WorkDTO> | null, query: $models.WorkQueryDTO): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.WorkDTO> | null> | null> {
    return $Call.ByID(916471787, page, query).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * Save 保存作品
 */
export function Save(work: dto$0.WorkDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(2065165505, work).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * SoftDelete 逻辑删除作品（移入回收站，可经回收站复原）
 */
export function SoftDelete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2303847439, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Update 更新作品
 */
export function Update(work: dto$0.WorkDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(17674021, work).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateLastUsed 批量更新作品最后使用时间
 */
export function UpdateLastUsed(ids: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2305023356, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = dto$0.WorkDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = dto$0.WorkFullDTO.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = model$0.ApiResponse.createFrom($$createType8);
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = dto$0.RankedLocalAuthor.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = model$0.ApiResponse.createFrom($$createType13);
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = model$0.Page.createFrom($$createType2);
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = model$0.ApiResponse.createFrom($$createType17);
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType21 = $Create.Nullable($$createType20);
