// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 任务 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTask 创建任务
 */
export function CreateTask(req: $models.CreateTaskRequest | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(4186072591, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CreateTaskByURL 根据传入的url创建任务
 */
export function CreateTaskByURL(url: string): $CancellablePromise<model$0.ApiResponse<$models.CreateTaskByURLResponse | null> | null> {
    return $Call.ByID(2243255827, url).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * DeleteTask 删除任务（包含子任务）- 批量删除
 */
export function DeleteTask(ids: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2576136752, ids).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<$models.TaskResultDTO | null> | null> {
    return $Call.ByID(1004381334, id).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ListChildrenTask 查询子任务列表
 */
export function ListChildrenTask(pid: number): $CancellablePromise<model$0.ApiResponse<($models.TaskResultDTO | null)[]> | null> {
    return $Call.ByID(4128042548, pid).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ListSchedule 查询任务进度列表
 */
export function ListSchedule(ids: number[]): $CancellablePromise<model$0.ApiResponse<($models.TaskScheduleDTO | null)[]> | null> {
    return $Call.ByID(4236291543, ids).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * ListStatus 查询状态列表
 */
export function ListStatus(ids: number[]): $CancellablePromise<model$0.ApiResponse<($models.TaskScheduleDTO | null)[]> | null> {
    return $Call.ByID(1739881180, ids).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * ListTaskTree 获取任务树列表
 */
export function ListTaskTree(taskIds: number[], ...includeStatus: number[]): $CancellablePromise<model$0.ApiResponse<($models.TaskResultDTO | null)[]> | null> {
    return $Call.ByID(867436771, taskIds, includeStatus).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * QueryChildrenTaskPage 查询子任务分页
 */
export function QueryChildrenTaskPage(pid: number, page: model$0.Page<$models.TaskResultDTO, $models.TaskQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.TaskResultDTO, $models.TaskQueryDTO> | null> | null> {
    return $Call.ByID(3312153847, pid, page).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: model$0.Page<$models.TaskResultDTO, $models.TaskQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.TaskResultDTO, $models.TaskQueryDTO> | null> | null> {
    return $Call.ByID(2367410609, page).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * QueryParentPage 分页查询父任务
 */
export function QueryParentPage(page: model$0.Page<$models.TaskResultDTO, $models.TaskQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.TaskResultDTO, $models.TaskQueryDTO> | null> | null> {
    return $Call.ByID(39626201, page).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * QueryTreeDataPage 查询任务树数据分页
 */
export function QueryTreeDataPage(page: model$0.Page<$models.TaskResultDTO, $models.TaskQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<$models.TreeDataPageDTO | null> | null> {
    return $Call.ByID(1518321709, page).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * RefreshStatus 刷新任务状态
 */
export function RefreshStatus(taskId: number): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(3363566231, taskId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Save 保存任务
 */
export function Save(task: $models.TaskDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(1923742947, task).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SetTreeStatus 设置任务树状态
 */
export function SetTreeStatus(taskIds: number[], status: number, includeStatus: number[]): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(3797064012, taskIds, status, includeStatus).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Update 更新任务
 */
export function Update(task: $models.TaskDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3556737999, task).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.CreateTaskByURLResponse.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.TaskResultDTO.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = model$0.ApiResponse.createFrom($$createType9);
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType9);
const $$createType13 = model$0.ApiResponse.createFrom($$createType12);
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $models.TaskScheduleDTO.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = model$0.ApiResponse.createFrom($$createType17);
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $models.TaskQueryDTO.createFrom;
const $$createType21 = model$0.Page.createFrom($$createType8, $$createType20);
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = model$0.ApiResponse.createFrom($$createType22);
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $models.TreeDataPageDTO.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = model$0.ApiResponse.createFrom($$createType26);
const $$createType28 = $Create.Nullable($$createType27);
