// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CreateTaskByURLResponse 根据URL创建任务的响应
 */
export class CreateTaskByURLResponse {
    "succeed": boolean;
    "addedQuantity": number;
    "msg": string;

    /** Creates a new CreateTaskByURLResponse instance. */
    constructor($$source: Partial<CreateTaskByURLResponse> = {}) {
        if (!("succeed" in $$source)) {
            this["succeed"] = false;
        }
        if (!("addedQuantity" in $$source)) {
            this["addedQuantity"] = 0;
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTaskByURLResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTaskByURLResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTaskByURLResponse($$parsedSource as Partial<CreateTaskByURLResponse>);
    }
}

/**
 * CreateTaskRequest 创建任务请求
 */
export class CreateTaskRequest {
    "pid": number;
    "taskName": string;
    "siteId": number;
    "siteWorkId": string;
    "url": string;
    "isCollection": number;
    "pluginPublicId": string;
    "pluginContributionId": string;
    "pluginData": string;

    /** Creates a new CreateTaskRequest instance. */
    constructor($$source: Partial<CreateTaskRequest> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("taskName" in $$source)) {
            this["taskName"] = "";
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = 0;
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("isCollection" in $$source)) {
            this["isCollection"] = 0;
        }
        if (!("pluginPublicId" in $$source)) {
            this["pluginPublicId"] = "";
        }
        if (!("pluginContributionId" in $$source)) {
            this["pluginContributionId"] = "";
        }
        if (!("pluginData" in $$source)) {
            this["pluginData"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTaskRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTaskRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTaskRequest($$parsedSource as Partial<CreateTaskRequest>);
    }
}

/**
 * TaskQueryDTO 任务查询条件
 */
export class TaskQueryDTO {
    /**
     * 父任务ID
     */
    "pid": number | null;

    /**
     * 站点ID
     */
    "siteId": number | null;

    /**
     * 站点作品ID
     */
    "siteWorkId": string | null;

    /**
     * 任务状态
     */
    "status": number | null;

    /**
     * 是否为合集（0=否，1=是）
     */
    "isCollection": number | null;

    /**
     * 插件公开ID
     */
    "pluginPublicId": string | null;

    /**
     * 插件贡献ID
     */
    "pluginContributionId": string | null;

    /**
     * 是否可继续（0=否，1=是）
     */
    "continuable": number | null;

    /**
     * 模糊查询
     * 任务名称（模糊匹配）
     */
    "taskNameLike": string | null;

    /**
     * 排序字段：create_time, update_time, task_name
     * 排序字段
     */
    "orderBy": string;

    /**
     * 是否降序
     */
    "orderDesc": boolean;

    /** Creates a new TaskQueryDTO instance. */
    constructor($$source: Partial<TaskQueryDTO> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = null;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = null;
        }
        if (!("isCollection" in $$source)) {
            this["isCollection"] = null;
        }
        if (!("pluginPublicId" in $$source)) {
            this["pluginPublicId"] = null;
        }
        if (!("pluginContributionId" in $$source)) {
            this["pluginContributionId"] = null;
        }
        if (!("continuable" in $$source)) {
            this["continuable"] = null;
        }
        if (!("taskNameLike" in $$source)) {
            this["taskNameLike"] = null;
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = "";
        }
        if (!("orderDesc" in $$source)) {
            this["orderDesc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskQueryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskQueryDTO($$parsedSource as Partial<TaskQueryDTO>);
    }
}

/**
 * TaskScheduleDTO 任务进度DTO
 */
export class TaskScheduleDTO {
    "id": number;
    "pid": number;
    "status": number;
    "schedule": number;

    /** Creates a new TaskScheduleDTO instance. */
    constructor($$source: Partial<TaskScheduleDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("schedule" in $$source)) {
            this["schedule"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskScheduleDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskScheduleDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskScheduleDTO($$parsedSource as Partial<TaskScheduleDTO>);
    }
}
