// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 作品集 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../base/model/dto/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除作品集
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3283039871, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取作品集
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<dto$0.WorkSetDTO | null> | null> {
    return $Call.ByID(1722582344, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetBySiteWorkSetIdAndSiteName 根据站点作品集ID和站点名称获取作品集
 */
export function GetBySiteWorkSetIdAndSiteName(siteWorkSetId: string, siteName: string): $CancellablePromise<model$0.ApiResponse<dto$0.WorkSetDTO | null> | null> {
    return $Call.ByID(1868450757, siteWorkSetId, siteName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetCoverWorkId 获取封面作品ID
 */
export function GetCoverWorkId(workSetId: number): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(2034482923, workSetId).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetWorksByWorkSetId 获取作品集下的作品列表
 */
export function GetWorksByWorkSetId(workSetId: number): $CancellablePromise<model$0.ApiResponse<(dto$0.WorkDTO | null)[]> | null> {
    return $Call.ByID(2302895211, workSetId).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * LinkBatchToWorkSet 批量关联作品到作品集
 */
export function LinkBatchToWorkSet(workSetId: number, workIds: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3354398736, workSetId, workIds).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LinkWorkToWorkSet 关联作品到作品集
 */
export function LinkWorkToWorkSet(workId: number, workSetId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1571076107, workId, workSetId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListWorkSetWithWorkByIds 根据作品集ID列表获取作品集及作品完整信息
 */
export function ListWorkSetWithWorkByIds(workSetIds: number[]): $CancellablePromise<model$0.ApiResponse<(dto$0.WorkSetWithWorksResultDTO | null)[]> | null> {
    return $Call.ByID(3476290543, workSetIds).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: model$0.Page<dto$0.WorkSetDTO> | null, query: $models.WorkSetQueryDTO): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.WorkSetDTO> | null> | null> {
    return $Call.ByID(1196822459, page, query).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * QueryPageWithCover 分页查询作品集（带封面）
 */
export function QueryPageWithCover(page: model$0.Page<dto$0.WorkSetWithCoverDTO> | null, query: $models.WorkSetQueryDTO): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.WorkSetWithCoverDTO> | null> | null> {
    return $Call.ByID(454983370, page, query).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * RemoveBatchFromWorkSet 批量从作品集移除作品
 */
export function RemoveBatchFromWorkSet(workSetId: number, workIds: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1044444007, workSetId, workIds).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Save 保存作品集
 */
export function Save(workSet: dto$0.WorkSetDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(41190161, workSet).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SetCover 设置作品集封面
 */
export function SetCover(workSetId: number, workId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2722729479, workSetId, workId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UnlinkWorkFromWorkSet 取消作品与作品集的关联
 */
export function UnlinkWorkFromWorkSet(workId: number, workSetId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1424251277, workId, workSetId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UnsetCover 取消作品集封面
 */
export function UnsetCover(workSetId: number, workId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2668425816, workSetId, workId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Update 更新作品集
 */
export function Update(workSet: dto$0.WorkSetDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(278496405, workSet).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateSortOrders 批量更新排序顺序
 */
export function UpdateSortOrders(workSetId: number, workIds: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1296878944, workSetId, workIds).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = dto$0.WorkSetDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = dto$0.WorkDTO.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = model$0.ApiResponse.createFrom($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = dto$0.WorkSetWithWorksResultDTO.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = model$0.ApiResponse.createFrom($$createType15);
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = model$0.Page.createFrom($$createType2);
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = model$0.ApiResponse.createFrom($$createType19);
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = dto$0.WorkSetWithCoverDTO.createFrom;
const $$createType23 = model$0.Page.createFrom($$createType22);
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = model$0.ApiResponse.createFrom($$createType24);
const $$createType26 = $Create.Nullable($$createType25);
