// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../base/query/models.js";

/**
 * WorkSetQueryDTO 作品集查询条件
 */
export class WorkSetQueryDTO {
    /**
     * 站点ID
     */
    "siteId": query$0.QueryAttribute<number>;

    /**
     * 站点作品集ID
     */
    "siteWorkSetId": query$0.QueryAttribute<number>;

    /**
     * 站点作者ID
     */
    "siteAuthorId": query$0.QueryAttribute<number>;

    /**
     * 昵称（精确匹配）
     */
    "nickName": query$0.QueryAttribute<string>;

    /**
     * 站点作品集名称（模糊匹配）
     */
    "siteWorkSetName": query$0.QueryAttribute<string>;

    /**
     * 站点作品集描述（模糊匹配）
     */
    "siteWorkSetDesc": query$0.QueryAttribute<string>;

    /**
     * 昵称（模糊匹配）
     */
    "nickNameStr": query$0.QueryAttribute<string>;

    /**
     * 创建时间（可用于排序）
     */
    "createTime": query$0.QueryAttribute<number>;

    /**
     * 更新时间（可用于排序）
     */
    "updateTime": query$0.QueryAttribute<number>;

    /** Creates a new WorkSetQueryDTO instance. */
    constructor($$source: Partial<WorkSetQueryDTO> = {}) {
        if (!("siteId" in $$source)) {
            this["siteId"] = (new query$0.QueryAttribute());
        }
        if (!("siteWorkSetId" in $$source)) {
            this["siteWorkSetId"] = (new query$0.QueryAttribute());
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = (new query$0.QueryAttribute());
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = (new query$0.QueryAttribute());
        }
        if (!("siteWorkSetName" in $$source)) {
            this["siteWorkSetName"] = (new query$0.QueryAttribute());
        }
        if (!("siteWorkSetDesc" in $$source)) {
            this["siteWorkSetDesc"] = (new query$0.QueryAttribute());
        }
        if (!("nickNameStr" in $$source)) {
            this["nickNameStr"] = (new query$0.QueryAttribute());
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = (new query$0.QueryAttribute());
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = (new query$0.QueryAttribute());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetQueryDTO {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField0_0($$parsedSource["siteId"]);
        }
        if ("siteWorkSetId" in $$parsedSource) {
            $$parsedSource["siteWorkSetId"] = $$createField1_0($$parsedSource["siteWorkSetId"]);
        }
        if ("siteAuthorId" in $$parsedSource) {
            $$parsedSource["siteAuthorId"] = $$createField2_0($$parsedSource["siteAuthorId"]);
        }
        if ("nickName" in $$parsedSource) {
            $$parsedSource["nickName"] = $$createField3_0($$parsedSource["nickName"]);
        }
        if ("siteWorkSetName" in $$parsedSource) {
            $$parsedSource["siteWorkSetName"] = $$createField4_0($$parsedSource["siteWorkSetName"]);
        }
        if ("siteWorkSetDesc" in $$parsedSource) {
            $$parsedSource["siteWorkSetDesc"] = $$createField5_0($$parsedSource["siteWorkSetDesc"]);
        }
        if ("nickNameStr" in $$parsedSource) {
            $$parsedSource["nickNameStr"] = $$createField6_0($$parsedSource["nickNameStr"]);
        }
        if ("createTime" in $$parsedSource) {
            $$parsedSource["createTime"] = $$createField7_0($$parsedSource["createTime"]);
        }
        if ("updateTime" in $$parsedSource) {
            $$parsedSource["updateTime"] = $$createField8_0($$parsedSource["updateTime"]);
        }
        return new WorkSetQueryDTO($$parsedSource as Partial<WorkSetQueryDTO>);
    }
}

// Private type creation functions
const $$createType0 = query$0.QueryAttribute.createFrom($Create.Any);
const $$createType1 = query$0.QueryAttribute.createFrom($Create.Any);
