// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../../database/sql/models.js";

/**
 * ReWorkTag 作品与标签关联
 */
export class ReWorkTag {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "workId": sql$0.NullInt64;
    "tagType": sql$0.NullInt64;
    "localTagId": sql$0.NullInt64;
    "siteTagId": sql$0.NullInt64;

    /**
     * 关联级 namespace（site 关联=所指 site_tag.namespace 镜像；local 关联=用户自设/null）
     */
    "namespace": sql$0.NullString;

    /**
     * Source 关联写入来源（constant.PLUGIN/MANUAL）：作品重拉只窄域重建插件来源关联，用户手动挂的关联不动；
     * 冲突 upsert 不写本列，先建行者的来源保持不变
     */
    "source": number;

    /** Creates a new ReWorkTag instance. */
    constructor($$source: Partial<ReWorkTag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("workId" in $$source)) {
            this["workId"] = (new sql$0.NullInt64());
        }
        if (!("tagType" in $$source)) {
            this["tagType"] = (new sql$0.NullInt64());
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = (new sql$0.NullInt64());
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = (new sql$0.NullInt64());
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = (new sql$0.NullString());
        }
        if (!("source" in $$source)) {
            this["source"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReWorkTag instance from a string or object.
     */
    static createFrom($$source: any = {}): ReWorkTag {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workId" in $$parsedSource) {
            $$parsedSource["workId"] = $$createField3_0($$parsedSource["workId"]);
        }
        if ("tagType" in $$parsedSource) {
            $$parsedSource["tagType"] = $$createField4_0($$parsedSource["tagType"]);
        }
        if ("localTagId" in $$parsedSource) {
            $$parsedSource["localTagId"] = $$createField5_0($$parsedSource["localTagId"]);
        }
        if ("siteTagId" in $$parsedSource) {
            $$parsedSource["siteTagId"] = $$createField6_0($$parsedSource["siteTagId"]);
        }
        if ("namespace" in $$parsedSource) {
            $$parsedSource["namespace"] = $$createField7_0($$parsedSource["namespace"]);
        }
        return new ReWorkTag($$parsedSource as Partial<ReWorkTag>);
    }
}

// Private type creation functions
const $$createType0 = sql$0.NullInt64.createFrom;
const $$createType1 = sql$0.NullString.createFrom;
