// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 分享 Handler（Wails Bind 方法，经 IPC 暴露给前端）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ShareCancelPublish 取消分享（停止 share-host 任务；已在线会话的撤销走 ShareRevoke）
 */
export function ShareCancelPublish(shareID: string): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3883396668, shareID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ShareConsumePendingLink 取走深链到达时缓存的待处理链接（前端启动衔接：深链事件可能
 * 先于前端就绪，消费式拉取兜底；空串=无待处理）
 */
export function ShareConsumePendingLink(): $CancellablePromise<model$0.ApiResponse<string> | null> {
    return $Call.ByID(60036526).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ShareProtocolRegStatus 深链协议注册状态（Windows 为 HKCU 自注册视图，其余平台恒未注册）
 */
export function ShareProtocolRegStatus(): $CancellablePromise<model$0.ApiResponse<$models.ShareProtocolRegStatus | null> | null> {
    return $Call.ByID(2347159049).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SharePublish 启动分享发布（异步：立即返回 shareID，进度/完成/会话状态经 share-events 推送）。
 * workIDs/workSetIds 为前端选中 id 列表（与导出同形态）；options 见 SharePublishOptions。
 */
export function SharePublish(workIDs: number[], workSetIDs: number[], options: $models.SharePublishOptions): $CancellablePromise<model$0.ApiResponse<string> | null> {
    return $Call.ByID(191296510, workIDs, workSetIDs, options).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ShareReceive 启动收件拉取：解析分享链接（深链或 https 分享链接，可含访问密码）→
 * 创建并启动 share-receive 任务，返回任务 ID（进度/终态由任务面板承载）。
 */
export function ShareReceive(link: string, password: string): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(980252716, link, password).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ShareRevoke 撤销分享会话（在线即在中继即时生效，后续拨号被拒）
 */
export function ShareRevoke(shareID: string): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2828240061, shareID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ShareSessions 查询全部分享会话快照（含终态）
 */
export function ShareSessions(): $CancellablePromise<model$0.ApiResponse<($models.ShareSessionDTO | null)[]> | null> {
    return $Call.ByID(1815905174).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * ShareUnregisterProtocol 取消深链协议注册（便携版无卸载器的清理入口；安装版 HKLM 键
 * 由卸载器管理，不受影响）
 */
export function ShareUnregisterProtocol(): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(4145005145).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ShareProtocolRegStatus.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.ApiResponse.createFrom($$createType5);
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.ShareSessionDTO.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = model$0.ApiResponse.createFrom($$createType12);
const $$createType14 = $Create.Nullable($$createType13);
