// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ShareProtocolRegStatus 深链协议注册状态（HKCU 视图）
 */
export class ShareProtocolRegStatus {
    /**
     * HKCU 注册键存在且 command 非空
     */
    "registered": boolean;

    /**
     * 当前注册的启动命令
     */
    "command": string;

    /**
     * 注册命令是否指向当前运行的 exe
     */
    "currentExe": boolean;

    /** Creates a new ShareProtocolRegStatus instance. */
    constructor($$source: Partial<ShareProtocolRegStatus> = {}) {
        if (!("registered" in $$source)) {
            this["registered"] = false;
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("currentExe" in $$source)) {
            this["currentExe"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareProtocolRegStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareProtocolRegStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareProtocolRegStatus($$parsedSource as Partial<ShareProtocolRegStatus>);
    }
}

/**
 * SharePublishOptions 发布选项（IPC 入参）
 */
export class SharePublishOptions {
    /**
     * Title 落地页标题；空=默认标题（已选 N 项分享）
     */
    "title": string;

    /**
     * ExpireSeconds 有效期秒数：-1=中继默认(7 天)；0=无限期；>0=自定义秒数
     */
    "expireSeconds": number;

    /**
     * Password 访问密码；空=无密码（明文仅在本机使用，线上只走 sha256 摘要；落任务载荷的只有摘要）
     */
    "password": string;

    /** Creates a new SharePublishOptions instance. */
    constructor($$source: Partial<SharePublishOptions> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("expireSeconds" in $$source)) {
            this["expireSeconds"] = 0;
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SharePublishOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): SharePublishOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SharePublishOptions($$parsedSource as Partial<SharePublishOptions>);
    }
}

/**
 * ShareSessionDTO 分享会话快照（IPC DTO：状态查询返回值与 state 事件载荷共用）
 */
export class ShareSessionDTO {
    "shareId": string;

    /**
     * 中继会话 token（访问凭证）
     */
    "token": string;

    /**
     * 完整分享链接（含 fragment 密钥；未在线为空）
     */
    "link": string;

    /**
     * 落地页标题
     */
    "title": string;

    /**
     * 分享作品数
     */
    "workCount": number;

    /**
     * 白名单文件数（不含缺失）
     */
    "fileCount": number;

    /**
     * 白名单文件总字节
     */
    "totalBytes": number;

    /**
     * 源文件缺失数
     */
    "missingFiles": number;

    /**
     * 到期时刻（unix 毫秒，0=无限期）
     */
    "expiresAt": number;
    "passwordProtected": boolean;

    /**
     * connecting/online/reconnecting/revoked/expired/failed
     */
    "state": string;
    "streamsServed": number;
    "bytesServed": number;
    "createdAt": number;
    "relayAddress": string;
    "errMsg": string;

    /** Creates a new ShareSessionDTO instance. */
    constructor($$source: Partial<ShareSessionDTO> = {}) {
        if (!("shareId" in $$source)) {
            this["shareId"] = "";
        }
        if (!("token" in $$source)) {
            this["token"] = "";
        }
        if (!("link" in $$source)) {
            this["link"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("workCount" in $$source)) {
            this["workCount"] = 0;
        }
        if (!("fileCount" in $$source)) {
            this["fileCount"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("missingFiles" in $$source)) {
            this["missingFiles"] = 0;
        }
        if (!("expiresAt" in $$source)) {
            this["expiresAt"] = 0;
        }
        if (!("passwordProtected" in $$source)) {
            this["passwordProtected"] = false;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("streamsServed" in $$source)) {
            this["streamsServed"] = 0;
        }
        if (!("bytesServed" in $$source)) {
            this["bytesServed"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = 0;
        }
        if (!("relayAddress" in $$source)) {
            this["relayAddress"] = "";
        }
        if (!("errMsg" in $$source)) {
            this["errMsg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareSessionDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareSessionDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareSessionDTO($$parsedSource as Partial<ShareSessionDTO>);
    }
}
