// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 站点标签 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除站点标签
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2828208107, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<model$1.SiteTag | null> | null> {
    return $Call.ByID(2899204012, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListByWorkId 根据作品ID获取标签列表
 */
export function ListByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<(model$1.SiteTag | null)[]> | null> {
    return $Call.ByID(94223277, workId).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: number, pageSize: number, queryDTO: $models.SiteTagQueryDTO | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<model$1.SiteTag> | null> | null> {
    return $Call.ByID(4275757295, page, pageSize, queryDTO).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * QuerySelectItemPageByWorkId 根据作品ID分页查询选择项
 */
export function QuerySelectItemPageByWorkId(page: number, pageSize: number, queryDTO: $models.SiteTagQueryDTO | null, workId: number): $CancellablePromise<model$0.ApiResponse<model$0.Page<model$1.SelectItem> | null> | null> {
    return $Call.ByID(4042932845, page, pageSize, queryDTO, workId).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * Save 保存站点标签
 */
export function Save(tag: $models.SiteTagDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(4113095981, tag).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * Update 更新站点标签
 */
export function Update(tag: $models.SiteTagDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3226027185, tag).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateLastUse 更新最后使用时间
 */
export function UpdateLastUse(ids: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2858868948, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$1.SiteTag.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType3);
const $$createType7 = model$0.ApiResponse.createFrom($$createType6);
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = model$0.Page.createFrom($$createType2);
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = model$0.ApiResponse.createFrom($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = model$1.SelectItem.createFrom;
const $$createType14 = model$0.Page.createFrom($$createType13);
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = model$0.ApiResponse.createFrom($$createType15);
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType19 = $Create.Nullable($$createType18);
