// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 站点标签 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateAndBindSameNameLocalTag 创建并绑定同名本地标签
 */
export function CreateAndBindSameNameLocalTag(siteTag: $models.SiteTagDTO | null): $CancellablePromise<model$0.ApiResponse<$models.LocalTagDTO | null> | null> {
    return $Call.ByID(209855906, siteTag).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Delete 删除站点标签
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2828208107, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<$models.SiteTagResultDTO | null> | null> {
    return $Call.ByID(2899204012, id).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListBySiteTagIds 根据站点标签ID列表获取
 */
export function ListBySiteTagIds(siteTagIds: number[]): $CancellablePromise<model$0.ApiResponse<($models.SiteTagResultDTO | null)[]> | null> {
    return $Call.ByID(3703036720, siteTagIds).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListByWorkId 根据作品ID获取标签列表
 */
export function ListByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<($models.SiteTagResultDTO | null)[]> | null> {
    return $Call.ByID(94223277, workId).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * QueryBoundOrUnboundToLocalTagPage 查询绑定或未绑定到本地标签的站点标签分页
 */
export function QueryBoundOrUnboundToLocalTagPage(page: model$0.Page<$models.SiteTagQueryDTO, $models.SiteTagQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.SiteTagFullDTO, $models.SiteTagQueryDTO> | null> | null> {
    return $Call.ByID(4186749337, page).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * QueryLocalRelateDTOPage 查询站点标签与本地标签关联DTO分页
 */
export function QueryLocalRelateDTOPage(page: model$0.Page<$models.SiteTagQueryDTO, $models.SiteTagQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.SiteTagLocalRelateDTO, $models.SiteTagQueryDTO> | null> | null> {
    return $Call.ByID(1761256276, page).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: model$0.Page<$models.SiteTagQueryDTO, $models.SiteTagQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.SiteTagResultDTO, $models.SiteTagQueryDTO> | null> | null> {
    return $Call.ByID(4275757295, page).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * QueryPageByWorkId 根据作品ID分页查询站点标签
 */
export function QueryPageByWorkId(page: model$0.Page<$models.SiteTagQueryDTO, $models.SiteTagQueryDTO> | null, workId: number): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.SiteTagFullDTO, $models.SiteTagQueryDTO> | null> | null> {
    return $Call.ByID(1002654178, page, workId).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * QuerySelectItemPageByWorkId 根据作品ID分页查询选择项
 */
export function QuerySelectItemPageByWorkId(page: model$0.Page<$models.SiteTagQueryDTO, $models.SiteTagQueryDTO> | null, workId: number): $CancellablePromise<model$0.ApiResponse<model$0.Page<model$1.SelectItem, $models.SiteTagQueryDTO> | null> | null> {
    return $Call.ByID(4042932845, page, workId).then(($result: any) => {
        return $$createType32($result);
    });
}

/**
 * Save 保存站点标签
 */
export function Save(tag: $models.SiteTagDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(4113095981, tag).then(($result: any) => {
        return $$createType34($result);
    });
}

/**
 * SaveBatch 批量保存站点标签
 */
export function SaveBatch(tags: ($models.SiteTagDTO | null)[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(411851267, tags).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Update 更新站点标签
 */
export function Update(tag: $models.SiteTagDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3226027185, tag).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateBindLocalTag 更新绑定本地标签
 */
export function UpdateBindLocalTag(localTagId: number, siteTagIds: number[]): $CancellablePromise<model$0.ApiResponse<boolean> | null> {
    return $Call.ByID(1869161719, localTagId, siteTagIds).then(($result: any) => {
        return $$createType36($result);
    });
}

/**
 * UpdateLastUse 更新最后使用时间
 */
export function UpdateLastUse(ids: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2858868948, ids).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LocalTagDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ApiResponse.createFrom($$createType1);
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.SiteTagResultDTO.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.ApiResponse.createFrom($$createType7);
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType7);
const $$createType11 = model$0.ApiResponse.createFrom($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.SiteTagFullDTO.createFrom;
const $$createType14 = $models.SiteTagQueryDTO.createFrom;
const $$createType15 = model$0.Page.createFrom($$createType13, $$createType14);
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = model$0.ApiResponse.createFrom($$createType16);
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $models.SiteTagLocalRelateDTO.createFrom;
const $$createType20 = model$0.Page.createFrom($$createType19, $$createType14);
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = model$0.ApiResponse.createFrom($$createType21);
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = model$0.Page.createFrom($$createType6, $$createType14);
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = model$0.ApiResponse.createFrom($$createType25);
const $$createType27 = $Create.Nullable($$createType26);
const $$createType28 = model$1.SelectItem.createFrom;
const $$createType29 = model$0.Page.createFrom($$createType28, $$createType14);
const $$createType30 = $Create.Nullable($$createType29);
const $$createType31 = model$0.ApiResponse.createFrom($$createType30);
const $$createType32 = $Create.Nullable($$createType31);
const $$createType33 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType34 = $Create.Nullable($$createType33);
const $$createType35 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType36 = $Create.Nullable($$createType35);
