// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../../pkg/query/models.js";

/**
 * LocalTagDTO 本地标签数据传输对象
 */
export class LocalTagDTO {
    "id": number;
    "localTagName": string | null;
    "baseLocalTagId": number | null;
    "description": string | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new LocalTagDTO instance. */
    constructor($$source: Partial<LocalTagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("localTagName" in $$source)) {
            this["localTagName"] = null;
        }
        if (!("baseLocalTagId" in $$source)) {
            this["baseLocalTagId"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalTagDTO($$parsedSource as Partial<LocalTagDTO>);
    }
}

/**
 * SiteTagDTO 站点标签数据传输对象
 */
export class SiteTagDTO {
    "id": number;
    "siteId": number | null;
    "siteTagId": string | null;
    "siteTagName": string | null;
    "description": string | null;

    /** Creates a new SiteTagDTO instance. */
    constructor($$source: Partial<SiteTagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = null;
        }
        if (!("siteTagName" in $$source)) {
            this["siteTagName"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteTagDTO($$parsedSource as Partial<SiteTagDTO>);
    }
}

/**
 * SiteTagFullDTO 站点标签完整信息DTO
 */
export class SiteTagFullDTO {
    "id": number;
    "siteId": number | null;
    "siteTagId": string | null;
    "siteTagName": string | null;
    "baseSiteTagId": string | null;
    "description": string | null;
    "localTagId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;
    "localTag"?: LocalTagDTO | null;

    /** Creates a new SiteTagFullDTO instance. */
    constructor($$source: Partial<SiteTagFullDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = null;
        }
        if (!("siteTagName" in $$source)) {
            this["siteTagName"] = null;
        }
        if (!("baseSiteTagId" in $$source)) {
            this["baseSiteTagId"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagFullDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagFullDTO {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localTag" in $$parsedSource) {
            $$parsedSource["localTag"] = $$createField10_0($$parsedSource["localTag"]);
        }
        return new SiteTagFullDTO($$parsedSource as Partial<SiteTagFullDTO>);
    }
}

/**
 * SiteTagLocalRelateDTO 站点标签与本地标签关联DTO
 */
export class SiteTagLocalRelateDTO {
    "id": number;
    "siteId": number | null;
    "siteTagId": string | null;
    "siteTagName": string | null;
    "baseSiteTagId": string | null;
    "description": string | null;
    "localTagId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;
    "localTag"?: LocalTagDTO | null;

    /** Creates a new SiteTagLocalRelateDTO instance. */
    constructor($$source: Partial<SiteTagLocalRelateDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = null;
        }
        if (!("siteTagName" in $$source)) {
            this["siteTagName"] = null;
        }
        if (!("baseSiteTagId" in $$source)) {
            this["baseSiteTagId"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagLocalRelateDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagLocalRelateDTO {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localTag" in $$parsedSource) {
            $$parsedSource["localTag"] = $$createField10_0($$parsedSource["localTag"]);
        }
        return new SiteTagLocalRelateDTO($$parsedSource as Partial<SiteTagLocalRelateDTO>);
    }
}

/**
 * SiteTagQueryDTO 站点标签查询条件
 */
export class SiteTagQueryDTO {
    /**
     * 站点ID
     */
    "siteId": query$0.QueryAttribute;

    /**
     * 站点标签ID（外部）
     */
    "siteTagId": query$0.QueryAttribute;

    /**
     * 基础站点标签ID
     */
    "baseSiteTagId": query$0.QueryAttribute;

    /**
     * 本地标签ID
     */
    "localTagId": query$0.QueryAttribute;

    /**
     * 是否绑定到指定本地标签（非数据库字段）
     */
    "boundOnLocalTagId": query$0.QueryAttribute;

    /**
     * 站点标签名称（模糊匹配）
     */
    "siteTagName": query$0.QueryAttribute;

    /**
     * 描述（模糊匹配）
     */
    "description": query$0.QueryAttribute;

    /**
     * 更新时间（可用于排序）
     */
    "updateTime": query$0.QueryAttribute;

    /**
     * 创建时间（可用于排序）
     */
    "createTime": query$0.QueryAttribute;

    /** Creates a new SiteTagQueryDTO instance. */
    constructor($$source: Partial<SiteTagQueryDTO> = {}) {
        if (!("siteId" in $$source)) {
            this["siteId"] = (new query$0.QueryAttribute());
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = (new query$0.QueryAttribute());
        }
        if (!("baseSiteTagId" in $$source)) {
            this["baseSiteTagId"] = (new query$0.QueryAttribute());
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = (new query$0.QueryAttribute());
        }
        if (!("boundOnLocalTagId" in $$source)) {
            this["boundOnLocalTagId"] = (new query$0.QueryAttribute());
        }
        if (!("siteTagName" in $$source)) {
            this["siteTagName"] = (new query$0.QueryAttribute());
        }
        if (!("description" in $$source)) {
            this["description"] = (new query$0.QueryAttribute());
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = (new query$0.QueryAttribute());
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = (new query$0.QueryAttribute());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagQueryDTO {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField0_0($$parsedSource["siteId"]);
        }
        if ("siteTagId" in $$parsedSource) {
            $$parsedSource["siteTagId"] = $$createField1_0($$parsedSource["siteTagId"]);
        }
        if ("baseSiteTagId" in $$parsedSource) {
            $$parsedSource["baseSiteTagId"] = $$createField2_0($$parsedSource["baseSiteTagId"]);
        }
        if ("localTagId" in $$parsedSource) {
            $$parsedSource["localTagId"] = $$createField3_0($$parsedSource["localTagId"]);
        }
        if ("boundOnLocalTagId" in $$parsedSource) {
            $$parsedSource["boundOnLocalTagId"] = $$createField4_0($$parsedSource["boundOnLocalTagId"]);
        }
        if ("siteTagName" in $$parsedSource) {
            $$parsedSource["siteTagName"] = $$createField5_0($$parsedSource["siteTagName"]);
        }
        if ("description" in $$parsedSource) {
            $$parsedSource["description"] = $$createField6_0($$parsedSource["description"]);
        }
        if ("updateTime" in $$parsedSource) {
            $$parsedSource["updateTime"] = $$createField7_0($$parsedSource["updateTime"]);
        }
        if ("createTime" in $$parsedSource) {
            $$parsedSource["createTime"] = $$createField8_0($$parsedSource["createTime"]);
        }
        return new SiteTagQueryDTO($$parsedSource as Partial<SiteTagQueryDTO>);
    }
}

/**
 * SiteTagResultDTO 站点标签返回结果DTO（用于屏蔽sql.Null*类型）
 */
export class SiteTagResultDTO {
    "id": number;
    "siteId": number | null;
    "siteTagId": string | null;
    "siteTagName": string | null;
    "baseSiteTagId": string | null;
    "description": string | null;
    "localTagId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new SiteTagResultDTO instance. */
    constructor($$source: Partial<SiteTagResultDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = null;
        }
        if (!("siteTagName" in $$source)) {
            this["siteTagName"] = null;
        }
        if (!("baseSiteTagId" in $$source)) {
            this["baseSiteTagId"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteTagResultDTO($$parsedSource as Partial<SiteTagResultDTO>);
    }
}

// Private type creation functions
const $$createType0 = LocalTagDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = query$0.QueryAttribute.createFrom;
