// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 站点浏览器 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../base/model/dto/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetByID 根据ID获取站点浏览器
 */
export function GetByID(pluginPublicId: string, extensionId: string): $CancellablePromise<model$0.ApiResponse<dto$0.SiteBrowserDTO | null> | null> {
    return $Call.ByID(908248202, pluginPublicId, extensionId).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetByPluginID 根据插件ID获取站点浏览器
 */
export function GetByPluginID(pluginId: number): $CancellablePromise<model$0.ApiResponse<(dto$0.SiteBrowserDTO | null)[]> | null> {
    return $Call.ByID(1002260721, pluginId).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * List 获取所有站点浏览器
 */
export function List(): $CancellablePromise<model$0.ApiResponse<(dto$0.SiteBrowserDTO | null)[]> | null> {
    return $Call.ByID(931532158).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Open 打开站点浏览器
 */
export function Open(pluginPublicId: string, extensionId: string): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3393200362, pluginPublicId, extensionId).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * QueryPage 分页查询站点浏览器
 */
export function QueryPage(page: number, pageSize: number): $CancellablePromise<model$0.ApiResponse<$models.PageResult | null> | null> {
    return $Call.ByID(3071395573, page, pageSize).then(($result: any) => {
        return $$createType12($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.SiteBrowserDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ApiResponse.createFrom($$createType1);
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType1);
const $$createType5 = model$0.ApiResponse.createFrom($$createType4);
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.PageResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = model$0.ApiResponse.createFrom($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
