// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExtensionType 扩展点类型
 */
export enum ExtensionType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ExtensionTypeTaskHandler 任务处理器
     */
    ExtensionTypeTaskHandler = "taskHandler",

    /**
     * ExtensionTypeSiteBrowser 站点浏览器
     */
    ExtensionTypeSiteBrowser = "siteBrowser",

    /**
     * ExtensionTypeSlot 插槽
     */
    ExtensionTypeSlot = "slot",
};

/**
 * Page 分页响应（与渲染进程 IPage 保持一致）
 */
export class Page<T> {
    /**
     * 当前页码
     */
    "pageNumber": number;

    /**
     * 分页大小
     */
    "pageSize": number;

    /**
     * 总页数
     */
    "pageCount": number;

    /**
     * 数据总量
     */
    "dataCount": number;

    /**
     * 本页数据量
     */
    "currentCount": number;

    /**
     * 查询条件
     */
    "query"?: any;

    /**
     * 数据列表
     */
    "data": (T | null)[];

    /** Creates a new Page instance. */
    constructor($$source: Partial<Page<T>> = {}) {
        if (!("pageNumber" in $$source)) {
            this["pageNumber"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("pageCount" in $$source)) {
            this["pageCount"] = 0;
        }
        if (!("dataCount" in $$source)) {
            this["dataCount"] = 0;
        }
        if (!("currentCount" in $$source)) {
            this["currentCount"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class Page.
     */
    static createFrom<T = any>($$createParamT: (source: any) => T): ($$source?: any) => Page<T> {
        const $$createField6_0 = $$createType1($$createParamT);
        return ($$source: any = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("data" in $$parsedSource) {
                $$parsedSource["data"] = $$createField6_0($$parsedSource["data"]);
            }
            return new Page<T>($$parsedSource as Partial<Page<T>>);
        };
    }
}

// Private type creation functions
const $$createType0 = ($$createParamT: any) => $Create.Nullable($$createParamT);
const $$createType1 = ($$createParamT: any) => $Create.Array($$createType0($$createParamT));
