// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../database/sql/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

/**
 * Backup 备份
 */
export class Backup {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "sourceType": sql$0.NullInt64;
    "sourceId": sql$0.NullInt64;
    "fileName": sql$0.NullString;
    "filePath": sql$0.NullString;
    "workdir": sql$0.NullString;

    /** Creates a new Backup instance. */
    constructor($$source: Partial<Backup> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = (new sql$0.NullInt64());
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = (new sql$0.NullInt64());
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = (new sql$0.NullString());
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = (new sql$0.NullString());
        }
        if (!("workdir" in $$source)) {
            this["workdir"] = (new sql$0.NullString());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Backup instance from a string or object.
     */
    static createFrom($$source: any = {}): Backup {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceType" in $$parsedSource) {
            $$parsedSource["sourceType"] = $$createField3_0($$parsedSource["sourceType"]);
        }
        if ("sourceId" in $$parsedSource) {
            $$parsedSource["sourceId"] = $$createField4_0($$parsedSource["sourceId"]);
        }
        if ("fileName" in $$parsedSource) {
            $$parsedSource["fileName"] = $$createField5_0($$parsedSource["fileName"]);
        }
        if ("filePath" in $$parsedSource) {
            $$parsedSource["filePath"] = $$createField6_0($$parsedSource["filePath"]);
        }
        if ("workdir" in $$parsedSource) {
            $$parsedSource["workdir"] = $$createField7_0($$parsedSource["workdir"]);
        }
        return new Backup($$parsedSource as Partial<Backup>);
    }
}

/**
 * ContentType 插槽内容类型
 */
export enum ContentType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ContentTypeVueSource Vue 源码
     */
    ContentTypeVueSource = "vueSource",

    /**
     * ContentTypeHTML HTML 内容
     */
    ContentTypeHTML = "html",

    /**
     * ContentTypeComponent 组件
     */
    ContentTypeComponent = "component",
};

/**
 * LocalAuthor 本地作者
 */
export class LocalAuthor {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "authorName": sql$0.NullString;
    "introduce": sql$0.NullString;
    "lastUse": sql$0.NullInt64;

    /** Creates a new LocalAuthor instance. */
    constructor($$source: Partial<LocalAuthor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = (new sql$0.NullString());
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = (new sql$0.NullString());
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = (new sql$0.NullInt64());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalAuthor instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalAuthor {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("authorName" in $$parsedSource) {
            $$parsedSource["authorName"] = $$createField3_0($$parsedSource["authorName"]);
        }
        if ("introduce" in $$parsedSource) {
            $$parsedSource["introduce"] = $$createField4_0($$parsedSource["introduce"]);
        }
        if ("lastUse" in $$parsedSource) {
            $$parsedSource["lastUse"] = $$createField5_0($$parsedSource["lastUse"]);
        }
        return new LocalAuthor($$parsedSource as Partial<LocalAuthor>);
    }
}

/**
 * LocalTag 本地标签
 */
export class LocalTag {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "localTagName": sql$0.NullString;
    "baseLocalTagId": sql$0.NullInt64;
    "lastUse": sql$0.NullInt64;

    /** Creates a new LocalTag instance. */
    constructor($$source: Partial<LocalTag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("localTagName" in $$source)) {
            this["localTagName"] = (new sql$0.NullString());
        }
        if (!("baseLocalTagId" in $$source)) {
            this["baseLocalTagId"] = (new sql$0.NullInt64());
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = (new sql$0.NullInt64());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTag instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTag {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localTagName" in $$parsedSource) {
            $$parsedSource["localTagName"] = $$createField3_0($$parsedSource["localTagName"]);
        }
        if ("baseLocalTagId" in $$parsedSource) {
            $$parsedSource["baseLocalTagId"] = $$createField4_0($$parsedSource["baseLocalTagId"]);
        }
        if ("lastUse" in $$parsedSource) {
            $$parsedSource["lastUse"] = $$createField5_0($$parsedSource["lastUse"]);
        }
        return new LocalTag($$parsedSource as Partial<LocalTag>);
    }
}

/**
 * Plugin 插件
 */
export class Plugin {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "publicId": sql$0.NullString;
    "author": sql$0.NullString;
    "name": sql$0.NullString;
    "version": sql$0.NullString;
    "entryPath": sql$0.NullString;
    "rootPath": sql$0.NullString;
    "backupId": sql$0.NullInt64;
    "sortNum": sql$0.NullInt64;
    "pluginData": sql$0.NullString;
    "uninstalled": sql$0.NullInt64;
    "activationType": sql$0.NullString;

    /** Creates a new Plugin instance. */
    constructor($$source: Partial<Plugin> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("publicId" in $$source)) {
            this["publicId"] = (new sql$0.NullString());
        }
        if (!("author" in $$source)) {
            this["author"] = (new sql$0.NullString());
        }
        if (!("name" in $$source)) {
            this["name"] = (new sql$0.NullString());
        }
        if (!("version" in $$source)) {
            this["version"] = (new sql$0.NullString());
        }
        if (!("entryPath" in $$source)) {
            this["entryPath"] = (new sql$0.NullString());
        }
        if (!("rootPath" in $$source)) {
            this["rootPath"] = (new sql$0.NullString());
        }
        if (!("backupId" in $$source)) {
            this["backupId"] = (new sql$0.NullInt64());
        }
        if (!("sortNum" in $$source)) {
            this["sortNum"] = (new sql$0.NullInt64());
        }
        if (!("pluginData" in $$source)) {
            this["pluginData"] = (new sql$0.NullString());
        }
        if (!("uninstalled" in $$source)) {
            this["uninstalled"] = (new sql$0.NullInt64());
        }
        if (!("activationType" in $$source)) {
            this["activationType"] = (new sql$0.NullString());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Plugin instance from a string or object.
     */
    static createFrom($$source: any = {}): Plugin {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("publicId" in $$parsedSource) {
            $$parsedSource["publicId"] = $$createField3_0($$parsedSource["publicId"]);
        }
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField4_0($$parsedSource["author"]);
        }
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField5_0($$parsedSource["name"]);
        }
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField6_0($$parsedSource["version"]);
        }
        if ("entryPath" in $$parsedSource) {
            $$parsedSource["entryPath"] = $$createField7_0($$parsedSource["entryPath"]);
        }
        if ("rootPath" in $$parsedSource) {
            $$parsedSource["rootPath"] = $$createField8_0($$parsedSource["rootPath"]);
        }
        if ("backupId" in $$parsedSource) {
            $$parsedSource["backupId"] = $$createField9_0($$parsedSource["backupId"]);
        }
        if ("sortNum" in $$parsedSource) {
            $$parsedSource["sortNum"] = $$createField10_0($$parsedSource["sortNum"]);
        }
        if ("pluginData" in $$parsedSource) {
            $$parsedSource["pluginData"] = $$createField11_0($$parsedSource["pluginData"]);
        }
        if ("uninstalled" in $$parsedSource) {
            $$parsedSource["uninstalled"] = $$createField12_0($$parsedSource["uninstalled"]);
        }
        if ("activationType" in $$parsedSource) {
            $$parsedSource["activationType"] = $$createField13_0($$parsedSource["activationType"]);
        }
        return new Plugin($$parsedSource as Partial<Plugin>);
    }
}

/**
 * ReWorkTag 作品与标签关联
 */
export class ReWorkTag {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "workId": sql$0.NullInt64;
    "tagType": sql$0.NullInt64;
    "localTagId": sql$0.NullInt64;
    "siteTagId": sql$0.NullInt64;

    /** Creates a new ReWorkTag instance. */
    constructor($$source: Partial<ReWorkTag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("workId" in $$source)) {
            this["workId"] = (new sql$0.NullInt64());
        }
        if (!("tagType" in $$source)) {
            this["tagType"] = (new sql$0.NullInt64());
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = (new sql$0.NullInt64());
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = (new sql$0.NullInt64());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReWorkTag instance from a string or object.
     */
    static createFrom($$source: any = {}): ReWorkTag {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workId" in $$parsedSource) {
            $$parsedSource["workId"] = $$createField3_0($$parsedSource["workId"]);
        }
        if ("tagType" in $$parsedSource) {
            $$parsedSource["tagType"] = $$createField4_0($$parsedSource["tagType"]);
        }
        if ("localTagId" in $$parsedSource) {
            $$parsedSource["localTagId"] = $$createField5_0($$parsedSource["localTagId"]);
        }
        if ("siteTagId" in $$parsedSource) {
            $$parsedSource["siteTagId"] = $$createField6_0($$parsedSource["siteTagId"]);
        }
        return new ReWorkTag($$parsedSource as Partial<ReWorkTag>);
    }
}

/**
 * Resource 资源
 */
export class Resource {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "workId": number;
    "taskId": number;
    "state": number;
    "filePath": sql$0.NullString;
    "fileName": sql$0.NullString;
    "filenameExtension": sql$0.NullString;
    "suggestName": sql$0.NullString;
    "resourceSize": sql$0.NullInt64;
    "workdir": sql$0.NullString;
    "resourceComplete": number;

    /** Creates a new Resource instance. */
    constructor($$source: Partial<Resource> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("workId" in $$source)) {
            this["workId"] = 0;
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = (new sql$0.NullString());
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = (new sql$0.NullString());
        }
        if (!("filenameExtension" in $$source)) {
            this["filenameExtension"] = (new sql$0.NullString());
        }
        if (!("suggestName" in $$source)) {
            this["suggestName"] = (new sql$0.NullString());
        }
        if (!("resourceSize" in $$source)) {
            this["resourceSize"] = (new sql$0.NullInt64());
        }
        if (!("workdir" in $$source)) {
            this["workdir"] = (new sql$0.NullString());
        }
        if (!("resourceComplete" in $$source)) {
            this["resourceComplete"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Resource instance from a string or object.
     */
    static createFrom($$source: any = {}): Resource {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("filePath" in $$parsedSource) {
            $$parsedSource["filePath"] = $$createField6_0($$parsedSource["filePath"]);
        }
        if ("fileName" in $$parsedSource) {
            $$parsedSource["fileName"] = $$createField7_0($$parsedSource["fileName"]);
        }
        if ("filenameExtension" in $$parsedSource) {
            $$parsedSource["filenameExtension"] = $$createField8_0($$parsedSource["filenameExtension"]);
        }
        if ("suggestName" in $$parsedSource) {
            $$parsedSource["suggestName"] = $$createField9_0($$parsedSource["suggestName"]);
        }
        if ("resourceSize" in $$parsedSource) {
            $$parsedSource["resourceSize"] = $$createField10_0($$parsedSource["resourceSize"]);
        }
        if ("workdir" in $$parsedSource) {
            $$parsedSource["workdir"] = $$createField11_0($$parsedSource["workdir"]);
        }
        return new Resource($$parsedSource as Partial<Resource>);
    }
}

/**
 * SearchCondition 搜索条件
 */
export class SearchCondition {
    /**
     * 查询参数类型
     */
    "type": SearchType;

    /**
     * 查询参数值
     */
    "value": any;

    /**
     * 操作符 (等于、大于、小于等)
     */
    "operator"?: string;

    /** Creates a new SearchCondition instance. */
    constructor($$source: Partial<SearchCondition> = {}) {
        if (!("type" in $$source)) {
            this["type"] = SearchType.$zero;
        }
        if (!("value" in $$source)) {
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchCondition instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchCondition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchCondition($$parsedSource as Partial<SearchCondition>);
    }
}

/**
 * SearchConditionQuery 搜索条件分页查询请求
 */
export class SearchConditionQuery {
    /**
     * 类型过滤
     */
    "types"?: SearchType[];

    /**
     * 关键词
     */
    "keyword"?: string;

    /** Creates a new SearchConditionQuery instance. */
    constructor($$source: Partial<SearchConditionQuery> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchConditionQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchConditionQuery {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField0_0($$parsedSource["types"]);
        }
        return new SearchConditionQuery($$parsedSource as Partial<SearchConditionQuery>);
    }
}

/**
 * SearchType 搜索类型
 */
export enum SearchType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    SearchTypeLocalTag = 1,
    SearchTypeSiteTag = 2,
    SearchTypeLocalAuthor = 3,
    SearchTypeSiteAuthor = 4,
    SearchTypeWorksSiteName = 5,
    SearchTypeWorksNickname = 6,
    SearchTypeWorksUploadTime = 7,
    SearchTypeWorksLastView = 8,
    SearchTypeMediaType = 9,
    SearchTypeSite = 10,
    SearchTypeWorkSet = 11,
};

/**
 * SelectItem 选择项（用于前端下拉框、列表选择等）
 */
export class SelectItem {
    "value": any;
    "label": string;
    "rootId"?: string;
    "subLabels"?: string[];
    "lastUse": number;
    "extraData"?: any;

    /** Creates a new SelectItem instance. */
    constructor($$source: Partial<SelectItem> = {}) {
        if (!("value" in $$source)) {
            this["value"] = null;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectItem {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subLabels" in $$parsedSource) {
            $$parsedSource["subLabels"] = $$createField3_0($$parsedSource["subLabels"]);
        }
        return new SelectItem($$parsedSource as Partial<SelectItem>);
    }
}

/**
 * Site 站点
 */
export class Site {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "siteName": sql$0.NullString;
    "siteDescription": sql$0.NullString;
    "homepage": sql$0.NullString;

    /** Creates a new Site instance. */
    constructor($$source: Partial<Site> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("siteName" in $$source)) {
            this["siteName"] = (new sql$0.NullString());
        }
        if (!("siteDescription" in $$source)) {
            this["siteDescription"] = (new sql$0.NullString());
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = (new sql$0.NullString());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Site instance from a string or object.
     */
    static createFrom($$source: any = {}): Site {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteName" in $$parsedSource) {
            $$parsedSource["siteName"] = $$createField3_0($$parsedSource["siteName"]);
        }
        if ("siteDescription" in $$parsedSource) {
            $$parsedSource["siteDescription"] = $$createField4_0($$parsedSource["siteDescription"]);
        }
        if ("homepage" in $$parsedSource) {
            $$parsedSource["homepage"] = $$createField5_0($$parsedSource["homepage"]);
        }
        return new Site($$parsedSource as Partial<Site>);
    }
}

/**
 * SiteAuthor 站点作者
 */
export class SiteAuthor {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "siteId": sql$0.NullInt64;
    "siteAuthorId": sql$0.NullString;
    "authorName": sql$0.NullString;
    "fixedAuthorName": sql$0.NullString;
    "siteAuthorNameBefore": sql$0.NullString;
    "introduce": sql$0.NullString;
    "localAuthorId": sql$0.NullInt64;
    "lastUse": sql$0.NullInt64;

    /** Creates a new SiteAuthor instance. */
    constructor($$source: Partial<SiteAuthor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = (new sql$0.NullInt64());
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = (new sql$0.NullString());
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = (new sql$0.NullString());
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = (new sql$0.NullString());
        }
        if (!("siteAuthorNameBefore" in $$source)) {
            this["siteAuthorNameBefore"] = (new sql$0.NullString());
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = (new sql$0.NullString());
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = (new sql$0.NullInt64());
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = (new sql$0.NullInt64());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthor instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthor {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField3_0($$parsedSource["siteId"]);
        }
        if ("siteAuthorId" in $$parsedSource) {
            $$parsedSource["siteAuthorId"] = $$createField4_0($$parsedSource["siteAuthorId"]);
        }
        if ("authorName" in $$parsedSource) {
            $$parsedSource["authorName"] = $$createField5_0($$parsedSource["authorName"]);
        }
        if ("fixedAuthorName" in $$parsedSource) {
            $$parsedSource["fixedAuthorName"] = $$createField6_0($$parsedSource["fixedAuthorName"]);
        }
        if ("siteAuthorNameBefore" in $$parsedSource) {
            $$parsedSource["siteAuthorNameBefore"] = $$createField7_0($$parsedSource["siteAuthorNameBefore"]);
        }
        if ("introduce" in $$parsedSource) {
            $$parsedSource["introduce"] = $$createField8_0($$parsedSource["introduce"]);
        }
        if ("localAuthorId" in $$parsedSource) {
            $$parsedSource["localAuthorId"] = $$createField9_0($$parsedSource["localAuthorId"]);
        }
        if ("lastUse" in $$parsedSource) {
            $$parsedSource["lastUse"] = $$createField10_0($$parsedSource["lastUse"]);
        }
        return new SiteAuthor($$parsedSource as Partial<SiteAuthor>);
    }
}

/**
 * SiteTag 站点标签
 */
export class SiteTag {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "siteId": sql$0.NullInt64;
    "siteTagId": sql$0.NullString;
    "siteTagName": sql$0.NullString;
    "baseSiteTagId": sql$0.NullString;
    "description": sql$0.NullString;
    "localTagId": sql$0.NullInt64;
    "lastUse": sql$0.NullInt64;

    /** Creates a new SiteTag instance. */
    constructor($$source: Partial<SiteTag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = (new sql$0.NullInt64());
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = (new sql$0.NullString());
        }
        if (!("siteTagName" in $$source)) {
            this["siteTagName"] = (new sql$0.NullString());
        }
        if (!("baseSiteTagId" in $$source)) {
            this["baseSiteTagId"] = (new sql$0.NullString());
        }
        if (!("description" in $$source)) {
            this["description"] = (new sql$0.NullString());
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = (new sql$0.NullInt64());
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = (new sql$0.NullInt64());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTag instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTag {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField3_0($$parsedSource["siteId"]);
        }
        if ("siteTagId" in $$parsedSource) {
            $$parsedSource["siteTagId"] = $$createField4_0($$parsedSource["siteTagId"]);
        }
        if ("siteTagName" in $$parsedSource) {
            $$parsedSource["siteTagName"] = $$createField5_0($$parsedSource["siteTagName"]);
        }
        if ("baseSiteTagId" in $$parsedSource) {
            $$parsedSource["baseSiteTagId"] = $$createField6_0($$parsedSource["baseSiteTagId"]);
        }
        if ("description" in $$parsedSource) {
            $$parsedSource["description"] = $$createField7_0($$parsedSource["description"]);
        }
        if ("localTagId" in $$parsedSource) {
            $$parsedSource["localTagId"] = $$createField8_0($$parsedSource["localTagId"]);
        }
        if ("lastUse" in $$parsedSource) {
            $$parsedSource["lastUse"] = $$createField9_0($$parsedSource["lastUse"]);
        }
        return new SiteTag($$parsedSource as Partial<SiteTag>);
    }
}

/**
 * SlotConfig 插槽配置
 */
export class SlotConfig {
    /**
     * 扩展点类型
     */
    "Type": model$0.ExtensionType;

    /**
     * 扩展点ID
     */
    "ID": string;

    /**
     * 插件数据库ID
     */
    "PluginID": number;

    /**
     * 插件公开ID
     */
    "PluginPublicID": string;

    /**
     * 扩展点名称
     */
    "Name": string;

    /**
     * 扩展点描述
     */
    "Description": string;

    /**
     * 插槽类型
     */
    "SlotType": SlotType;

    /**
     * 插槽内容
     */
    "Content": string;

    /**
     * 内容类型
     */
    "ContentType": ContentType;

    /**
     * 插槽标题
     */
    "Title": string;

    /**
     * 插槽图标
     */
    "Icon": string;

    /**
     * 排序
     */
    "Order": number;

    /** Creates a new SlotConfig instance. */
    constructor($$source: Partial<SlotConfig> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = model$0.ExtensionType.$zero;
        }
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("PluginID" in $$source)) {
            this["PluginID"] = 0;
        }
        if (!("PluginPublicID" in $$source)) {
            this["PluginPublicID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("SlotType" in $$source)) {
            this["SlotType"] = SlotType.$zero;
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("ContentType" in $$source)) {
            this["ContentType"] = ContentType.$zero;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Icon" in $$source)) {
            this["Icon"] = "";
        }
        if (!("Order" in $$source)) {
            this["Order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlotConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SlotConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlotConfig($$parsedSource as Partial<SlotConfig>);
    }
}

/**
 * SlotType 插槽类型
 */
export enum SlotType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SlotTypeEmbed 嵌入插槽
     */
    SlotTypeEmbed = "embed",

    /**
     * SlotTypePanel 面板插槽
     */
    SlotTypePanel = "panel",

    /**
     * SlotTypeView 视图插槽
     */
    SlotTypeView = "view",

    /**
     * SlotTypeMenu 菜单插槽
     */
    SlotTypeMenu = "menu",

    /**
     * SlotTypeSiteBrowserList 站点浏览器列表插槽
     */
    SlotTypeSiteBrowserList = "siteBrowserList",
};

/**
 * Task 任务
 */
export class Task {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "isCollection": sql$0.NullInt64;
    "pid": sql$0.NullInt64;
    "taskName": sql$0.NullString;
    "siteId": sql$0.NullInt64;
    "siteWorkId": sql$0.NullString;
    "url": sql$0.NullString;
    "status": number;
    "pendingResourceId": sql$0.NullInt64;
    "continuable": sql$0.NullInt64;
    "pluginPublicId": sql$0.NullString;
    "pluginContributionId": sql$0.NullString;
    "pluginData": sql$0.NullString;
    "errorMessage": sql$0.NullString;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("isCollection" in $$source)) {
            this["isCollection"] = (new sql$0.NullInt64());
        }
        if (!("pid" in $$source)) {
            this["pid"] = (new sql$0.NullInt64());
        }
        if (!("taskName" in $$source)) {
            this["taskName"] = (new sql$0.NullString());
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = (new sql$0.NullInt64());
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = (new sql$0.NullString());
        }
        if (!("url" in $$source)) {
            this["url"] = (new sql$0.NullString());
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("pendingResourceId" in $$source)) {
            this["pendingResourceId"] = (new sql$0.NullInt64());
        }
        if (!("continuable" in $$source)) {
            this["continuable"] = (new sql$0.NullInt64());
        }
        if (!("pluginPublicId" in $$source)) {
            this["pluginPublicId"] = (new sql$0.NullString());
        }
        if (!("pluginContributionId" in $$source)) {
            this["pluginContributionId"] = (new sql$0.NullString());
        }
        if (!("pluginData" in $$source)) {
            this["pluginData"] = (new sql$0.NullString());
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = (new sql$0.NullString());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType1;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType1;
        const $$createField14_0 = $$createType1;
        const $$createField15_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("isCollection" in $$parsedSource) {
            $$parsedSource["isCollection"] = $$createField3_0($$parsedSource["isCollection"]);
        }
        if ("pid" in $$parsedSource) {
            $$parsedSource["pid"] = $$createField4_0($$parsedSource["pid"]);
        }
        if ("taskName" in $$parsedSource) {
            $$parsedSource["taskName"] = $$createField5_0($$parsedSource["taskName"]);
        }
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField6_0($$parsedSource["siteId"]);
        }
        if ("siteWorkId" in $$parsedSource) {
            $$parsedSource["siteWorkId"] = $$createField7_0($$parsedSource["siteWorkId"]);
        }
        if ("url" in $$parsedSource) {
            $$parsedSource["url"] = $$createField8_0($$parsedSource["url"]);
        }
        if ("pendingResourceId" in $$parsedSource) {
            $$parsedSource["pendingResourceId"] = $$createField10_0($$parsedSource["pendingResourceId"]);
        }
        if ("continuable" in $$parsedSource) {
            $$parsedSource["continuable"] = $$createField11_0($$parsedSource["continuable"]);
        }
        if ("pluginPublicId" in $$parsedSource) {
            $$parsedSource["pluginPublicId"] = $$createField12_0($$parsedSource["pluginPublicId"]);
        }
        if ("pluginContributionId" in $$parsedSource) {
            $$parsedSource["pluginContributionId"] = $$createField13_0($$parsedSource["pluginContributionId"]);
        }
        if ("pluginData" in $$parsedSource) {
            $$parsedSource["pluginData"] = $$createField14_0($$parsedSource["pluginData"]);
        }
        if ("errorMessage" in $$parsedSource) {
            $$parsedSource["errorMessage"] = $$createField15_0($$parsedSource["errorMessage"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

/**
 * Work 作品
 */
export class Work {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "siteId": sql$0.NullInt64;
    "siteWorkId": sql$0.NullString;
    "siteWorkName": sql$0.NullString;
    "siteAuthorId": sql$0.NullString;
    "siteWorkDescription": sql$0.NullString;
    "siteUploadTime": sql$0.NullInt64;
    "siteUpdateTime": sql$0.NullInt64;
    "nickName": sql$0.NullString;
    "localAuthorId": sql$0.NullInt64;
    "lastView": sql$0.NullInt64;

    /** Creates a new Work instance. */
    constructor($$source: Partial<Work> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = (new sql$0.NullInt64());
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = (new sql$0.NullString());
        }
        if (!("siteWorkName" in $$source)) {
            this["siteWorkName"] = (new sql$0.NullString());
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = (new sql$0.NullString());
        }
        if (!("siteWorkDescription" in $$source)) {
            this["siteWorkDescription"] = (new sql$0.NullString());
        }
        if (!("siteUploadTime" in $$source)) {
            this["siteUploadTime"] = (new sql$0.NullInt64());
        }
        if (!("siteUpdateTime" in $$source)) {
            this["siteUpdateTime"] = (new sql$0.NullInt64());
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = (new sql$0.NullString());
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = (new sql$0.NullInt64());
        }
        if (!("lastView" in $$source)) {
            this["lastView"] = (new sql$0.NullInt64());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Work instance from a string or object.
     */
    static createFrom($$source: any = {}): Work {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField3_0($$parsedSource["siteId"]);
        }
        if ("siteWorkId" in $$parsedSource) {
            $$parsedSource["siteWorkId"] = $$createField4_0($$parsedSource["siteWorkId"]);
        }
        if ("siteWorkName" in $$parsedSource) {
            $$parsedSource["siteWorkName"] = $$createField5_0($$parsedSource["siteWorkName"]);
        }
        if ("siteAuthorId" in $$parsedSource) {
            $$parsedSource["siteAuthorId"] = $$createField6_0($$parsedSource["siteAuthorId"]);
        }
        if ("siteWorkDescription" in $$parsedSource) {
            $$parsedSource["siteWorkDescription"] = $$createField7_0($$parsedSource["siteWorkDescription"]);
        }
        if ("siteUploadTime" in $$parsedSource) {
            $$parsedSource["siteUploadTime"] = $$createField8_0($$parsedSource["siteUploadTime"]);
        }
        if ("siteUpdateTime" in $$parsedSource) {
            $$parsedSource["siteUpdateTime"] = $$createField9_0($$parsedSource["siteUpdateTime"]);
        }
        if ("nickName" in $$parsedSource) {
            $$parsedSource["nickName"] = $$createField10_0($$parsedSource["nickName"]);
        }
        if ("localAuthorId" in $$parsedSource) {
            $$parsedSource["localAuthorId"] = $$createField11_0($$parsedSource["localAuthorId"]);
        }
        if ("lastView" in $$parsedSource) {
            $$parsedSource["lastView"] = $$createField12_0($$parsedSource["lastView"]);
        }
        return new Work($$parsedSource as Partial<Work>);
    }
}

/**
 * WorkFullDTO 作品完整信息DTO
 */
export class WorkFullDTO {
    /**
     * 基础字段
     */
    "id": number;
    "createTime": number;
    "updateTime": number;
    "siteId": number;
    "siteWorkId": string;
    "siteWorkName": string;
    "siteAuthorId": string;
    "siteWorkDescription": string;
    "siteUploadTime": number;
    "siteUpdateTime": number;
    "nickName": string;
    "localAuthorId": number;
    "lastView": number;

    /**
     * 关联的本地作者信息
     */
    "localAuthor"?: model$0.RankedLocalAuthor | null;

    /**
     * 关联的站点作者信息
     */
    "siteAuthor"?: model$0.RankedSiteAuthor | null;

    /**
     * 关联的站点信息
     */
    "site"?: SelectItem | null;

    /**
     * 关联的本地标签列表
     */
    "localTags"?: (SelectItem | null)[];

    /**
     * 关联的站点标签列表
     */
    "siteTags"?: (SelectItem | null)[];

    /**
     * 关联的资源列表
     */
    "resources"?: (Resource | null)[];

    /** Creates a new WorkFullDTO instance. */
    constructor($$source: Partial<WorkFullDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = 0;
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = "";
        }
        if (!("siteWorkName" in $$source)) {
            this["siteWorkName"] = "";
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = "";
        }
        if (!("siteWorkDescription" in $$source)) {
            this["siteWorkDescription"] = "";
        }
        if (!("siteUploadTime" in $$source)) {
            this["siteUploadTime"] = 0;
        }
        if (!("siteUpdateTime" in $$source)) {
            this["siteUpdateTime"] = 0;
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = "";
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = 0;
        }
        if (!("lastView" in $$source)) {
            this["lastView"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkFullDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkFullDTO {
        const $$createField13_0 = $$createType5;
        const $$createField14_0 = $$createType7;
        const $$createField15_0 = $$createType9;
        const $$createField16_0 = $$createType10;
        const $$createField17_0 = $$createType10;
        const $$createField18_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localAuthor" in $$parsedSource) {
            $$parsedSource["localAuthor"] = $$createField13_0($$parsedSource["localAuthor"]);
        }
        if ("siteAuthor" in $$parsedSource) {
            $$parsedSource["siteAuthor"] = $$createField14_0($$parsedSource["siteAuthor"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField15_0($$parsedSource["site"]);
        }
        if ("localTags" in $$parsedSource) {
            $$parsedSource["localTags"] = $$createField16_0($$parsedSource["localTags"]);
        }
        if ("siteTags" in $$parsedSource) {
            $$parsedSource["siteTags"] = $$createField17_0($$parsedSource["siteTags"]);
        }
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField18_0($$parsedSource["resources"]);
        }
        return new WorkFullDTO($$parsedSource as Partial<WorkFullDTO>);
    }
}

/**
 * WorkSet 作品集
 */
export class WorkSet {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "siteId": sql$0.NullInt64;
    "siteWorkSetId": sql$0.NullString;
    "siteWorkSetName": sql$0.NullString;
    "siteAuthorId": sql$0.NullString;
    "siteWorkSetDescription": sql$0.NullString;
    "siteUploadTime": sql$0.NullInt64;
    "siteUpdateTime": sql$0.NullInt64;
    "nickName": sql$0.NullString;
    "lastView": sql$0.NullInt64;

    /** Creates a new WorkSet instance. */
    constructor($$source: Partial<WorkSet> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = (new sql$0.NullInt64());
        }
        if (!("siteWorkSetId" in $$source)) {
            this["siteWorkSetId"] = (new sql$0.NullString());
        }
        if (!("siteWorkSetName" in $$source)) {
            this["siteWorkSetName"] = (new sql$0.NullString());
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = (new sql$0.NullString());
        }
        if (!("siteWorkSetDescription" in $$source)) {
            this["siteWorkSetDescription"] = (new sql$0.NullString());
        }
        if (!("siteUploadTime" in $$source)) {
            this["siteUploadTime"] = (new sql$0.NullInt64());
        }
        if (!("siteUpdateTime" in $$source)) {
            this["siteUpdateTime"] = (new sql$0.NullInt64());
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = (new sql$0.NullString());
        }
        if (!("lastView" in $$source)) {
            this["lastView"] = (new sql$0.NullInt64());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSet instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSet {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField3_0($$parsedSource["siteId"]);
        }
        if ("siteWorkSetId" in $$parsedSource) {
            $$parsedSource["siteWorkSetId"] = $$createField4_0($$parsedSource["siteWorkSetId"]);
        }
        if ("siteWorkSetName" in $$parsedSource) {
            $$parsedSource["siteWorkSetName"] = $$createField5_0($$parsedSource["siteWorkSetName"]);
        }
        if ("siteAuthorId" in $$parsedSource) {
            $$parsedSource["siteAuthorId"] = $$createField6_0($$parsedSource["siteAuthorId"]);
        }
        if ("siteWorkSetDescription" in $$parsedSource) {
            $$parsedSource["siteWorkSetDescription"] = $$createField7_0($$parsedSource["siteWorkSetDescription"]);
        }
        if ("siteUploadTime" in $$parsedSource) {
            $$parsedSource["siteUploadTime"] = $$createField8_0($$parsedSource["siteUploadTime"]);
        }
        if ("siteUpdateTime" in $$parsedSource) {
            $$parsedSource["siteUpdateTime"] = $$createField9_0($$parsedSource["siteUpdateTime"]);
        }
        if ("nickName" in $$parsedSource) {
            $$parsedSource["nickName"] = $$createField10_0($$parsedSource["nickName"]);
        }
        if ("lastView" in $$parsedSource) {
            $$parsedSource["lastView"] = $$createField11_0($$parsedSource["lastView"]);
        }
        return new WorkSet($$parsedSource as Partial<WorkSet>);
    }
}

// Private type creation functions
const $$createType0 = sql$0.NullInt64.createFrom;
const $$createType1 = sql$0.NullString.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = model$0.RankedLocalAuthor.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.RankedSiteAuthor.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = SelectItem.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Resource.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
