// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ImportResult 导入结果摘要。
 */
export class ImportResult {
    /**
     * 新建作品数
     */
    "createdWorks": number;

    /**
     * 替换作品数（确认替换 + 自动增补 全集）
     */
    "replacedWorks": number;

    /**
     * 经用户确认替换的作品数
     */
    "replacedConfirmed": number;

    /**
     * 零交集命中自动增补的作品数
     */
    "replacedAuto": number;

    /**
     * 查重命中（site_id+site_work_id 已存在）跳过的作品数
     */
    "skippedWorks": number;

    /**
     * 新建作品集数
     */
    "createdWorkSets": number;

    /**
     * 查重命中跳过的作品集数
     */
    "skippedWorkSets": number;

    /**
     * 新建站点数（按键 find-or-create）
     */
    "createdSites": number;

    /**
     * 新建本地标签数（按名称 find-or-create）
     */
    "createdLocalTags": number;

    /**
     * 新建站点标签数（按站点+site_tag_id 匹配）
     */
    "createdSiteTags": number;

    /**
     * 新建本地作者数（按名称 find-or-create）
     */
    "createdLocalAuthors": number;

    /**
     * 新建站点作者数（按站点+site_author_id 匹配）
     */
    "createdSiteAuthors": number;

    /**
     * 落盘文件数
     */
    "extractedFiles": number;

    /**
     * 挂载缺席数（源文件缺失/无包内路径，决策4）
     */
    "absentStores": number;

    /** Creates a new ImportResult instance. */
    constructor($$source: Partial<ImportResult> = {}) {
        if (!("createdWorks" in $$source)) {
            this["createdWorks"] = 0;
        }
        if (!("replacedWorks" in $$source)) {
            this["replacedWorks"] = 0;
        }
        if (!("replacedConfirmed" in $$source)) {
            this["replacedConfirmed"] = 0;
        }
        if (!("replacedAuto" in $$source)) {
            this["replacedAuto"] = 0;
        }
        if (!("skippedWorks" in $$source)) {
            this["skippedWorks"] = 0;
        }
        if (!("createdWorkSets" in $$source)) {
            this["createdWorkSets"] = 0;
        }
        if (!("skippedWorkSets" in $$source)) {
            this["skippedWorkSets"] = 0;
        }
        if (!("createdSites" in $$source)) {
            this["createdSites"] = 0;
        }
        if (!("createdLocalTags" in $$source)) {
            this["createdLocalTags"] = 0;
        }
        if (!("createdSiteTags" in $$source)) {
            this["createdSiteTags"] = 0;
        }
        if (!("createdLocalAuthors" in $$source)) {
            this["createdLocalAuthors"] = 0;
        }
        if (!("createdSiteAuthors" in $$source)) {
            this["createdSiteAuthors"] = 0;
        }
        if (!("extractedFiles" in $$source)) {
            this["extractedFiles"] = 0;
        }
        if (!("absentStores" in $$source)) {
            this["absentStores"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult($$parsedSource as Partial<ImportResult>);
    }
}
