// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 作品-作者关联 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../../lvfeng-z/library-squirrel-plugin-sdk/dto/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListByWorkId 获取单个作品的作者关联信息
 * @Summary 获取单个作品的作者关联信息
 * @Param workId path int true "作品ID"
 * @Success 200 {object} model.ApiResponse[*sdkdto.WorkAuthorDTO]
 */
export function ListByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<$models.WorkAuthorDTO | null> | null> {
    return $Call.ByID(3131814203, workId).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListByWorkIds 批量获取多个作品的作者关联信息
 * @Summary 批量获取多个作品的作者关联信息
 * @Param workIds body []int64 true "作品ID列表"
 * @Success 200 {object} model.ApiResponse[[]*WorkAuthorsResultDTO]
 */
export function ListByWorkIds(workIds: number[]): $CancellablePromise<model$0.ApiResponse<($models.WorkAuthorsResultDTO | null)[]> | null> {
    return $Call.ByID(608703576, workIds).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListLocalAuthorsByWorkId 查询作品关联的本地作者
 * @Summary 查询作品关联的本地作者
 * @Param workId path int true "作品ID"
 * @Success 200 {object} model.ApiResponse[[]*model.RankedLocalAuthor]
 */
export function ListLocalAuthorsByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<(dto$0.RankedLocalAuthor | null)[]> | null> {
    return $Call.ByID(1091765870, workId).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * ListRankedLocalAuthorWithWorkIdByWorkIds 查询多个作品的本地作者列表（带作品ID）
 * @Summary 查询多个作品的本地作者列表（带作品ID）
 * @Param workIds body []int64 true "作品ID列表"
 * @Success 200 {object} model.ApiResponse[[]*model.RankedLocalAuthorWithWorkId]
 */
export function ListRankedLocalAuthorWithWorkIdByWorkIds(workIds: number[]): $CancellablePromise<model$0.ApiResponse<(dto$0.RankedLocalAuthorWithWorkId | null)[]> | null> {
    return $Call.ByID(746410167, workIds).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * ListRankedSiteAuthorWithWorkIdByWorkIds 查询多个作品的站点作者列表（带作品ID）
 * @Summary 查询多个作品的站点作者列表（带作品ID）
 * @Param workIds body []int64 true "作品ID列表"
 * @Success 200 {object} model.ApiResponse[[]*model.RankedSiteAuthorWithWorkId]
 */
export function ListRankedSiteAuthorWithWorkIdByWorkIds(workIds: number[]): $CancellablePromise<model$0.ApiResponse<(dto$0.RankedSiteAuthorWithWorkId | null)[]> | null> {
    return $Call.ByID(2386936165, workIds).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * ListSiteAuthorsByWorkId 查询作品关联的站点作者
 * @Summary 查询作品关联的站点作者
 * @Param workId path int true "作品ID"
 * @Success 200 {object} model.ApiResponse[[]*model.RankedSiteAuthor]
 */
export function ListSiteAuthorsByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<(dto$0.RankedSiteAuthor | null)[]> | null> {
    return $Call.ByID(2120143110, workId).then(($result: any) => {
        return $$createType28($result);
    });
}

// Private type creation functions
const $$createType0 = $models.WorkAuthorDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ApiResponse.createFrom($$createType1);
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.WorkAuthorsResultDTO.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = model$0.ApiResponse.createFrom($$createType6);
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = dto$0.RankedLocalAuthor.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = model$0.ApiResponse.createFrom($$createType11);
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = dto$0.RankedLocalAuthorWithWorkId.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = model$0.ApiResponse.createFrom($$createType16);
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = dto$0.RankedSiteAuthorWithWorkId.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = model$0.ApiResponse.createFrom($$createType21);
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = dto$0.RankedSiteAuthor.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = model$0.ApiResponse.createFrom($$createType26);
const $$createType28 = $Create.Nullable($$createType27);
