// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 任务管理器 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";

/**
 * GetTaskState 获取任务状态
 */
export function GetTaskState(taskId: number): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(254567904, taskId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetTaskTreeState 获取任务树状态
 */
export function GetTaskTreeState(taskId: number): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(3070069892, taskId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * IsIdle 检查任务管理器是否处于空闲状态
 */
export function IsIdle(): $CancellablePromise<model$0.ApiResponse<boolean> | null> {
    return $Call.ByID(2837421788).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * PauseTaskTree 暂停任务树
 */
export function PauseTaskTree(taskId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3300265013, taskId).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ResumeTaskTree 恢复任务树
 */
export function ResumeTaskTree(taskId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1122220040, taskId).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * RetryTaskTree 重试任务树
 */
export function RetryTaskTree(taskId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3536642449, taskId).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * StartTaskTree 启动任务树
 */
export function StartTaskTree(taskId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2158111927, taskId).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * StopTaskTree 停止任务树
 */
export function StopTaskTree(taskId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(30666831, taskId).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType5 = $Create.Nullable($$createType4);
