// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SiteQueryDTO 站点查询条件
 */
export class SiteQueryDTO {
    /**
     * 站点名称（精确匹配）
     */
    "siteName": string | null;

    /**
     * 主页地址（精确匹配）
     */
    "homepage": string | null;

    /**
     * 站点名称（模糊匹配）
     */
    "siteNameLike": string | null;

    /**
     * 排序字段：create_time, update_time, site_name
     * 排序字段
     */
    "orderBy": string;

    /**
     * 是否降序
     */
    "orderDesc": boolean;

    /** Creates a new SiteQueryDTO instance. */
    constructor($$source: Partial<SiteQueryDTO> = {}) {
        if (!("siteName" in $$source)) {
            this["siteName"] = null;
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = null;
        }
        if (!("siteNameLike" in $$source)) {
            this["siteNameLike"] = null;
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = "";
        }
        if (!("orderDesc" in $$source)) {
            this["orderDesc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteQueryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteQueryDTO($$parsedSource as Partial<SiteQueryDTO>);
    }
}
