// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SiteDTO 站点数据传输对象
 */
export class SiteDTO {
    "id": number;
    "siteName": string | null;
    "siteDescription": string | null;
    "homepage": string | null;

    /** Creates a new SiteDTO instance. */
    constructor($$source: Partial<SiteDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteName" in $$source)) {
            this["siteName"] = null;
        }
        if (!("siteDescription" in $$source)) {
            this["siteDescription"] = null;
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteDTO($$parsedSource as Partial<SiteDTO>);
    }
}

/**
 * SiteQueryDTO 站点查询条件
 */
export class SiteQueryDTO {
    /**
     * 站点名称（精确匹配）
     */
    "siteName": string | null;

    /**
     * 主页地址（精确匹配）
     */
    "homepage": string | null;

    /**
     * 站点名称（模糊匹配）
     */
    "siteNameLike": string | null;

    /**
     * 排序字段：create_time, update_time, site_name
     * 排序字段
     */
    "orderBy": string;

    /**
     * 是否降序
     */
    "orderDesc": boolean;

    /** Creates a new SiteQueryDTO instance. */
    constructor($$source: Partial<SiteQueryDTO> = {}) {
        if (!("siteName" in $$source)) {
            this["siteName"] = null;
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = null;
        }
        if (!("siteNameLike" in $$source)) {
            this["siteNameLike"] = null;
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = "";
        }
        if (!("orderDesc" in $$source)) {
            this["orderDesc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteQueryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteQueryDTO($$parsedSource as Partial<SiteQueryDTO>);
    }
}

/**
 * SiteResultDTO 站点返回结果DTO（用于屏蔽sql.Null*类型）
 */
export class SiteResultDTO {
    "id": number;
    "siteName": string | null;
    "siteDescription": string | null;
    "homepage": string | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new SiteResultDTO instance. */
    constructor($$source: Partial<SiteResultDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteName" in $$source)) {
            this["siteName"] = null;
        }
        if (!("siteDescription" in $$source)) {
            this["siteDescription"] = null;
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteResultDTO($$parsedSource as Partial<SiteResultDTO>);
    }
}
