// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// Compatibility shim - re-exports handlers under old App namespace
// This file exists for migration convenience - new code should import handlers directly

import * as LocalTagHandler from './wails/internal/localTag/index.js'
import * as LocalAuthorHandler from './wails/internal/localAuthor/index.js'
import * as SiteTagHandler from './wails/internal/siteTag/index.js'
import * as SiteAuthorHandler from './wails/internal/siteAuthor/index.js'
import * as SiteHandler from './wails/internal/site/index.js'
import * as ResourceHandler from './wails/internal/resource/index.js'
import * as WorkHandler from './wails/internal/work/index.js'
import * as WorkSetHandler from './wails/internal/workSet/index.js'
import * as SearchHandler from './wails/internal/search/index.js'
import * as SettingsHandler from './wails/internal/settings/index.js'
import * as SecureStorageHandler from './wails/internal/secureStorage/index.js'
import * as BackupHandler from './wails/internal/backup/index.js'
import * as AppLauncherHandler from './wails/internal/appLauncher/index.js'
import * as FileSysUtilHandler from './wails/internal/fileSysUtil/index.js'
import * as PluginHandler from './wails/internal/plugin/index.js'
import * as TaskHandler from './wails/internal/task/index.js'
import * as TaskManagerHandler from './wails/internal/taskManager/index.js'
import * as SlotHandler from './wails/internal/slot/index.js'
import * as SiteBrowserHandler from './wails/internal/siteBrowser/index.js'
import * as ReWorkTagHandler from './wails/internal/reWorkTag/index.js'

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const App = {
  // LocalTag
  LocalTagSave: (tag: any) => LocalTagHandler.Handler.Save(tag),
  LocalTagDeleteById: (id: number) => LocalTagHandler.Handler.Delete(id),
  LocalTagUpdateById: (tag: any) => LocalTagHandler.Handler.Update(tag),
  LocalTagGetById: (id: number) => LocalTagHandler.Handler.GetById(id),
  LocalTagQueryPage: (query: any) => LocalTagHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  LocalTagQueryDTOPage: (query: any) => LocalTagHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  LocalTagGetTree: (rootId: number, depth: number) => LocalTagHandler.Handler.GetTree(rootId, depth),
  LocalTagListSelectItems: (query: any) => LocalTagHandler.Handler.ListSelectItems(query),
  LocalTagQuerySelectItemPage: (query: any) => LocalTagHandler.Handler.QuerySelectItemPage(query.page, query.pageSize, query.query),
  LocalTagListByWorkId: (workId: number) => LocalTagHandler.Handler.ListByWorkId(workId),
  LocalTagQuerySelectItemPageByWorkId: (query: any, workId: number) => LocalTagHandler.Handler.QuerySelectItemPageByWorkId(query, workId),

  // LocalAuthor
  LocalAuthorSave: (author: any) => LocalAuthorHandler.Handler.Save(author),
  LocalAuthorDeleteById: (id: number) => LocalAuthorHandler.Handler.Delete(id),
  LocalAuthorUpdateById: (author: any) => LocalAuthorHandler.Handler.Update(author),
  LocalAuthorGetById: (id: number) => LocalAuthorHandler.Handler.GetById(id),
  LocalAuthorQueryPage: (query: any) => LocalAuthorHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  LocalAuthorQuerySelectItemPage: (query: any) => LocalAuthorHandler.Handler.QuerySelectItemPage(query.page, query.pageSize, query.query),
  LocalAuthorListByWorkId: (workId: number) => LocalAuthorHandler.Handler.ListByWorkId(workId),
  LocalAuthorUpdateLastUse: (ids: number[]) => LocalAuthorHandler.Handler.UpdateLastUse(ids),

  // SiteTag
  SiteTagSave: (tag: any) => SiteTagHandler.Handler.Save(tag),
  SiteTagDeleteById: (id: number) => SiteTagHandler.Handler.Delete(id),
  SiteTagUpdateById: (tag: any) => SiteTagHandler.Handler.Update(tag),
  SiteTagGetById: (id: number) => SiteTagHandler.Handler.GetById(id),
  SiteTagQueryPage: (query: any) => SiteTagHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  SiteTagListByWorkId: (workId: number) => SiteTagHandler.Handler.ListByWorkId(workId),

  // SiteAuthor
  SiteAuthorSave: (author: any) => SiteAuthorHandler.Handler.Save(author),
  SiteAuthorDeleteById: (id: number) => SiteAuthorHandler.Handler.Delete(id),
  SiteAuthorUpdateById: (author: any) => SiteAuthorHandler.Handler.Update(author),
  SiteAuthorGetById: (id: number) => SiteAuthorHandler.Handler.GetById(id),
  SiteAuthorQueryPage: (query: any) => SiteAuthorHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  SiteAuthorListByWorkId: (workId: number) => SiteAuthorHandler.Handler.ListByWorkId(workId),

  // Site
  SiteSave: (site: any) => SiteHandler.Handler.Save(site),
  SiteDelete: (id: number) => SiteHandler.Handler.Delete(id),
  SiteUpdate: (site: any) => SiteHandler.Handler.Update(site),
  SiteGetById: (id: number) => SiteHandler.Handler.GetById(id),
  SiteQueryPage: (query: any) => SiteHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  SiteQuerySelectItemPage: (query: any) => SiteHandler.Handler.QuerySelectItemPage(query.page, query.pageSize, query.query),
  SiteGetByName: (name: string) => SiteHandler.Handler.GetByName(name),

  // Resource
  ResourceSave: (resource: any) => ResourceHandler.Handler.Save(resource),
  ResourceDelete: (id: number) => ResourceHandler.Handler.Delete(id),
  ResourceUpdate: (resource: any) => ResourceHandler.Handler.Update(resource),
  ResourceGetById: (id: number) => ResourceHandler.Handler.GetById(id),
  ResourceQueryPage: (query: any) => ResourceHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  ResourceQueryByWorkId: (workId: number) => ResourceHandler.Handler.QueryByWorkId(workId),

  // Work
  WorkSave: (work: any) => WorkHandler.Handler.Save(work),
  WorkDelete: (id: number) => WorkHandler.Handler.Delete(id),
  WorkUpdate: (work: any) => WorkHandler.Handler.Update(work),
  WorkDeleteWorkAndSurroundingData: (id: number) => WorkHandler.Handler.DeleteWorkAndSurroundingData(id),
  WorkGetById: (id: number) => WorkHandler.Handler.GetById(id),
  WorkQueryPage: (query: any) => WorkHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  WorkGetFullWorkInfoById: (id: number) => WorkHandler.Handler.GetFullWorkInfoById(id),

  // WorkSet
  WorkSetSave: (workSet: any) => WorkSetHandler.Handler.Save(workSet),
  WorkSetDelete: (id: number) => WorkSetHandler.Handler.Delete(id),
  WorkSetUpdate: (workSet: any) => WorkSetHandler.Handler.Update(workSet),
  WorkSetGetById: (id: number) => WorkSetHandler.Handler.GetById(id),
  WorkSetQueryPage: (query: any) => WorkSetHandler.Handler.QueryPage(query.page, query.pageSize, query.query),

  // Search
  SearchFullText: (keyword: string, searchType: number, searchCondition: any) => SearchHandler.Handler.FullTextSearch(keyword, searchType, searchCondition),
  SearchAggregation: (query: any) => SearchHandler.Handler.Aggregation(query),

  // Settings
  SettingsGetSettings: () => SettingsHandler.Handler.GetSettings(),
  SettingsSaveSettings: (settings: any) => SettingsHandler.Handler.SaveSettings(settings),

  // SecureStorage
  SecureStorageSet: (key: string, value: string) => SecureStorageHandler.Handler.Set(key, value),
  SecureStorageGet: (key: string) => SecureStorageHandler.Handler.Get(key),
  SecureStorageDelete: (key: string) => SecureStorageHandler.Handler.Delete(key),
  SecureStorageKeys: () => SecureStorageHandler.Handler.Keys(),

  // Backup
  BackupCreate: (sourceType: number, sourceId: number, fileName: string, sourcePath: string, workDir: string) =>
    BackupHandler.Handler.Create(sourceType, sourceId, fileName, sourcePath, workDir),
  BackupGetById: (id: number) => BackupHandler.Handler.GetById(id),

  // AppLauncher
  AppLauncherOpen: (app: any, filePath: string) => AppLauncherHandler.Handler.Open(app, filePath),
  AppLauncherOpenPath: (filePath: string) => AppLauncherHandler.Handler.OpenPath(filePath),
  AppLauncherOpenExternal: (url: string) => AppLauncherHandler.Handler.OpenExternal(url),

  // FileSysUtil
  DirSelect: (openFile: boolean) => FileSysUtilHandler.Handler.DirSelect(openFile, false),
  DirSelectMultiple: (openFile: boolean) => FileSysUtilHandler.Handler.DirSelectMultiple(openFile, false),

  // Plugin
  PluginGetById: (id: number) => PluginHandler.Handler.GetById(id),
  PluginGetByPublicId: (publicId: string) => PluginHandler.Handler.GetByPublicId(publicId),
  PluginPage: (page: number, pageSize: number, query: any) => PluginHandler.Handler.Page(page, pageSize, query),
  PluginCheckInstalled: (publicId: string) => PluginHandler.Handler.CheckInstalled(publicId),
  PluginGetPluginRoot: () => PluginHandler.Handler.GetPluginRoot(),
  PluginInstallFromPath: (packagePath: string, installType: number) => PluginHandler.Handler.InstallFromPath(packagePath, installType),
  PluginReinstall: (pluginPublicId: string, installType: number) => PluginHandler.Handler.Reinstall(pluginPublicId, installType),
  PluginUninstall: (pluginPublicId: string) => PluginHandler.Handler.Uninstall(pluginPublicId),
  PluginSetUninstalled: (pluginId: number) => PluginHandler.Handler.SetUninstalled(pluginId),
  PluginReadVueFile: (pluginPublicId: string, filePath: string) => PluginHandler.Handler.ReadVueFile(pluginPublicId, filePath),

  // Task
  TaskGetById: (id: number) => TaskHandler.Handler.GetById(id),
  TaskQueryPage: (query: any) => TaskHandler.Handler.QueryPage(query.page, query.pageSize, query.query),
  TaskQueryParentPage: (query: any) => TaskHandler.Handler.QueryParentPage(query.page, query.pageSize, query.query),
  TaskCreate: (task: any) => TaskHandler.Handler.CreateTask(task),
  TaskDelete: (id: number) => TaskHandler.Handler.DeleteTask(id),
  TaskCreateByURL: (url: string) => TaskHandler.Handler.CreateTaskByURL(url),
  TaskQueryChildrenTaskPage: (pid: number, query: any) => TaskHandler.Handler.QueryChildrenTaskPage(pid, query.page, query.pageSize, query.query),
  TaskListChildrenTask: (pid: number) => TaskHandler.Handler.ListChildrenTask(pid),
  TaskQueryTreeDataPage: (treeId: number) => TaskHandler.Handler.QueryTreeDataPage(treeId),
  TaskListTree: (taskIds: number[]) => TaskHandler.Handler.ListTaskTree(taskIds),
  TaskListStatus: (ids: number[]) => TaskHandler.Handler.ListStatus(ids),
  TaskListSchedule: (ids: number[]) => TaskHandler.Handler.ListSchedule(ids),

  // TaskManager
  TaskManagerStartTree: (taskId: number) => TaskManagerHandler.Handler.StartTaskTree(taskId),
  TaskManagerPauseTree: (taskId: number) => TaskManagerHandler.Handler.PauseTaskTree(taskId),
  TaskManagerResumeTree: (taskId: number) => TaskManagerHandler.Handler.ResumeTaskTree(taskId),
  TaskManagerStopTree: (taskId: number) => TaskManagerHandler.Handler.StopTaskTree(taskId),
  TaskManagerRetryTree: (taskId: number) => TaskManagerHandler.Handler.RetryTree(taskId),
  TaskManagerGetTaskTreeState: (taskId: number) => TaskManagerHandler.Handler.GetTaskTreeState(taskId),
  TaskManagerGetTaskState: (taskId: number) => TaskManagerHandler.Handler.GetTaskState(taskId),
  TaskManagerIsIdle: () => TaskManagerHandler.Handler.IsIdle(),

  // Slot
  GetAllSlots: () => SlotHandler.Handler.GetAllSlots(),

  // SiteBrowser
  SiteBrowserList: () => SiteBrowserHandler.Handler.List(),
  SiteBrowserGetByID: (pluginPublicId: string, contributionId: string) => SiteBrowserHandler.Handler.GetByID(pluginPublicId, contributionId),
  SiteBrowserGetByPluginID: (pluginId: number) => SiteBrowserHandler.Handler.GetByPluginID(pluginId),
  SiteBrowserOpen: (pluginPublicId: string, contributionId: string) => SiteBrowserHandler.Handler.Open(pluginPublicId, contributionId),

  // ReWorkTag
  ReWorkTagSave: (workId: number, tagType: number, tagId: number) => ReWorkTagHandler.Handler.Save(workId, tagType, tagId),
  ReWorkTagSaveBatch: (workId: number, tagType: number, tagIds: number[]) => ReWorkTagHandler.Handler.SaveBatch(workId, tagType, tagIds),
  ReWorkTagDelete: (workId: number, tagType: number, tagId: number) => ReWorkTagHandler.Handler.Delete(workId, tagType, tagId),
  ReWorkTagDeleteBatch: (workId: number, tagType: number, tagIds: number[]) => ReWorkTagHandler.Handler.DeleteBatch(workId, tagType, tagIds),
  ReWorkTagListByWorkId: (workId: number) => ReWorkTagHandler.Handler.ListByWorkId(workId),
  ReWorkTagListLocalTagIdsByWorkId: (workId: number) => ReWorkTagHandler.Handler.ListLocalTagIdsByWorkId(workId),
  ReWorkTagListSiteTagIdsByWorkId: (workId: number) => ReWorkTagHandler.Handler.ListSiteTagIdsByWorkId(workId),
}
