// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

/**
 * WorkAuthorDTO 作品作者信息（包含本地作者和站点作者）
 */
export class WorkAuthorDTO {
    "localAuthors"?: (model$0.RankedLocalAuthor | null)[];
    "siteAuthors"?: (model$0.RankedSiteAuthor | null)[];

    /** Creates a new WorkAuthorDTO instance. */
    constructor($$source: Partial<WorkAuthorDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkAuthorDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkAuthorDTO {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localAuthors" in $$parsedSource) {
            $$parsedSource["localAuthors"] = $$createField0_0($$parsedSource["localAuthors"]);
        }
        if ("siteAuthors" in $$parsedSource) {
            $$parsedSource["siteAuthors"] = $$createField1_0($$parsedSource["siteAuthors"]);
        }
        return new WorkAuthorDTO($$parsedSource as Partial<WorkAuthorDTO>);
    }
}

/**
 * WorkAuthorsResultDTO 批量作品作者信息返回结果
 */
export class WorkAuthorsResultDTO {
    "workId": number;
    "localAuthors"?: (model$0.RankedLocalAuthor | null)[];
    "siteAuthors"?: (model$0.RankedSiteAuthor | null)[];

    /** Creates a new WorkAuthorsResultDTO instance. */
    constructor($$source: Partial<WorkAuthorsResultDTO> = {}) {
        if (!("workId" in $$source)) {
            this["workId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkAuthorsResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkAuthorsResultDTO {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localAuthors" in $$parsedSource) {
            $$parsedSource["localAuthors"] = $$createField1_0($$parsedSource["localAuthors"]);
        }
        if ("siteAuthors" in $$parsedSource) {
            $$parsedSource["siteAuthors"] = $$createField2_0($$parsedSource["siteAuthors"]);
        }
        return new WorkAuthorsResultDTO($$parsedSource as Partial<WorkAuthorsResultDTO>);
    }
}

// Private type creation functions
const $$createType0 = model$0.RankedLocalAuthor.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.RankedSiteAuthor.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
