export enum TaskStatusEnum {
  CREATED = 0,
  WAITING = 1,
  PROCESSING = 2,
  PAUSING = 3,
  PAUSED = 4,
  STOPPING = 5,
  FINISHED = 6,
  FAILED = 7,
  PARTLY_FINISHED = 8,
  WAITING_FOR_INPUT = 9
}
