// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackupResultDTO 备份返回结果DTO（用于屏蔽sql.Null*类型）
 */
export class BackupResultDTO {
    "id": number;
    "sourceType": number | null;
    "sourceId": number | null;
    "fileName": string | null;
    "filePath": string | null;
    "workdir": string | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new BackupResultDTO instance. */
    constructor($$source: Partial<BackupResultDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = null;
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = null;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = null;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = null;
        }
        if (!("workdir" in $$source)) {
            this["workdir"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupResultDTO($$parsedSource as Partial<BackupResultDTO>);
    }
}
