// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 回收站 Handler（方法名显式表达条目实体归属：Works=作品条目、Stores=文件条目，
 * 为作品集条目（WorkSets）的并列扩展留语义空间）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../base/model/dto/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * PageStores 分页查询回收站文件条目（persistent_store 已删行，非「作品已删」聚合形态）
 * query: 文件域条件体系，见 dto.RecycleStorePageQuery
 */
export function PageStores(page: model$0.Page<dto$0.RecycleStoreDTO> | null, query: dto$0.RecycleStorePageQuery | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.RecycleStoreDTO> | null> | null> {
    return $Call.ByID(327218636, page, query).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * PageWorkSets 分页查询回收站作品集条目（work_set 已删行）
 * query: 作品集域平铺条件体系，见 dto.RecycleWorkSetPageQuery
 */
export function PageWorkSets(page: model$0.Page<dto$0.RecycleWorkSetDTO> | null, query: dto$0.RecycleWorkSetPageQuery | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.RecycleWorkSetDTO> | null> | null> {
    return $Call.ByID(1982244126, page, query).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * PageWorks 分页查询回收站作品条目
 * query: 查询条件（SearchCondition 条件体系 + 排序），见 RecyclePageQuery
 */
export function PageWorks(page: model$0.Page<dto$0.RecycleWorkDTO> | null, query: $models.RecyclePageQuery): $CancellablePromise<model$0.ApiResponse<model$0.Page<dto$0.RecycleWorkDTO> | null> | null> {
    return $Call.ByID(1139234152, page, query).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * PurgeStore 彻底删除回收站文件条目（不可恢复，条目单位=store 行）。
 * 文件删除失败（被占用/只读等）时保留记录并返回错误——前端据此询问「仅删记录或放弃」（PurgeStoreRecords）
 * storeId: 已软删 persistent_store 行 ID
 */
export function PurgeStore(storeId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3859689381, storeId).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * PurgeStoreRecords 仅删除回收站文件条目记录（不动磁盘文件）——文件删除失败后用户明确选择「仅删记录」的降级路径
 * storeId: 已软删 persistent_store 行 ID
 */
export function PurgeStoreRecords(storeId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2988714605, storeId).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * PurgeWork 彻底删除回收站作品条目（不可恢复，级联清从属行与备份）。
 * 文件删除失败（被占用/只读等）时保留记录并返回错误——前端据此询问「仅删记录或放弃」（PurgeWorkRecords）
 * workId: 已软删作品 ID
 */
export function PurgeWork(workId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3030960545, workId).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * PurgeWorkRecords 仅删除回收站作品条目记录（不动磁盘文件）——文件删除失败后用户明确选择「仅删记录」的降级路径
 * workId: 已软删作品 ID
 */
export function PurgeWorkRecords(workId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1231168777, workId).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * PurgeWorkSet 彻底删除回收站作品集条目（不可恢复，级联清成员与父子关联行）
 * workSetId: 已软删作品集 ID
 */
export function PurgeWorkSet(workSetId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(4280127911, workSetId).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * RestoreStore 复原文件条目（版本回滚置换：行内备份还原为当前版本，被置换的当前活行转入回收站）
 * storeId: 已软删 persistent_store 行 ID（须有备份且挂载活作品）
 */
export function RestoreStore(storeId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1152685402, storeId).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * RestoreWork 从回收站复原作品条目
 * workId: 已软删作品 ID；overwrite: 检测到业务键被占位时是否将占位作品转入回收站
 */
export function RestoreWork(workId: number, overwrite: boolean): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(2563681660, workId, overwrite).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * RestoreWorkSet 从回收站复原作品集条目
 * workSetId: 已软删作品集 ID；overwrite: 检测到业务键被占位时是否将占位作品集转入回收站
 */
export function RestoreWorkSet(workSetId: number, overwrite: boolean): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(920927092, workSetId, overwrite).then(($result: any) => {
        return $$createType18($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.RecycleStoreDTO.createFrom;
const $$createType1 = model$0.Page.createFrom($$createType0);
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = model$0.ApiResponse.createFrom($$createType2);
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = dto$0.RecycleWorkSetDTO.createFrom;
const $$createType6 = model$0.Page.createFrom($$createType5);
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.ApiResponse.createFrom($$createType7);
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = dto$0.RecycleWorkDTO.createFrom;
const $$createType11 = model$0.Page.createFrom($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = model$0.ApiResponse.createFrom($$createType12);
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType18 = $Create.Nullable($$createType17);
