// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 作品集 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as entity$0 from "../../pkg/model/entity/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除作品集
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3524079901, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取作品集
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<$models.WorkSetResultDTO | null> | null> {
    return $Call.ByID(1001500618, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetBySiteWorkSetIdAndSiteName 根据站点作品集ID和站点名称获取作品集
 */
export function GetBySiteWorkSetIdAndSiteName(siteWorkSetId: string, siteName: string): $CancellablePromise<model$0.ApiResponse<$models.WorkSetResultDTO | null> | null> {
    return $Call.ByID(495360619, siteWorkSetId, siteName).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetCoverWorkId 获取封面作品ID
 */
export function GetCoverWorkId(workSetId: number): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(589631381, workSetId).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetWorksByWorkSetId 获取作品集下的作品列表
 */
export function GetWorksByWorkSetId(workSetId: number): $CancellablePromise<model$0.ApiResponse<(entity$0.Work | null)[]> | null> {
    return $Call.ByID(3166169653, workSetId).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * LinkBatchToWorkSet 批量关联作品到作品集
 */
export function LinkBatchToWorkSet(workSetId: number, workIds: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1202620814, workSetId, workIds).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LinkWorkToWorkSet 关联作品到作品集
 */
export function LinkWorkToWorkSet(workId: number, workSetId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1138854437, workId, workSetId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ListWorkSetWithWorkByIds 根据作品集ID列表获取作品集及作品
 */
export function ListWorkSetWithWorkByIds(workSetIds: number[]): $CancellablePromise<model$0.ApiResponse<($models.WorkSetWithWorksResultDTO | null)[]> | null> {
    return $Call.ByID(1542209505, workSetIds).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: model$0.Page<$models.WorkSetResultDTO, $models.WorkSetQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.WorkSetResultDTO, $models.WorkSetQueryDTO> | null> | null> {
    return $Call.ByID(306740245, page).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * QueryPageWithCover 分页查询作品集（带封面）
 */
export function QueryPageWithCover(page: model$0.Page<$models.WorkSetWithCoverResultDTO, $models.WorkSetQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.WorkSetWithCoverResultDTO, $models.WorkSetQueryDTO> | null> | null> {
    return $Call.ByID(1391581908, page).then(($result: any) => {
        return $$createType27($result);
    });
}

/**
 * RemoveBatchFromWorkSet 批量从作品集移除作品
 */
export function RemoveBatchFromWorkSet(workSetId: number, workIds: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(4280868937, workSetId, workIds).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Save 保存作品集
 */
export function Save(workSet: $models.WorkSetDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(1135512815, workSet).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * SetCover 设置作品集封面
 */
export function SetCover(workSetId: number, workId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3062994113, workSetId, workId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UnlinkWorkFromWorkSet 取消作品与作品集的关联
 */
export function UnlinkWorkFromWorkSet(workId: number, workSetId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(907865851, workId, workSetId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UnsetCover 取消作品集封面
 */
export function UnsetCover(workSetId: number, workId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(220337390, workSetId, workId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Update 更新作品集
 */
export function Update(workSet: $models.WorkSetDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3898832955, workSet).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateSortOrders 批量更新排序顺序
 */
export function UpdateSortOrders(workSetId: number, workIds: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1453918114, workSetId, workIds).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.WorkSetResultDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = entity$0.Work.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = model$0.ApiResponse.createFrom($$createType10);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.WorkSetWithWorksResultDTO.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = model$0.ApiResponse.createFrom($$createType15);
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = $models.WorkSetQueryDTO.createFrom;
const $$createType19 = model$0.Page.createFrom($$createType2, $$createType18);
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = model$0.ApiResponse.createFrom($$createType20);
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $models.WorkSetWithCoverResultDTO.createFrom;
const $$createType24 = model$0.Page.createFrom($$createType23, $$createType18);
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = model$0.ApiResponse.createFrom($$createType25);
const $$createType27 = $Create.Nullable($$createType26);
