// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../../pkg/query/models.js";

/**
 * WorkResultDTO 作品返回结果DTO（用于屏蔽sql.Null*类型）
 */
export class WorkResultDTO {
    "id": number;
    "siteId": number | null;
    "siteWorkId": string | null;
    "siteWorkName": string | null;
    "siteAuthorId": string | null;
    "siteWorkDescription": string | null;
    "siteUploadTime": number | null;
    "siteUpdateTime": number | null;
    "nickName": string | null;
    "localAuthorId": number | null;
    "lastView": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new WorkResultDTO instance. */
    constructor($$source: Partial<WorkResultDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = null;
        }
        if (!("siteWorkName" in $$source)) {
            this["siteWorkName"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("siteWorkDescription" in $$source)) {
            this["siteWorkDescription"] = null;
        }
        if (!("siteUploadTime" in $$source)) {
            this["siteUploadTime"] = null;
        }
        if (!("siteUpdateTime" in $$source)) {
            this["siteUpdateTime"] = null;
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = null;
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = null;
        }
        if (!("lastView" in $$source)) {
            this["lastView"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkResultDTO($$parsedSource as Partial<WorkResultDTO>);
    }
}

/**
 * WorkSetDTO 作品集数据传输对象
 */
export class WorkSetDTO {
    "id": number;
    "siteId": number | null;
    "siteWorkSetName": string | null;

    /** Creates a new WorkSetDTO instance. */
    constructor($$source: Partial<WorkSetDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkSetName" in $$source)) {
            this["siteWorkSetName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkSetDTO($$parsedSource as Partial<WorkSetDTO>);
    }
}

/**
 * WorkSetQueryDTO 作品集查询条件
 */
export class WorkSetQueryDTO {
    /**
     * 站点ID
     */
    "siteId": query$0.QueryAttribute;

    /**
     * 站点作品集ID
     */
    "siteWorkSetId": query$0.QueryAttribute;

    /**
     * 站点作者ID
     */
    "siteAuthorId": query$0.QueryAttribute;

    /**
     * 昵称（精确匹配）
     */
    "nickName": query$0.QueryAttribute;

    /**
     * 站点作品集名称（模糊匹配）
     */
    "siteWorkSetName": query$0.QueryAttribute;

    /**
     * 站点作品集描述（模糊匹配）
     */
    "siteWorkSetDesc": query$0.QueryAttribute;

    /**
     * 昵称（模糊匹配）
     */
    "nickNameStr": query$0.QueryAttribute;

    /**
     * 创建时间（可用于排序）
     */
    "createTime": query$0.QueryAttribute;

    /**
     * 更新时间（可用于排序）
     */
    "updateTime": query$0.QueryAttribute;

    /** Creates a new WorkSetQueryDTO instance. */
    constructor($$source: Partial<WorkSetQueryDTO> = {}) {
        if (!("siteId" in $$source)) {
            this["siteId"] = (new query$0.QueryAttribute());
        }
        if (!("siteWorkSetId" in $$source)) {
            this["siteWorkSetId"] = (new query$0.QueryAttribute());
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = (new query$0.QueryAttribute());
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = (new query$0.QueryAttribute());
        }
        if (!("siteWorkSetName" in $$source)) {
            this["siteWorkSetName"] = (new query$0.QueryAttribute());
        }
        if (!("siteWorkSetDesc" in $$source)) {
            this["siteWorkSetDesc"] = (new query$0.QueryAttribute());
        }
        if (!("nickNameStr" in $$source)) {
            this["nickNameStr"] = (new query$0.QueryAttribute());
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = (new query$0.QueryAttribute());
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = (new query$0.QueryAttribute());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetQueryDTO {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField0_0($$parsedSource["siteId"]);
        }
        if ("siteWorkSetId" in $$parsedSource) {
            $$parsedSource["siteWorkSetId"] = $$createField1_0($$parsedSource["siteWorkSetId"]);
        }
        if ("siteAuthorId" in $$parsedSource) {
            $$parsedSource["siteAuthorId"] = $$createField2_0($$parsedSource["siteAuthorId"]);
        }
        if ("nickName" in $$parsedSource) {
            $$parsedSource["nickName"] = $$createField3_0($$parsedSource["nickName"]);
        }
        if ("siteWorkSetName" in $$parsedSource) {
            $$parsedSource["siteWorkSetName"] = $$createField4_0($$parsedSource["siteWorkSetName"]);
        }
        if ("siteWorkSetDesc" in $$parsedSource) {
            $$parsedSource["siteWorkSetDesc"] = $$createField5_0($$parsedSource["siteWorkSetDesc"]);
        }
        if ("nickNameStr" in $$parsedSource) {
            $$parsedSource["nickNameStr"] = $$createField6_0($$parsedSource["nickNameStr"]);
        }
        if ("createTime" in $$parsedSource) {
            $$parsedSource["createTime"] = $$createField7_0($$parsedSource["createTime"]);
        }
        if ("updateTime" in $$parsedSource) {
            $$parsedSource["updateTime"] = $$createField8_0($$parsedSource["updateTime"]);
        }
        return new WorkSetQueryDTO($$parsedSource as Partial<WorkSetQueryDTO>);
    }
}

/**
 * WorkSetResultDTO 作品集返回结果DTO（用于屏蔽sql.Null*类型）
 */
export class WorkSetResultDTO {
    "id": number;
    "siteId": number | null;
    "siteWorkSetId": string | null;
    "siteWorkSetName": string | null;
    "siteAuthorId": string | null;
    "siteWorkSetDescription": string | null;
    "siteUploadTime": number | null;
    "siteUpdateTime": number | null;
    "nickName": string | null;
    "lastView": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new WorkSetResultDTO instance. */
    constructor($$source: Partial<WorkSetResultDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkSetId" in $$source)) {
            this["siteWorkSetId"] = null;
        }
        if (!("siteWorkSetName" in $$source)) {
            this["siteWorkSetName"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("siteWorkSetDescription" in $$source)) {
            this["siteWorkSetDescription"] = null;
        }
        if (!("siteUploadTime" in $$source)) {
            this["siteUploadTime"] = null;
        }
        if (!("siteUpdateTime" in $$source)) {
            this["siteUpdateTime"] = null;
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = null;
        }
        if (!("lastView" in $$source)) {
            this["lastView"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkSetResultDTO($$parsedSource as Partial<WorkSetResultDTO>);
    }
}

/**
 * WorkSetWithCoverResultDTO 作品集及其封面作品信息
 */
export class WorkSetWithCoverResultDTO {
    "workSet": WorkSetResultDTO | null;
    "coverWork"?: WorkResultDTO | null;

    /** Creates a new WorkSetWithCoverResultDTO instance. */
    constructor($$source: Partial<WorkSetWithCoverResultDTO> = {}) {
        if (!("workSet" in $$source)) {
            this["workSet"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetWithCoverResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetWithCoverResultDTO {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workSet" in $$parsedSource) {
            $$parsedSource["workSet"] = $$createField0_0($$parsedSource["workSet"]);
        }
        if ("coverWork" in $$parsedSource) {
            $$parsedSource["coverWork"] = $$createField1_0($$parsedSource["coverWork"]);
        }
        return new WorkSetWithCoverResultDTO($$parsedSource as Partial<WorkSetWithCoverResultDTO>);
    }
}

/**
 * WorkSetWithWorksResultDTO 作品集及其作品信息
 */
export class WorkSetWithWorksResultDTO {
    "workSet": WorkSetResultDTO | null;
    "works": (WorkResultDTO | null)[];

    /** Creates a new WorkSetWithWorksResultDTO instance. */
    constructor($$source: Partial<WorkSetWithWorksResultDTO> = {}) {
        if (!("workSet" in $$source)) {
            this["workSet"] = null;
        }
        if (!("works" in $$source)) {
            this["works"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetWithWorksResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetWithWorksResultDTO {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workSet" in $$parsedSource) {
            $$parsedSource["workSet"] = $$createField0_0($$parsedSource["workSet"]);
        }
        if ("works" in $$parsedSource) {
            $$parsedSource["works"] = $$createField1_0($$parsedSource["works"]);
        }
        return new WorkSetWithWorksResultDTO($$parsedSource as Partial<WorkSetWithWorksResultDTO>);
    }
}

// Private type creation functions
const $$createType0 = query$0.QueryAttribute.createFrom;
const $$createType1 = WorkSetResultDTO.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = WorkResultDTO.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
