// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WorkSetDTO 作品集数据传输对象
 */
export class WorkSetDTO {
    "id": number;
    "siteId": number | null;
    "siteWorkSetName": string | null;

    /** Creates a new WorkSetDTO instance. */
    constructor($$source: Partial<WorkSetDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkSetName" in $$source)) {
            this["siteWorkSetName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkSetDTO($$parsedSource as Partial<WorkSetDTO>);
    }
}

/**
 * WorkSetQueryDTO 作品集查询条件
 */
export class WorkSetQueryDTO {
    /**
     * 站点ID
     */
    "siteId": number | null;

    /**
     * 站点作品集ID
     */
    "siteWorkSetId": string | null;

    /**
     * 站点作者ID
     */
    "siteAuthorId": string | null;

    /**
     * 昵称（精确匹配）
     */
    "nickName": string | null;

    /**
     * 模糊查询
     * 站点作品集名称（模糊匹配）
     */
    "siteWorkSetNameLike": string | null;

    /**
     * 站点作品集描述（模糊匹配）
     */
    "siteWorkSetDescLike": string | null;

    /**
     * 昵称（模糊匹配）
     */
    "nickNameLike": string | null;

    /**
     * 排序字段：create_time, update_time, site_upload_time, site_update_time, last_view, site_work_set_name
     * 排序字段
     */
    "orderBy": string;

    /**
     * 是否降序
     */
    "orderDesc": boolean;

    /** Creates a new WorkSetQueryDTO instance. */
    constructor($$source: Partial<WorkSetQueryDTO> = {}) {
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkSetId" in $$source)) {
            this["siteWorkSetId"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = null;
        }
        if (!("siteWorkSetNameLike" in $$source)) {
            this["siteWorkSetNameLike"] = null;
        }
        if (!("siteWorkSetDescLike" in $$source)) {
            this["siteWorkSetDescLike"] = null;
        }
        if (!("nickNameLike" in $$source)) {
            this["nickNameLike"] = null;
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = "";
        }
        if (!("orderDesc" in $$source)) {
            this["orderDesc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetQueryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkSetQueryDTO($$parsedSource as Partial<WorkSetQueryDTO>);
    }
}
