// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 作品 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除作品
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3630898157, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteWorkAndSurroundingData 删除作品及周边数据
 */
export function DeleteWorkAndSurroundingData(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(4119360905, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取作品
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<$models.WorkResultDTO | null> | null> {
    return $Call.ByID(4285741466, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetFullWorkInfoById 获取完整作品信息
 */
export function GetFullWorkInfoById(id: number): $CancellablePromise<model$0.ApiResponse<model$1.WorkFullDTO | null> | null> {
    return $Call.ByID(454836830, id).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: number, pageSize: number, queryDTO: $models.WorkQueryDTO | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.WorkResultDTO> | null> | null> {
    return $Call.ByID(2743079621, page, pageSize, queryDTO).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * Save 保存作品
 */
export function Save(work: $models.WorkDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(111346079, work).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * Update 更新作品
 */
export function Update(work: $models.WorkDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2273827723, work).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.WorkResultDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$1.WorkFullDTO.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.ApiResponse.createFrom($$createType7);
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = model$0.Page.createFrom($$createType2);
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = model$0.ApiResponse.createFrom($$createType11);
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType15 = $Create.Nullable($$createType14);
