// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WorkQueryDTO 作品查询条件
 */
export class WorkQueryDTO {
    /**
     * 站点ID
     */
    "siteId": number | null;

    /**
     * 站点作品ID
     */
    "siteWorkId": string | null;

    /**
     * 站点作者ID
     */
    "siteAuthorId": string | null;

    /**
     * 本地作者ID
     */
    "localAuthorId": number | null;

    /**
     * 昵称（精确匹配）
     */
    "nickName": string | null;

    /**
     * 模糊查询
     * 站点作品名称（模糊匹配）
     */
    "siteWorkNameLike": string | null;

    /**
     * 站点作品描述（模糊匹配）
     */
    "siteWorkDescLike": string | null;

    /**
     * 昵称（模糊匹配）
     */
    "nickNameLike": string | null;

    /**
     * 排序字段：create_time, update_time, site_upload_time, site_update_time, last_view, site_work_name
     * 排序字段
     */
    "orderBy": string;

    /**
     * 是否降序
     */
    "orderDesc": boolean;

    /** Creates a new WorkQueryDTO instance. */
    constructor($$source: Partial<WorkQueryDTO> = {}) {
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = null;
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = null;
        }
        if (!("siteWorkNameLike" in $$source)) {
            this["siteWorkNameLike"] = null;
        }
        if (!("siteWorkDescLike" in $$source)) {
            this["siteWorkDescLike"] = null;
        }
        if (!("nickNameLike" in $$source)) {
            this["nickNameLike"] = null;
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = "";
        }
        if (!("orderDesc" in $$source)) {
            this["orderDesc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkQueryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkQueryDTO($$parsedSource as Partial<WorkQueryDTO>);
    }
}
