// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 导出 Handler（Wails Bind 方法，经 IPC 暴露给前端）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelExport 取消指定导出（无进行中导出则 no-op）。
 */
export function CancelExport(exportID: string): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(347395385, exportID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Collect 收集导出数据模型（决策5：id 列表透传——前端把选中 work/workSet id 列表传给后端）。
 */
export function Collect(workIDs: number[], workSetIDs: number[]): $CancellablePromise<model$0.ApiResponse<$models.ExportModel | null> | null> {
    return $Call.ByID(2412892345, workIDs, workSetIDs).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * StartExport 启动导出（异步：立即返回 exportID，进度/完成经 export-events 事件推送）。
 * outputDir 为空时落盘到工作目录根（默认）；非空为自选输出目录（前端经文件选择器挑选并持久化）。
 */
export function StartExport(workIDs: number[], workSetIDs: number[], outputDir: string): $CancellablePromise<model$0.ApiResponse<string> | null> {
    return $Call.ByID(3732176901, workIDs, workSetIDs, outputDir).then(($result: any) => {
        return $$createType7($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ExportModel.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType7 = $Create.Nullable($$createType6);
