// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 安全存储 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";

/**
 * Delete 删除值
 */
export function Delete(storageKey: string): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(929032387, storageKey).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Get 获取值
 */
export function Get(storageKey: string): $CancellablePromise<model$0.ApiResponse<string> | null> {
    return $Call.ByID(2601155524, storageKey).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Keys 获取所有键
 */
export function Keys(): $CancellablePromise<model$0.ApiResponse<string[]> | null> {
    return $Call.ByID(1012073756).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Set 设置值
 */
export function Set(storageKey: string, plainValue: string, description: string): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(421045592, storageKey, plainValue, description).then(($result: any) => {
        return $$createType8($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = model$0.ApiResponse.createFrom($$createType4);
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType8 = $Create.Nullable($$createType7);
