// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../../../encoding/json/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "./model/models.js";

/**
 * ContentType 插槽内容类型
 */
export enum ContentType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ContentTypeVueSource Vue 源码
     */
    ContentTypeVueSource = "vueSource",

    /**
     * ContentTypePrecompiled 预编译 JS/CSS
     */
    ContentTypePrecompiled = "precompiled",

    /**
     * ContentTypeCode JavaScript 代码字符串
     */
    ContentTypeCode = "code",

    /**
     * ContentTypeHTML HTML 文件
     */
    ContentTypeHTML = "html",
};

/**
 * SlotConfig 插槽配置
 */
export class SlotConfig {
    /**
     * 扩展点类型
     */
    "Type": model$0.ExtensionType;

    /**
     * 扩展点ID
     */
    "ID": string;

    /**
     * 插件数据库ID
     */
    "PluginID": number;

    /**
     * 插件公开ID
     */
    "PluginPublicID": string;

    /**
     * 扩展点名称
     */
    "Name": string;

    /**
     * 扩展点描述
     */
    "Description": string;

    /**
     * 插槽类型
     */
    "SlotType": SlotType;

    /**
     * 插槽内容（JSON 结构，前端根据 ContentType 解析）
     */
    "Content": json$0.RawMessage;

    /**
     * 内容类型
     */
    "ContentType": ContentType;

    /**
     * 插槽标题
     */
    "Title": string;

    /**
     * 插槽图标
     */
    "Icon": string;

    /**
     * 排序
     */
    "Order": number;

    /**
     * 扩展字段（声明式注册使用）
     * panel: left-sidebar|right-sidebar|bottom; embed: topbar|toolbar|statusbar
     */
    "Position": string;

    /**
     * panel: 宽度
     */
    "Width": number | null;

    /**
     * panel: 高度
     */
    "Height": number | null;

    /**
     * menu: 关联的 view slot ID
     */
    "ViewId": string;

    /**
     * siteBrowserList: 关联的 siteBrowser contribution ID
     */
    "ContributionId": string;

    /** Creates a new SlotConfig instance. */
    constructor($$source: Partial<SlotConfig> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = model$0.ExtensionType.$zero;
        }
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("PluginID" in $$source)) {
            this["PluginID"] = 0;
        }
        if (!("PluginPublicID" in $$source)) {
            this["PluginPublicID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("SlotType" in $$source)) {
            this["SlotType"] = SlotType.$zero;
        }
        if (!("Content" in $$source)) {
            this["Content"] = null;
        }
        if (!("ContentType" in $$source)) {
            this["ContentType"] = ContentType.$zero;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("Icon" in $$source)) {
            this["Icon"] = "";
        }
        if (!("Order" in $$source)) {
            this["Order"] = 0;
        }
        if (!("Position" in $$source)) {
            this["Position"] = "";
        }
        if (!("Width" in $$source)) {
            this["Width"] = null;
        }
        if (!("Height" in $$source)) {
            this["Height"] = null;
        }
        if (!("ViewId" in $$source)) {
            this["ViewId"] = "";
        }
        if (!("ContributionId" in $$source)) {
            this["ContributionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SlotConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SlotConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SlotConfig($$parsedSource as Partial<SlotConfig>);
    }
}

/**
 * SlotType 插槽类型
 */
export enum SlotType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * SlotTypeEmbed 嵌入插槽
     */
    SlotTypeEmbed = "embed",

    /**
     * SlotTypePanel 面板插槽
     */
    SlotTypePanel = "panel",

    /**
     * SlotTypeView 视图插槽
     */
    SlotTypeView = "view",

    /**
     * SlotTypeMenu 菜单插槽
     */
    SlotTypeMenu = "menu",

    /**
     * SlotTypeSiteBrowserList 站点浏览器列表插槽
     */
    SlotTypeSiteBrowserList = "siteBrowserList",
};
