// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 资源 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../../lvfeng-z/library-squirrel-plugin-sdk/dto/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除资源
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2005888296, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteByWorkId 根据作品ID删除资源
 */
export function DeleteByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3587983933, workId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<$models.ResourceResultDTO | null> | null> {
    return $Call.ByID(1237970633, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListByWorkId 根据作品ID获取资源列表
 */
export function ListByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<($models.ResourceResultDTO | null)[]> | null> {
    return $Call.ByID(3778182254, workId).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Save 保存资源
 */
export function Save(resource: dto$0.ResourceDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(3923956150, resource).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Update 更新资源
 */
export function Update(resource: dto$0.ResourceDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(2969603770, resource).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ResourceResultDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType3);
const $$createType7 = model$0.ApiResponse.createFrom($$createType6);
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType10 = $Create.Nullable($$createType9);
