// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackupDTO 备份保管清单行 DTO（备份管理面板列表；命名字段组合，不嵌实体）
 */
export class BackupDTO {
    /**
     * 清单行 ID
     */
    "id": number;

    /**
     * 保管文件名
     */
    "fileName": string;

    /**
     * 保管相对路径（workDir 基准，正斜杠）
     */
    "filePath": string;

    /**
     * 保管时的 workDir
     */
    "workdir": string;

    /**
     * 保管时刻（毫秒时间戳）
     */
    "createTime": number;

    /**
     * Referenced 是否被业务行引用（有主）；与治理对账同一引用集（含软删 store 行/已卸载插件行引用）
     */
    "referenced": boolean;

    /**
     * FileSize 文件磁盘占用（字节，os.Stat；文件缺失计 0）。仅展示，不参与服务端排序
     * （大小无库列，按大小排序需全量 Stat）
     */
    "fileSize": number;

    /** Creates a new BackupDTO instance. */
    constructor($$source: Partial<BackupDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("workdir" in $$source)) {
            this["workdir"] = "";
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("referenced" in $$source)) {
            this["referenced"] = false;
        }
        if (!("fileSize" in $$source)) {
            this["fileSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupDTO($$parsedSource as Partial<BackupDTO>);
    }
}

/**
 * BackupStatsDTO 备份占用统计（监视哨同源数据面）：总占用、有主/无主拆分、
 * 按引用方分组（数量/占用/最老引用年龄，超 90 天观察阈值由前端高亮）、无主超期圈定
 */
export class BackupStatsDTO {
    /**
     * 清单行总数
     */
    "totalCount": number;

    /**
     * 总磁盘占用
     */
    "totalBytes": number;

    /**
     * 有主清单行数
     */
    "referencedCount": number;

    /**
     * 有主占用
     */
    "referencedBytes": number;

    /**
     * 无主清单行数
     */
    "orphanedCount": number;

    /**
     * 无主占用
     */
    "orphanedBytes": number;

    /**
     * ExpiredOrphanIDs 无主且超保留期的清单行 ID：「清理全部无主」的删除圈定，
     * 与治理正向判据同源（防误杀替换在途还原点/崩溃窗口新孤儿）
     */
    "expiredOrphanIds": number[];

    /**
     * 按引用方分组统计
     */
    "referencers": ReferencerStats[];

    /** Creates a new BackupStatsDTO instance. */
    constructor($$source: Partial<BackupStatsDTO> = {}) {
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("referencedCount" in $$source)) {
            this["referencedCount"] = 0;
        }
        if (!("referencedBytes" in $$source)) {
            this["referencedBytes"] = 0;
        }
        if (!("orphanedCount" in $$source)) {
            this["orphanedCount"] = 0;
        }
        if (!("orphanedBytes" in $$source)) {
            this["orphanedBytes"] = 0;
        }
        if (!("expiredOrphanIds" in $$source)) {
            this["expiredOrphanIds"] = [];
        }
        if (!("referencers" in $$source)) {
            this["referencers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupStatsDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupStatsDTO {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("expiredOrphanIds" in $$parsedSource) {
            $$parsedSource["expiredOrphanIds"] = $$createField6_0($$parsedSource["expiredOrphanIds"]);
        }
        if ("referencers" in $$parsedSource) {
            $$parsedSource["referencers"] = $$createField7_0($$parsedSource["referencers"]);
        }
        return new BackupStatsDTO($$parsedSource as Partial<BackupStatsDTO>);
    }
}

/**
 * ReconciliationResult 一轮对账的清理统计（手动「立即巡检」返回给备份管理面板）
 */
export class ReconciliationResult {
    /**
     * 正向：清理的无主备份数
     */
    "orphansCleaned": number;

    /**
     * 反向：清除的悬空引用数
     */
    "danglingRefsCleared": number;

    /**
     * 防御：清除的活行非法引用数
     */
    "illegalRefsCleared": number;

    /** Creates a new ReconciliationResult instance. */
    constructor($$source: Partial<ReconciliationResult> = {}) {
        if (!("orphansCleaned" in $$source)) {
            this["orphansCleaned"] = 0;
        }
        if (!("danglingRefsCleared" in $$source)) {
            this["danglingRefsCleared"] = 0;
        }
        if (!("illegalRefsCleared" in $$source)) {
            this["illegalRefsCleared"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconciliationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReconciliationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReconciliationResult($$parsedSource as Partial<ReconciliationResult>);
    }
}

/**
 * ReferencerStats 按引用方分组的引用统计（监视哨 Warn 判定与备份管理面板展示共用）
 */
export class ReferencerStats {
    /**
     * 引用方展示名
     */
    "name": string;

    /**
     * 引用的清单行数
     */
    "count": number;

    /**
     * 引用备份的磁盘占用（文件缺失计 0）
     */
    "totalBytes": number;

    /**
     * 最老引用年龄（天，按清单行创建时刻；0=无引用）
     */
    "oldestAgeDays": number;

    /** Creates a new ReferencerStats instance. */
    constructor($$source: Partial<ReferencerStats> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("oldestAgeDays" in $$source)) {
            this["oldestAgeDays"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReferencerStats instance from a string or object.
     */
    static createFrom($$source: any = {}): ReferencerStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReferencerStats($$parsedSource as Partial<ReferencerStats>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ReferencerStats.createFrom;
const $$createType2 = $Create.Array($$createType1);
