// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../base/query/models.js";

/**
 * CreateTaskByURLResponse 根据URL创建任务的响应
 */
export class CreateTaskByURLResponse {
    "succeed": boolean;
    "addedQuantity": number;
    "msg": string;

    /** Creates a new CreateTaskByURLResponse instance. */
    constructor($$source: Partial<CreateTaskByURLResponse> = {}) {
        if (!("succeed" in $$source)) {
            this["succeed"] = false;
        }
        if (!("addedQuantity" in $$source)) {
            this["addedQuantity"] = 0;
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTaskByURLResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTaskByURLResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateTaskByURLResponse($$parsedSource as Partial<CreateTaskByURLResponse>);
    }
}

/**
 * TaskQueryDTO 任务查询条件。
 * 列名一律带表前缀：查询语句挂 work_task 左连接（领域列在领域表），无前缀的 create_time
 * 等同名列在连接后产生歧义引用
 */
export class TaskQueryDTO {
    /**
     * 父任务ID
     */
    "pid": query$0.QueryAttribute<number>;

    /**
     * 站点ID（领域列）
     */
    "siteId": query$0.QueryAttribute<number>;

    /**
     * 站点作品ID（领域列）
     */
    "siteWorkId": query$0.QueryAttribute<string>;

    /**
     * 任务状态
     */
    "status": query$0.QueryAttribute<number>;

    /**
     * 任务类型（内置类型 eq/ne 过滤：任务面板排除、类型专属视图圈定）
     */
    "taskType": query$0.QueryAttribute<string>;

    /**
     * 是否有子任务
     */
    "hasChild": query$0.QueryAttribute<boolean>;

    /**
     * 插件公开ID（领域列）
     */
    "pluginPublicId": query$0.QueryAttribute<string>;

    /**
     * 插件贡献ID（领域列）
     */
    "pluginExtensionId": query$0.QueryAttribute<string>;

    /**
     * 是否可继续（领域列；0=否，1=是）
     */
    "continuable": query$0.QueryAttribute<boolean>;

    /**
     * 任务名称（模糊匹配）
     */
    "taskName": query$0.QueryAttribute<string>;

    /**
     * 创建时间（可用于排序）
     */
    "createTime": query$0.QueryAttribute<number>;

    /**
     * 更新时间（可用于排序）
     */
    "updateTime": query$0.QueryAttribute<number>;

    /** Creates a new TaskQueryDTO instance. */
    constructor($$source: Partial<TaskQueryDTO> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = (new query$0.QueryAttribute());
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = (new query$0.QueryAttribute());
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = (new query$0.QueryAttribute());
        }
        if (!("status" in $$source)) {
            this["status"] = (new query$0.QueryAttribute());
        }
        if (!("taskType" in $$source)) {
            this["taskType"] = (new query$0.QueryAttribute());
        }
        if (!("hasChild" in $$source)) {
            this["hasChild"] = (new query$0.QueryAttribute());
        }
        if (!("pluginPublicId" in $$source)) {
            this["pluginPublicId"] = (new query$0.QueryAttribute());
        }
        if (!("pluginExtensionId" in $$source)) {
            this["pluginExtensionId"] = (new query$0.QueryAttribute());
        }
        if (!("continuable" in $$source)) {
            this["continuable"] = (new query$0.QueryAttribute());
        }
        if (!("taskName" in $$source)) {
            this["taskName"] = (new query$0.QueryAttribute());
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = (new query$0.QueryAttribute());
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = (new query$0.QueryAttribute());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskQueryDTO {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        const $$createField8_0 = $$createType2;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType0;
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pid" in $$parsedSource) {
            $$parsedSource["pid"] = $$createField0_0($$parsedSource["pid"]);
        }
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField1_0($$parsedSource["siteId"]);
        }
        if ("siteWorkId" in $$parsedSource) {
            $$parsedSource["siteWorkId"] = $$createField2_0($$parsedSource["siteWorkId"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField3_0($$parsedSource["status"]);
        }
        if ("taskType" in $$parsedSource) {
            $$parsedSource["taskType"] = $$createField4_0($$parsedSource["taskType"]);
        }
        if ("hasChild" in $$parsedSource) {
            $$parsedSource["hasChild"] = $$createField5_0($$parsedSource["hasChild"]);
        }
        if ("pluginPublicId" in $$parsedSource) {
            $$parsedSource["pluginPublicId"] = $$createField6_0($$parsedSource["pluginPublicId"]);
        }
        if ("pluginExtensionId" in $$parsedSource) {
            $$parsedSource["pluginExtensionId"] = $$createField7_0($$parsedSource["pluginExtensionId"]);
        }
        if ("continuable" in $$parsedSource) {
            $$parsedSource["continuable"] = $$createField8_0($$parsedSource["continuable"]);
        }
        if ("taskName" in $$parsedSource) {
            $$parsedSource["taskName"] = $$createField9_0($$parsedSource["taskName"]);
        }
        if ("createTime" in $$parsedSource) {
            $$parsedSource["createTime"] = $$createField10_0($$parsedSource["createTime"]);
        }
        if ("updateTime" in $$parsedSource) {
            $$parsedSource["updateTime"] = $$createField11_0($$parsedSource["updateTime"]);
        }
        return new TaskQueryDTO($$parsedSource as Partial<TaskQueryDTO>);
    }
}

// Private type creation functions
const $$createType0 = query$0.QueryAttribute.createFrom($Create.Any);
const $$createType1 = query$0.QueryAttribute.createFrom($Create.Any);
const $$createType2 = query$0.QueryAttribute.createFrom($Create.Any);
