// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackupDTO 备份数据传输对象（无 sql.Null* 版本）
 */
export class BackupDTO {
    "id": number;
    "sourceType": number | null;
    "sourceId": number | null;
    "fileName": string | null;
    "filePath": string | null;
    "workdir": string | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new BackupDTO instance. */
    constructor($$source: Partial<BackupDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("sourceType" in $$source)) {
            this["sourceType"] = null;
        }
        if (!("sourceId" in $$source)) {
            this["sourceId"] = null;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = null;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = null;
        }
        if (!("workdir" in $$source)) {
            this["workdir"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupDTO($$parsedSource as Partial<BackupDTO>);
    }
}

/**
 * LocalAuthorDTO 本地作者数据传输对象（无 sql.Null* 版本）
 */
export class LocalAuthorDTO {
    "id": number;
    "authorName": string | null;
    "introduce": string | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new LocalAuthorDTO instance. */
    constructor($$source: Partial<LocalAuthorDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalAuthorDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalAuthorDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalAuthorDTO($$parsedSource as Partial<LocalAuthorDTO>);
    }
}

/**
 * LocalTagDTO 本地标签数据传输对象（无 sql.Null* 版本）
 */
export class LocalTagDTO {
    "id": number;
    "localTagName": string | null;
    "baseLocalTagId": number | null;
    "description": string | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new LocalTagDTO instance. */
    constructor($$source: Partial<LocalTagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("localTagName" in $$source)) {
            this["localTagName"] = null;
        }
        if (!("baseLocalTagId" in $$source)) {
            this["baseLocalTagId"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalTagDTO($$parsedSource as Partial<LocalTagDTO>);
    }
}

/**
 * LocalTagWithBaseTagDTO 本地标签及其基础标签数据传输对象
 */
export class LocalTagWithBaseTagDTO {
    "id": number;
    "localTagName": string | null;
    "baseLocalTagId": number | null;
    "description": string | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /**
     * 基础标签信息
     */
    "baseTag": LocalTagDTO | null;

    /** Creates a new LocalTagWithBaseTagDTO instance. */
    constructor($$source: Partial<LocalTagWithBaseTagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("localTagName" in $$source)) {
            this["localTagName"] = null;
        }
        if (!("baseLocalTagId" in $$source)) {
            this["baseLocalTagId"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("baseTag" in $$source)) {
            this["baseTag"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTagWithBaseTagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTagWithBaseTagDTO {
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("baseTag" in $$parsedSource) {
            $$parsedSource["baseTag"] = $$createField7_0($$parsedSource["baseTag"]);
        }
        return new LocalTagWithBaseTagDTO($$parsedSource as Partial<LocalTagWithBaseTagDTO>);
    }
}

/**
 * PluginDTO 插件数据传输对象（无 sql.Null* 版本）
 */
export class PluginDTO {
    "id": number;
    "publicId": string | null;
    "author": string | null;
    "name": string | null;
    "version": string | null;
    "description": string | null;
    "changelog": string | null;
    "entryPath": string | null;
    "rootPath": string | null;
    "backupId": number | null;
    "sortNum": number | null;
    "pluginData": string | null;
    "uninstalled": number | null;
    "activationType": string | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new PluginDTO instance. */
    constructor($$source: Partial<PluginDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("publicId" in $$source)) {
            this["publicId"] = null;
        }
        if (!("author" in $$source)) {
            this["author"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = null;
        }
        if (!("version" in $$source)) {
            this["version"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("changelog" in $$source)) {
            this["changelog"] = null;
        }
        if (!("entryPath" in $$source)) {
            this["entryPath"] = null;
        }
        if (!("rootPath" in $$source)) {
            this["rootPath"] = null;
        }
        if (!("backupId" in $$source)) {
            this["backupId"] = null;
        }
        if (!("sortNum" in $$source)) {
            this["sortNum"] = null;
        }
        if (!("pluginData" in $$source)) {
            this["pluginData"] = null;
        }
        if (!("uninstalled" in $$source)) {
            this["uninstalled"] = null;
        }
        if (!("activationType" in $$source)) {
            this["activationType"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PluginDTO($$parsedSource as Partial<PluginDTO>);
    }
}

/**
 * RankedSiteAuthorWithWorkIdDTO 带作品ID的排名站点作者DTO
 */
export class RankedSiteAuthorWithWorkIdDTO {
    "workId": number;
    "siteAuthorId": string | null;
    "authorName": string | null;
    "rank": number;

    /** Creates a new RankedSiteAuthorWithWorkIdDTO instance. */
    constructor($$source: Partial<RankedSiteAuthorWithWorkIdDTO> = {}) {
        if (!("workId" in $$source)) {
            this["workId"] = 0;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("rank" in $$source)) {
            this["rank"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankedSiteAuthorWithWorkIdDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RankedSiteAuthorWithWorkIdDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RankedSiteAuthorWithWorkIdDTO($$parsedSource as Partial<RankedSiteAuthorWithWorkIdDTO>);
    }
}

/**
 * ResourceDTO 资源数据传输对象（无 sql.Null* 版本）
 */
export class ResourceDTO {
    "id": number;
    "workId": number;
    "taskId": number;
    "state": number;
    "filePath": string | null;
    "fileName": string | null;
    "filenameExtension": string | null;
    "suggestName": string | null;
    "resourceSize": number | null;
    "workdir": string | null;
    "resourceComplete": number;
    "createTime": number;
    "updateTime": number;

    /** Creates a new ResourceDTO instance. */
    constructor($$source: Partial<ResourceDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("workId" in $$source)) {
            this["workId"] = 0;
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = null;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = null;
        }
        if (!("filenameExtension" in $$source)) {
            this["filenameExtension"] = null;
        }
        if (!("suggestName" in $$source)) {
            this["suggestName"] = null;
        }
        if (!("resourceSize" in $$source)) {
            this["resourceSize"] = null;
        }
        if (!("workdir" in $$source)) {
            this["workdir"] = null;
        }
        if (!("resourceComplete" in $$source)) {
            this["resourceComplete"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceDTO($$parsedSource as Partial<ResourceDTO>);
    }
}

/**
 * SearchCondition 搜索条件
 */
export class SearchCondition {
    /**
     * 查询参数类型
     */
    "type": SearchType;

    /**
     * 查询参数值
     */
    "value": any;

    /**
     * 操作符 (等于、大于、小于等)
     */
    "operator"?: string;

    /** Creates a new SearchCondition instance. */
    constructor($$source: Partial<SearchCondition> = {}) {
        if (!("type" in $$source)) {
            this["type"] = SearchType.$zero;
        }
        if (!("value" in $$source)) {
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchCondition instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchCondition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchCondition($$parsedSource as Partial<SearchCondition>);
    }
}

/**
 * SearchConditionQuery 搜索条件分页查询请求
 */
export class SearchConditionQuery {
    /**
     * 类型过滤
     */
    "types"?: SearchType[];

    /**
     * 关键词
     */
    "keyword"?: string;

    /** Creates a new SearchConditionQuery instance. */
    constructor($$source: Partial<SearchConditionQuery> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchConditionQuery instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchConditionQuery {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField0_0($$parsedSource["types"]);
        }
        return new SearchConditionQuery($$parsedSource as Partial<SearchConditionQuery>);
    }
}

/**
 * SearchType 搜索类型
 */
export enum SearchType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    SearchTypeLocalTag = 1,
    SearchTypeSiteTag = 2,
    SearchTypeLocalAuthor = 3,
    SearchTypeSiteAuthor = 4,
    SearchTypeWorksSiteName = 5,
    SearchTypeWorksNickname = 6,
    SearchTypeWorksUploadTime = 7,
    SearchTypeWorksLastView = 8,
    SearchTypeMediaType = 9,
    SearchTypeSite = 10,
    SearchTypeWorkSet = 11,
};

/**
 * SelectItem 选择项（用于前端下拉框、列表选择等）
 */
export class SelectItem {
    "value": any;
    "label": string;
    "rootId"?: string;
    "subLabels"?: string[];
    "extraData"?: any;

    /** Creates a new SelectItem instance. */
    constructor($$source: Partial<SelectItem> = {}) {
        if (!("value" in $$source)) {
            this["value"] = null;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectItem instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectItem {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subLabels" in $$parsedSource) {
            $$parsedSource["subLabels"] = $$createField3_0($$parsedSource["subLabels"]);
        }
        return new SelectItem($$parsedSource as Partial<SelectItem>);
    }
}

/**
 * SiteAuthorDTO 站点作者数据传输对象（无 sql.Null* 版本）
 */
export class SiteAuthorDTO {
    "id": number;
    "siteId": number | null;
    "siteAuthorId": string | null;
    "authorName": string | null;
    "fixedAuthorName": string | null;
    "siteAuthorNameBefore": string | null;
    "introduce": string | null;
    "localAuthorId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new SiteAuthorDTO instance. */
    constructor($$source: Partial<SiteAuthorDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = null;
        }
        if (!("siteAuthorNameBefore" in $$source)) {
            this["siteAuthorNameBefore"] = null;
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = null;
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteAuthorDTO($$parsedSource as Partial<SiteAuthorDTO>);
    }
}

/**
 * SiteAuthorFullDTO 站点作者完整DTO（包含绑定的本地作者和来源站点信息）
 * 注意：显式定义所有字段，不使用嵌入（embedding）来复现 TypeScript 的继承行为
 */
export class SiteAuthorFullDTO {
    /**
     * 基础实体字段
     */
    "id": number;
    "createTime": number;
    "updateTime": number;

    /**
     * 站点作者字段
     */
    "siteId": number;
    "siteAuthorId": string;
    "authorName": string;
    "fixedAuthorName": string;
    "siteAuthorNameBefore": string;
    "introduce": string;
    "localAuthorId": number;
    "lastUse": number;

    /**
     * 关联的本地作者
     */
    "localAuthor"?: LocalAuthorDTO | null;

    /**
     * 来源站点
     */
    "site"?: SiteDTO | null;

    /** Creates a new SiteAuthorFullDTO instance. */
    constructor($$source: Partial<SiteAuthorFullDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = 0;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = "";
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = "";
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = "";
        }
        if (!("siteAuthorNameBefore" in $$source)) {
            this["siteAuthorNameBefore"] = "";
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = "";
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = 0;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorFullDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorFullDTO {
        const $$createField11_0 = $$createType5;
        const $$createField12_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localAuthor" in $$parsedSource) {
            $$parsedSource["localAuthor"] = $$createField11_0($$parsedSource["localAuthor"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField12_0($$parsedSource["site"]);
        }
        return new SiteAuthorFullDTO($$parsedSource as Partial<SiteAuthorFullDTO>);
    }
}

/**
 * SiteAuthorLocalRelateDTO 站点作者与本地作者关联DTO
 * 注意：显式定义所有字段，不使用嵌入
 */
export class SiteAuthorLocalRelateDTO {
    /**
     * 基础实体字段
     */
    "id": number;
    "createTime": number;
    "updateTime": number;

    /**
     * 站点作者字段
     */
    "siteId": number;
    "siteAuthorId": string;
    "authorName": string;
    "fixedAuthorName": string;
    "siteAuthorNameBefore": string;
    "introduce": string;
    "localAuthorId": number;
    "lastUse": number;

    /**
     * 关联的本地作者
     */
    "localAuthor"?: LocalAuthorDTO | null;

    /**
     * 来源站点
     */
    "site"?: SiteDTO | null;

    /**
     * 是否有同名本地作者
     */
    "hasSameNameLocalAuthor": boolean;

    /** Creates a new SiteAuthorLocalRelateDTO instance. */
    constructor($$source: Partial<SiteAuthorLocalRelateDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = 0;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = "";
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = "";
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = "";
        }
        if (!("siteAuthorNameBefore" in $$source)) {
            this["siteAuthorNameBefore"] = "";
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = "";
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = 0;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = 0;
        }
        if (!("hasSameNameLocalAuthor" in $$source)) {
            this["hasSameNameLocalAuthor"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorLocalRelateDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorLocalRelateDTO {
        const $$createField11_0 = $$createType5;
        const $$createField12_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localAuthor" in $$parsedSource) {
            $$parsedSource["localAuthor"] = $$createField11_0($$parsedSource["localAuthor"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField12_0($$parsedSource["site"]);
        }
        return new SiteAuthorLocalRelateDTO($$parsedSource as Partial<SiteAuthorLocalRelateDTO>);
    }
}

/**
 * SiteDTO 站点数据传输对象（无 sql.Null* 版本）
 */
export class SiteDTO {
    "id": number;
    "siteName": string | null;
    "siteDescription": string | null;
    "homepage": string | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new SiteDTO instance. */
    constructor($$source: Partial<SiteDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteName" in $$source)) {
            this["siteName"] = null;
        }
        if (!("siteDescription" in $$source)) {
            this["siteDescription"] = null;
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteDTO($$parsedSource as Partial<SiteDTO>);
    }
}

/**
 * SiteTagDTO 站点标签数据传输对象（无 sql.Null* 版本）
 */
export class SiteTagDTO {
    "id": number;
    "siteId": number | null;
    "siteTagId": string | null;
    "siteTagName": string | null;
    "baseSiteTagId": string | null;
    "description": string | null;
    "localTagId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new SiteTagDTO instance. */
    constructor($$source: Partial<SiteTagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = null;
        }
        if (!("siteTagName" in $$source)) {
            this["siteTagName"] = null;
        }
        if (!("baseSiteTagId" in $$source)) {
            this["baseSiteTagId"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteTagDTO($$parsedSource as Partial<SiteTagDTO>);
    }
}

/**
 * SiteTagFullDTO 站点标签完整DTO（包含绑定的本地标签和来源站点信息）
 */
export class SiteTagFullDTO {
    "siteTag"?: SiteTagDTO | null;
    "localTag"?: LocalTagDTO | null;

    /**
     * 来源站点
     */
    "site"?: SiteDTO | null;

    /** Creates a new SiteTagFullDTO instance. */
    constructor($$source: Partial<SiteTagFullDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagFullDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagFullDTO {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteTag" in $$parsedSource) {
            $$parsedSource["siteTag"] = $$createField0_0($$parsedSource["siteTag"]);
        }
        if ("localTag" in $$parsedSource) {
            $$parsedSource["localTag"] = $$createField1_0($$parsedSource["localTag"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField2_0($$parsedSource["site"]);
        }
        return new SiteTagFullDTO($$parsedSource as Partial<SiteTagFullDTO>);
    }
}

/**
 * TaskDTO 任务数据传输对象（无 sql.Null* 版本）
 */
export class TaskDTO {
    "id": number;
    "isCollection": number | null;
    "pid": number | null;
    "taskName": string | null;
    "siteId": number | null;
    "siteWorkId": string | null;
    "url": string | null;
    "status": number;
    "pendingResourceId": number | null;
    "continuable": number | null;
    "pluginPublicId": string | null;
    "pluginContributionId": string | null;
    "pluginData": string | null;
    "errorMessage": string | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new TaskDTO instance. */
    constructor($$source: Partial<TaskDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("isCollection" in $$source)) {
            this["isCollection"] = null;
        }
        if (!("pid" in $$source)) {
            this["pid"] = null;
        }
        if (!("taskName" in $$source)) {
            this["taskName"] = null;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = null;
        }
        if (!("url" in $$source)) {
            this["url"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("pendingResourceId" in $$source)) {
            this["pendingResourceId"] = null;
        }
        if (!("continuable" in $$source)) {
            this["continuable"] = null;
        }
        if (!("pluginPublicId" in $$source)) {
            this["pluginPublicId"] = null;
        }
        if (!("pluginContributionId" in $$source)) {
            this["pluginContributionId"] = null;
        }
        if (!("pluginData" in $$source)) {
            this["pluginData"] = null;
        }
        if (!("errorMessage" in $$source)) {
            this["errorMessage"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskDTO($$parsedSource as Partial<TaskDTO>);
    }
}

/**
 * WorkDTO 作品数据传输对象（无 sql.Null* 版本）
 */
export class WorkDTO {
    "id": number;
    "siteId": number | null;
    "siteWorkId": string | null;
    "siteWorkName": string | null;
    "siteAuthorId": string | null;
    "siteWorkDescription": string | null;
    "siteUploadTime": number | null;
    "siteUpdateTime": number | null;
    "nickName": string | null;
    "localAuthorId": number | null;
    "lastView": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new WorkDTO instance. */
    constructor($$source: Partial<WorkDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkId" in $$source)) {
            this["siteWorkId"] = null;
        }
        if (!("siteWorkName" in $$source)) {
            this["siteWorkName"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("siteWorkDescription" in $$source)) {
            this["siteWorkDescription"] = null;
        }
        if (!("siteUploadTime" in $$source)) {
            this["siteUploadTime"] = null;
        }
        if (!("siteUpdateTime" in $$source)) {
            this["siteUpdateTime"] = null;
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = null;
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = null;
        }
        if (!("lastView" in $$source)) {
            this["lastView"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkDTO($$parsedSource as Partial<WorkDTO>);
    }
}

/**
 * WorkFullDTO 作品完整信息DTO
 */
export class WorkFullDTO {
    /**
     * 基础作品信息（组合 WorkDTO，避免嵌入实体）
     */
    "work"?: WorkDTO | null;

    /**
     * 关联的本地作者列表
     */
    "localAuthors"?: (LocalAuthorDTO | null)[];

    /**
     * 关联的站点作者列表
     */
    "siteAuthors"?: (SiteAuthorFullDTO | null)[];

    /**
     * 关联的站点信息
     */
    "site"?: SiteDTO | null;

    /**
     * 关联的本地标签列表
     */
    "localTags"?: (LocalTagDTO | null)[];

    /**
     * 关联的站点标签列表
     */
    "siteTags"?: (SiteTagFullDTO | null)[];

    /**
     * 关联的资源列表
     */
    "resources"?: (ResourceDTO | null)[];

    /** Creates a new WorkFullDTO instance. */
    constructor($$source: Partial<WorkFullDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkFullDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkFullDTO {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType15;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType16;
        const $$createField5_0 = $$createType19;
        const $$createField6_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("work" in $$parsedSource) {
            $$parsedSource["work"] = $$createField0_0($$parsedSource["work"]);
        }
        if ("localAuthors" in $$parsedSource) {
            $$parsedSource["localAuthors"] = $$createField1_0($$parsedSource["localAuthors"]);
        }
        if ("siteAuthors" in $$parsedSource) {
            $$parsedSource["siteAuthors"] = $$createField2_0($$parsedSource["siteAuthors"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        if ("localTags" in $$parsedSource) {
            $$parsedSource["localTags"] = $$createField4_0($$parsedSource["localTags"]);
        }
        if ("siteTags" in $$parsedSource) {
            $$parsedSource["siteTags"] = $$createField5_0($$parsedSource["siteTags"]);
        }
        if ("resources" in $$parsedSource) {
            $$parsedSource["resources"] = $$createField6_0($$parsedSource["resources"]);
        }
        return new WorkFullDTO($$parsedSource as Partial<WorkFullDTO>);
    }
}

/**
 * WorkSetDTO 作品集数据传输对象（无 sql.Null* 版本）
 */
export class WorkSetDTO {
    "id": number;
    "siteId": number | null;
    "siteWorkSetId": string | null;
    "siteWorkSetName": string | null;
    "siteAuthorId": string | null;
    "siteWorkSetDescription": string | null;
    "siteUploadTime": number | null;
    "siteUpdateTime": number | null;
    "nickName": string | null;
    "lastView": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new WorkSetDTO instance. */
    constructor($$source: Partial<WorkSetDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteWorkSetId" in $$source)) {
            this["siteWorkSetId"] = null;
        }
        if (!("siteWorkSetName" in $$source)) {
            this["siteWorkSetName"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("siteWorkSetDescription" in $$source)) {
            this["siteWorkSetDescription"] = null;
        }
        if (!("siteUploadTime" in $$source)) {
            this["siteUploadTime"] = null;
        }
        if (!("siteUpdateTime" in $$source)) {
            this["siteUpdateTime"] = null;
        }
        if (!("nickName" in $$source)) {
            this["nickName"] = null;
        }
        if (!("lastView" in $$source)) {
            this["lastView"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkSetDTO($$parsedSource as Partial<WorkSetDTO>);
    }
}

/**
 * WorkSetWithCoverResultDTO 作品集及其封面作品信息
 */
export class WorkSetWithCoverResultDTO {
    "workSet": WorkSetDTO | null;
    "coverWork"?: WorkDTO | null;

    /** Creates a new WorkSetWithCoverResultDTO instance. */
    constructor($$source: Partial<WorkSetWithCoverResultDTO> = {}) {
        if (!("workSet" in $$source)) {
            this["workSet"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetWithCoverResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetWithCoverResultDTO {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workSet" in $$parsedSource) {
            $$parsedSource["workSet"] = $$createField0_0($$parsedSource["workSet"]);
        }
        if ("coverWork" in $$parsedSource) {
            $$parsedSource["coverWork"] = $$createField1_0($$parsedSource["coverWork"]);
        }
        return new WorkSetWithCoverResultDTO($$parsedSource as Partial<WorkSetWithCoverResultDTO>);
    }
}

/**
 * WorkSetWithWorksResultDTO 作品集及其作品信息
 */
export class WorkSetWithWorksResultDTO {
    "workSet": WorkSetDTO | null;
    "works": (WorkDTO | null)[];

    /** Creates a new WorkSetWithWorksResultDTO instance. */
    constructor($$source: Partial<WorkSetWithWorksResultDTO> = {}) {
        if (!("workSet" in $$source)) {
            this["workSet"] = null;
        }
        if (!("works" in $$source)) {
            this["works"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetWithWorksResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetWithWorksResultDTO {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workSet" in $$parsedSource) {
            $$parsedSource["workSet"] = $$createField0_0($$parsedSource["workSet"]);
        }
        if ("works" in $$parsedSource) {
            $$parsedSource["works"] = $$createField1_0($$parsedSource["works"]);
        }
        return new WorkSetWithWorksResultDTO($$parsedSource as Partial<WorkSetWithWorksResultDTO>);
    }
}

// Private type creation functions
const $$createType0 = LocalTagDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = LocalAuthorDTO.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = SiteDTO.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = SiteTagDTO.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = WorkDTO.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType5);
const $$createType13 = SiteAuthorFullDTO.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $Create.Array($$createType1);
const $$createType17 = SiteTagFullDTO.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = ResourceDTO.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = WorkSetDTO.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $Create.Array($$createType11);
