// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ApiResponse 统一API响应格式（匹配前端 ApiResponse.ts）。
 * 语义单向不变量：Success 为 false ⇔ 纯失败——操作未达成，Msg 为用户可读原因，Data 无意义（恒零值，
 * 只经 Error/HandleError/HandleResult 构造，禁止手工构造携带 Data 的失败响应）；一切非失败的业务
 * 分支态（候选冲突待用户显选、批量逐条结果、降级成功）住 Success 为 true 的 Data 载荷内，由载荷
 * 自带标志表达。Msg 在成功时为附注说明（默认 "success"，降级/引导文案经 SuccessWithMsg），不承载
 * 调用方的分支判定
 */
export class ApiResponse<T> {
    /**
     * 是否成功
     */
    "success": boolean;

    /**
     * 消息
     */
    "msg": string;

    /**
     * 数据
     */
    "data"?: T;

    /** Creates a new ApiResponse instance. */
    constructor($$source: Partial<ApiResponse<T>> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("msg" in $$source)) {
            this["msg"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class ApiResponse.
     */
    static createFrom<T = any>($$createParamT: (source: any) => T): ($$source?: any) => ApiResponse<T> {
        const $$createField2_0 = $$createParamT;
        return ($$source: any = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("data" in $$parsedSource) {
                $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
            }
            return new ApiResponse<T>($$parsedSource as Partial<ApiResponse<T>>);
        };
    }
}

/**
 * Page 分页响应（与渲染进程 IPage 保持一致）
 */
export class Page<D> {
    /**
     * 当前页码
     */
    "pageNumber": number;

    /**
     * 分页大小
     */
    "pageSize": number;

    /**
     * 总页数
     */
    "pageCount": number;

    /**
     * 数据总量
     */
    "dataCount": number;

    /**
     * 本页数据量
     */
    "currentCount": number;

    /**
     * 数据列表
     */
    "data": (D | null)[];

    /** Creates a new Page instance. */
    constructor($$source: Partial<Page<D>> = {}) {
        if (!("pageNumber" in $$source)) {
            this["pageNumber"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }
        if (!("pageCount" in $$source)) {
            this["pageCount"] = 0;
        }
        if (!("dataCount" in $$source)) {
            this["dataCount"] = 0;
        }
        if (!("currentCount" in $$source)) {
            this["currentCount"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class Page.
     */
    static createFrom<D = any>($$createParamD: (source: any) => D): ($$source?: any) => Page<D> {
        const $$createField5_0 = $$createType1($$createParamD);
        return ($$source: any = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("data" in $$parsedSource) {
                $$parsedSource["data"] = $$createField5_0($$parsedSource["data"]);
            }
            return new Page<D>($$parsedSource as Partial<Page<D>>);
        };
    }
}

// Private type creation functions
const $$createType0 = ($$createParamD: any) => $Create.Nullable($$createParamD);
const $$createType1 = ($$createParamD: any) => $Create.Array($$createType0($$createParamD));
