// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * WorkSetQueryDTO 作品集查询条件
 */
export class WorkSetQueryDTO {
    /**
     * 关键词
     */
    "keyword": string;

    /**
     * 站点ID
     */
    "siteId": number | null;

    /** Creates a new WorkSetQueryDTO instance. */
    constructor($$source: Partial<WorkSetQueryDTO> = {}) {
        if (!("keyword" in $$source)) {
            this["keyword"] = "";
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkSetQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkSetQueryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkSetQueryDTO($$parsedSource as Partial<WorkSetQueryDTO>);
    }
}
