// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as gen$0 from "../../gen/models.js";

/**
 * Context 主程序渲染某 resourceType 资源、命中插件渲染器时注入的完整 props。
 */
export class Context {
    "work"?: dto$0.WorkDTO | null;
    "localAuthors"?: (RankedLocalAuthor | null)[];
    "siteAuthors"?: (RankedSiteAuthor | null)[];
    "site"?: dto$0.SiteDTO | null;
    "localTags"?: (dto$0.LocalTagDTO | null)[];
    "siteTags"?: (SiteTagFullDTO | null)[];
    "resource"?: ResourceFullDTO | null;

    /** Creates a new Context instance. */
    constructor($$source: Partial<Context> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Context instance from a string or object.
     */
    static createFrom($$source: any = {}): Context {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType12;
        const $$createField5_0 = $$createType15;
        const $$createField6_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("work" in $$parsedSource) {
            $$parsedSource["work"] = $$createField0_0($$parsedSource["work"]);
        }
        if ("localAuthors" in $$parsedSource) {
            $$parsedSource["localAuthors"] = $$createField1_0($$parsedSource["localAuthors"]);
        }
        if ("siteAuthors" in $$parsedSource) {
            $$parsedSource["siteAuthors"] = $$createField2_0($$parsedSource["siteAuthors"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField3_0($$parsedSource["site"]);
        }
        if ("localTags" in $$parsedSource) {
            $$parsedSource["localTags"] = $$createField4_0($$parsedSource["localTags"]);
        }
        if ("siteTags" in $$parsedSource) {
            $$parsedSource["siteTags"] = $$createField5_0($$parsedSource["siteTags"]);
        }
        if ("resource" in $$parsedSource) {
            $$parsedSource["resource"] = $$createField6_0($$parsedSource["resource"]);
        }
        return new Context($$parsedSource as Partial<Context>);
    }
}

/**
 * PersistentStoreDTO 文件持久存储信息。
 */
export class PersistentStoreDTO {
    "id": number;
    "filePath": string | null;
    "fileName": string | null;
    "filenameExtension": string | null;

    /**
     * 0=未完成，1=完成
     */
    "status": number;

    /**
     * 图片宽度（像素），非图片为 0
     */
    "width": number;

    /**
     * 图片高度（像素），非图片为 0
     */
    "height": number;
    "createTime": number;
    "updateTime": number;

    /** Creates a new PersistentStoreDTO instance. */
    constructor($$source: Partial<PersistentStoreDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = null;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = null;
        }
        if (!("filenameExtension" in $$source)) {
            this["filenameExtension"] = null;
        }
        if (!("status" in $$source)) {
            this["status"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PersistentStoreDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): PersistentStoreDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PersistentStoreDTO($$parsedSource as Partial<PersistentStoreDTO>);
    }
}

/**
 * RankedLocalAuthor 带角色与排序的本地作者。
 */
export class RankedLocalAuthor {
    "author": dto$0.LocalAuthorDTO;
    "roleName": string;
    "sortOrder": number;

    /** Creates a new RankedLocalAuthor instance. */
    constructor($$source: Partial<RankedLocalAuthor> = {}) {
        if (!("author" in $$source)) {
            this["author"] = (new dto$0.LocalAuthorDTO());
        }
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankedLocalAuthor instance from a string or object.
     */
    static createFrom($$source: any = {}): RankedLocalAuthor {
        const $$createField0_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField0_0($$parsedSource["author"]);
        }
        return new RankedLocalAuthor($$parsedSource as Partial<RankedLocalAuthor>);
    }
}

/**
 * RankedSiteAuthor 带角色与排序的站点作者。
 */
export class RankedSiteAuthor {
    "author": SiteAuthorDTO;
    "roleName": string;
    "sortOrder": number;

    /** Creates a new RankedSiteAuthor instance. */
    constructor($$source: Partial<RankedSiteAuthor> = {}) {
        if (!("author" in $$source)) {
            this["author"] = (new SiteAuthorDTO());
        }
        if (!("roleName" in $$source)) {
            this["roleName"] = "";
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankedSiteAuthor instance from a string or object.
     */
    static createFrom($$source: any = {}): RankedSiteAuthor {
        const $$createField0_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField0_0($$parsedSource["author"]);
        }
        return new RankedSiteAuthor($$parsedSource as Partial<RankedSiteAuthor>);
    }
}

/**
 * ResourceFullDTO 资源完整信息。Stores 为全量多轨 store（主数据源）；WorkStore 为展示主体
 * （按资源类型 PrimaryRoles 优先级链派生）；ThumbnailStore 为缩略图便捷访问器。
 */
export class ResourceFullDTO {
    "id": number;
    "workId": number;
    "taskId": number;
    "enabled": boolean;
    "suggestName": string | null;
    "resourceType": string;
    "resourceComplete": number;
    "stores"?: ResourceStoreDTO[];
    "workStore"?: PersistentStoreDTO | null;
    "thumbnailStore"?: PersistentStoreDTO | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new ResourceFullDTO instance. */
    constructor($$source: Partial<ResourceFullDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("workId" in $$source)) {
            this["workId"] = 0;
        }
        if (!("taskId" in $$source)) {
            this["taskId"] = 0;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("suggestName" in $$source)) {
            this["suggestName"] = null;
        }
        if (!("resourceType" in $$source)) {
            this["resourceType"] = "";
        }
        if (!("resourceComplete" in $$source)) {
            this["resourceComplete"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceFullDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceFullDTO {
        const $$createField7_0 = $$createType21;
        const $$createField8_0 = $$createType23;
        const $$createField9_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stores" in $$parsedSource) {
            $$parsedSource["stores"] = $$createField7_0($$parsedSource["stores"]);
        }
        if ("workStore" in $$parsedSource) {
            $$parsedSource["workStore"] = $$createField8_0($$parsedSource["workStore"]);
        }
        if ("thumbnailStore" in $$parsedSource) {
            $$parsedSource["thumbnailStore"] = $$createField9_0($$parsedSource["thumbnailStore"]);
        }
        return new ResourceFullDTO($$parsedSource as Partial<ResourceFullDTO>);
    }
}

/**
 * ResourceStoreDTO Resource 关联的单个 typed store。
 */
export class ResourceStoreDTO {
    /**
     * image | document | thumbnail | videoTrack | audioTrack | videoMain
     */
    "storeType": string;

    /**
     * downloaded | derived
     */
    "generation": string;
    "store"?: PersistentStoreDTO | null;

    /** Creates a new ResourceStoreDTO instance. */
    constructor($$source: Partial<ResourceStoreDTO> = {}) {
        if (!("storeType" in $$source)) {
            this["storeType"] = "";
        }
        if (!("generation" in $$source)) {
            this["generation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceStoreDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceStoreDTO {
        const $$createField2_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("store" in $$parsedSource) {
            $$parsedSource["store"] = $$createField2_0($$parsedSource["store"]);
        }
        return new ResourceStoreDTO($$parsedSource as Partial<ResourceStoreDTO>);
    }
}

/**
 * SiteAuthorDTO 站点作者。
 */
export class SiteAuthorDTO {
    "id": number;
    "siteId": number | null;
    "siteAuthorId": string | null;
    "authorName": string | null;
    "fixedAuthorName": string | null;
    "siteAuthorNameBefore": string | null;
    "introduce": string | null;
    "homepage": string | null;
    "localAuthorId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new SiteAuthorDTO instance. */
    constructor($$source: Partial<SiteAuthorDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = null;
        }
        if (!("siteAuthorNameBefore" in $$source)) {
            this["siteAuthorNameBefore"] = null;
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = null;
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = null;
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteAuthorDTO($$parsedSource as Partial<SiteAuthorDTO>);
    }
}

/**
 * SiteTagDTO 站点标签。
 */
export class SiteTagDTO {
    "id": number;
    "siteId": number | null;
    "siteTagId": string | null;
    "siteTagName": string | null;
    "baseSiteTagId": string | null;
    "description": string | null;
    "localTagId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new SiteTagDTO instance. */
    constructor($$source: Partial<SiteTagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteTagId" in $$source)) {
            this["siteTagId"] = null;
        }
        if (!("siteTagName" in $$source)) {
            this["siteTagName"] = null;
        }
        if (!("baseSiteTagId" in $$source)) {
            this["baseSiteTagId"] = null;
        }
        if (!("description" in $$source)) {
            this["description"] = null;
        }
        if (!("localTagId" in $$source)) {
            this["localTagId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteTagDTO($$parsedSource as Partial<SiteTagDTO>);
    }
}

/**
 * SiteTagFullDTO 站点标签完整信息（含绑定的本地标签与来源站点）。
 */
export class SiteTagFullDTO {
    "siteTag"?: SiteTagDTO | null;
    "localTag"?: dto$0.LocalTagDTO | null;
    "site"?: dto$0.SiteDTO | null;

    /** Creates a new SiteTagFullDTO instance. */
    constructor($$source: Partial<SiteTagFullDTO> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteTagFullDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteTagFullDTO {
        const $$createField0_0 = $$createType25;
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteTag" in $$parsedSource) {
            $$parsedSource["siteTag"] = $$createField0_0($$parsedSource["siteTag"]);
        }
        if ("localTag" in $$parsedSource) {
            $$parsedSource["localTag"] = $$createField1_0($$parsedSource["localTag"]);
        }
        if ("site" in $$parsedSource) {
            $$parsedSource["site"] = $$createField2_0($$parsedSource["site"]);
        }
        return new SiteTagFullDTO($$parsedSource as Partial<SiteTagFullDTO>);
    }
}

// Private type creation functions
const $$createType0 = gen$0.Work.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = RankedLocalAuthor.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = RankedSiteAuthor.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = gen$0.SiteDTO.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = gen$0.LocalTagDTO.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = SiteTagFullDTO.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ResourceFullDTO.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = gen$0.LocalAuthorDTO.createFrom;
const $$createType19 = SiteAuthorDTO.createFrom;
const $$createType20 = ResourceStoreDTO.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = PersistentStoreDTO.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = SiteTagDTO.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
