// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 资源 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除资源
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(862931394, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteByWorkId 根据作品ID删除资源
 */
export function DeleteByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1146891019, workId).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<model$1.Resource | null> | null> {
    return $Call.ByID(2112164391, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListByWorkId 根据作品ID获取资源列表
 */
export function ListByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<(model$1.Resource | null)[]> | null> {
    return $Call.ByID(3126823840, workId).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Save 保存资源
 */
export function Save(resource: $models.ResourceDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(3241444144, resource).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Update 更新资源
 */
export function Update(resource: $models.ResourceDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3014164060, resource).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$1.Resource.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType3);
const $$createType7 = model$0.ApiResponse.createFrom($$createType6);
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType10 = $Create.Nullable($$createType9);
