// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ResourceDTO 资源数据传输对象
 */
export class ResourceDTO {
    "id": number;
    "workId": number;
    "filePath": string | null;
    "fileName": string | null;

    /** Creates a new ResourceDTO instance. */
    constructor($$source: Partial<ResourceDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("workId" in $$source)) {
            this["workId"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = null;
        }
        if (!("fileName" in $$source)) {
            this["fileName"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResourceDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): ResourceDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResourceDTO($$parsedSource as Partial<ResourceDTO>);
    }
}
