// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sql$0 from "../../../../../database/sql/models.js";

/**
 * PluginWithContribution 带贡献点的插件
 */
export class PluginWithContribution {
    "id": number;
    "createTime": number;
    "updateTime": number;
    "publicId": sql$0.NullString;
    "author": sql$0.NullString;
    "name": sql$0.NullString;
    "version": sql$0.NullString;
    "entryPath": sql$0.NullString;
    "rootPath": sql$0.NullString;
    "backupId": sql$0.NullInt64;
    "sortNum": sql$0.NullInt64;
    "pluginData": sql$0.NullString;
    "uninstalled": sql$0.NullInt64;
    "activationType": sql$0.NullString;

    /**
     * 贡献点类型
     */
    "ContributeKey": string;

    /**
     * 贡献点ID
     */
    "ContributionID": string;

    /** Creates a new PluginWithContribution instance. */
    constructor($$source: Partial<PluginWithContribution> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }
        if (!("publicId" in $$source)) {
            this["publicId"] = (new sql$0.NullString());
        }
        if (!("author" in $$source)) {
            this["author"] = (new sql$0.NullString());
        }
        if (!("name" in $$source)) {
            this["name"] = (new sql$0.NullString());
        }
        if (!("version" in $$source)) {
            this["version"] = (new sql$0.NullString());
        }
        if (!("entryPath" in $$source)) {
            this["entryPath"] = (new sql$0.NullString());
        }
        if (!("rootPath" in $$source)) {
            this["rootPath"] = (new sql$0.NullString());
        }
        if (!("backupId" in $$source)) {
            this["backupId"] = (new sql$0.NullInt64());
        }
        if (!("sortNum" in $$source)) {
            this["sortNum"] = (new sql$0.NullInt64());
        }
        if (!("pluginData" in $$source)) {
            this["pluginData"] = (new sql$0.NullString());
        }
        if (!("uninstalled" in $$source)) {
            this["uninstalled"] = (new sql$0.NullInt64());
        }
        if (!("activationType" in $$source)) {
            this["activationType"] = (new sql$0.NullString());
        }
        if (!("ContributeKey" in $$source)) {
            this["ContributeKey"] = "";
        }
        if (!("ContributionID" in $$source)) {
            this["ContributionID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PluginWithContribution instance from a string or object.
     */
    static createFrom($$source: any = {}): PluginWithContribution {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType1;
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType0;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("publicId" in $$parsedSource) {
            $$parsedSource["publicId"] = $$createField3_0($$parsedSource["publicId"]);
        }
        if ("author" in $$parsedSource) {
            $$parsedSource["author"] = $$createField4_0($$parsedSource["author"]);
        }
        if ("name" in $$parsedSource) {
            $$parsedSource["name"] = $$createField5_0($$parsedSource["name"]);
        }
        if ("version" in $$parsedSource) {
            $$parsedSource["version"] = $$createField6_0($$parsedSource["version"]);
        }
        if ("entryPath" in $$parsedSource) {
            $$parsedSource["entryPath"] = $$createField7_0($$parsedSource["entryPath"]);
        }
        if ("rootPath" in $$parsedSource) {
            $$parsedSource["rootPath"] = $$createField8_0($$parsedSource["rootPath"]);
        }
        if ("backupId" in $$parsedSource) {
            $$parsedSource["backupId"] = $$createField9_0($$parsedSource["backupId"]);
        }
        if ("sortNum" in $$parsedSource) {
            $$parsedSource["sortNum"] = $$createField10_0($$parsedSource["sortNum"]);
        }
        if ("pluginData" in $$parsedSource) {
            $$parsedSource["pluginData"] = $$createField11_0($$parsedSource["pluginData"]);
        }
        if ("uninstalled" in $$parsedSource) {
            $$parsedSource["uninstalled"] = $$createField12_0($$parsedSource["uninstalled"]);
        }
        if ("activationType" in $$parsedSource) {
            $$parsedSource["activationType"] = $$createField13_0($$parsedSource["activationType"]);
        }
        return new PluginWithContribution($$parsedSource as Partial<PluginWithContribution>);
    }
}

// Private type creation functions
const $$createType0 = sql$0.NullString.createFrom;
const $$createType1 = sql$0.NullInt64.createFrom;
