// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 备份 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../base/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dto$0 from "../../../lvfeng-z/library-squirrel-plugin-sdk/dto/models.js";

/**
 * Create 创建备份
 */
export function Create(sourceType: number, sourceId: number, fileName: string, sourcePath: string, workDir: string): $CancellablePromise<model$0.ApiResponse<dto$0.BackupDTO | null> | null> {
    return $Call.ByID(3800164609, sourceType, sourceId, fileName, sourcePath, workDir).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CreatePluginBackup 创建插件备份
 */
export function CreatePluginBackup(sourceId: number, fileName: string, sourcePath: string, workDir: string): $CancellablePromise<model$0.ApiResponse<dto$0.BackupDTO | null> | null> {
    return $Call.ByID(234106224, sourceId, fileName, sourcePath, workDir).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetById 根据ID获取备份
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<dto$0.BackupDTO | null> | null> {
    return $Call.ByID(2746523107, id).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetPluginBackup 获取插件备份
 */
export function GetPluginBackup(sourceId: number): $CancellablePromise<model$0.ApiResponse<dto$0.BackupDTO | null> | null> {
    return $Call.ByID(3374446214, sourceId).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = dto$0.BackupDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ApiResponse.createFrom($$createType1);
const $$createType3 = $Create.Nullable($$createType2);
