// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 站点作者 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除站点作者
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1514788862, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<model$1.SiteAuthor | null> | null> {
    return $Call.ByID(3691656987, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListByWorkId 根据作品ID获取作者列表
 */
export function ListByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<(model$0.RankedSiteAuthor | null)[]> | null> {
    return $Call.ByID(1167056852, workId).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: number, pageSize: number, queryDTO: $models.SiteAuthorQueryDTO | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<model$1.SiteAuthor> | null> | null> {
    return $Call.ByID(19819348, page, pageSize, queryDTO).then(($result: any) => {
        return $$createType14($result);
    });
}

/**
 * Save 保存站点作者
 */
export function Save(author: $models.SiteAuthorDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(1406741580, author).then(($result: any) => {
        return $$createType16($result);
    });
}

/**
 * Update 更新站点作者
 */
export function Update(author: $models.SiteAuthorDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1576222040, author).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateLastUse 更新最后使用时间
 */
export function UpdateLastUse(ids: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(3304317963, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$1.SiteAuthor.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.RankedSiteAuthor.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = model$0.ApiResponse.createFrom($$createType8);
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = model$0.Page.createFrom($$createType2);
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = model$0.ApiResponse.createFrom($$createType12);
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType16 = $Create.Nullable($$createType15);
