// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "../../pkg/query/models.js";

/**
 * LocalAuthorDTO 本地作者数据传输对象
 */
export class LocalAuthorDTO {
    "id": number;
    "authorName": string | null;
    "introduce": string | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new LocalAuthorDTO instance. */
    constructor($$source: Partial<LocalAuthorDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalAuthorDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalAuthorDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalAuthorDTO($$parsedSource as Partial<LocalAuthorDTO>);
    }
}

/**
 * RankedSiteAuthorWithWorkIdDTO 带作品ID的排名站点作者DTO
 */
export class RankedSiteAuthorWithWorkIdDTO {
    "workId": number;
    "siteAuthorId": string | null;
    "authorName": string | null;
    "rank": number;

    /** Creates a new RankedSiteAuthorWithWorkIdDTO instance. */
    constructor($$source: Partial<RankedSiteAuthorWithWorkIdDTO> = {}) {
        if (!("workId" in $$source)) {
            this["workId"] = 0;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("rank" in $$source)) {
            this["rank"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RankedSiteAuthorWithWorkIdDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): RankedSiteAuthorWithWorkIdDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RankedSiteAuthorWithWorkIdDTO($$parsedSource as Partial<RankedSiteAuthorWithWorkIdDTO>);
    }
}

/**
 * SiteAuthorDTO 站点作者数据传输对象
 */
export class SiteAuthorDTO {
    "id": number;
    "siteId": number | null;
    "siteAuthorId": string | null;
    "authorName": string | null;
    "introduce": string | null;

    /** Creates a new SiteAuthorDTO instance. */
    constructor($$source: Partial<SiteAuthorDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteAuthorDTO($$parsedSource as Partial<SiteAuthorDTO>);
    }
}

/**
 * SiteAuthorFullDTO 站点作者完整信息DTO
 */
export class SiteAuthorFullDTO {
    "id": number;
    "siteId": number | null;
    "siteAuthorId": string | null;
    "authorName": string | null;
    "fixedAuthorName": string | null;
    "siteAuthorNameBefore": string | null;
    "introduce": string | null;
    "localAuthorId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;
    "localAuthor"?: LocalAuthorDTO | null;

    /** Creates a new SiteAuthorFullDTO instance. */
    constructor($$source: Partial<SiteAuthorFullDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = null;
        }
        if (!("siteAuthorNameBefore" in $$source)) {
            this["siteAuthorNameBefore"] = null;
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = null;
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorFullDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorFullDTO {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localAuthor" in $$parsedSource) {
            $$parsedSource["localAuthor"] = $$createField11_0($$parsedSource["localAuthor"]);
        }
        return new SiteAuthorFullDTO($$parsedSource as Partial<SiteAuthorFullDTO>);
    }
}

/**
 * SiteAuthorLocalRelateDTO 站点作者与本地作者关联DTO
 */
export class SiteAuthorLocalRelateDTO {
    "id": number;
    "siteId": number | null;
    "siteAuthorId": string | null;
    "authorName": string | null;
    "fixedAuthorName": string | null;
    "siteAuthorNameBefore": string | null;
    "introduce": string | null;
    "localAuthorId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;
    "localAuthor"?: LocalAuthorDTO | null;

    /** Creates a new SiteAuthorLocalRelateDTO instance. */
    constructor($$source: Partial<SiteAuthorLocalRelateDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = null;
        }
        if (!("siteAuthorNameBefore" in $$source)) {
            this["siteAuthorNameBefore"] = null;
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = null;
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorLocalRelateDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorLocalRelateDTO {
        const $$createField11_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("localAuthor" in $$parsedSource) {
            $$parsedSource["localAuthor"] = $$createField11_0($$parsedSource["localAuthor"]);
        }
        return new SiteAuthorLocalRelateDTO($$parsedSource as Partial<SiteAuthorLocalRelateDTO>);
    }
}

/**
 * SiteAuthorQueryDTO 站点作者查询条件
 */
export class SiteAuthorQueryDTO {
    /**
     * 站点ID
     */
    "siteId": query$0.QueryAttribute;

    /**
     * 站点作者ID（外部）
     */
    "siteAuthorId": query$0.QueryAttribute;

    /**
     * 本地作者ID
     */
    "localAuthorId": query$0.QueryAttribute;

    /**
     * 固定作者名称
     */
    "fixedAuthorName": query$0.QueryAttribute;

    /**
     * 是否绑定到指定本地作者（非数据库字段）
     */
    "boundOnLocalAuthorId": query$0.QueryAttribute;

    /**
     * 作者名称（模糊匹配）
     */
    "authorName": query$0.QueryAttribute;

    /**
     * 介绍（模糊匹配）
     */
    "introduce": query$0.QueryAttribute;

    /**
     * 排序字段
     */
    "orderBy": query$0.QueryAttribute;

    /** Creates a new SiteAuthorQueryDTO instance. */
    constructor($$source: Partial<SiteAuthorQueryDTO> = {}) {
        if (!("siteId" in $$source)) {
            this["siteId"] = (new query$0.QueryAttribute());
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = (new query$0.QueryAttribute());
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = (new query$0.QueryAttribute());
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = (new query$0.QueryAttribute());
        }
        if (!("boundOnLocalAuthorId" in $$source)) {
            this["boundOnLocalAuthorId"] = (new query$0.QueryAttribute());
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = (new query$0.QueryAttribute());
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = (new query$0.QueryAttribute());
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = (new query$0.QueryAttribute());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorQueryDTO {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("siteId" in $$parsedSource) {
            $$parsedSource["siteId"] = $$createField0_0($$parsedSource["siteId"]);
        }
        if ("siteAuthorId" in $$parsedSource) {
            $$parsedSource["siteAuthorId"] = $$createField1_0($$parsedSource["siteAuthorId"]);
        }
        if ("localAuthorId" in $$parsedSource) {
            $$parsedSource["localAuthorId"] = $$createField2_0($$parsedSource["localAuthorId"]);
        }
        if ("fixedAuthorName" in $$parsedSource) {
            $$parsedSource["fixedAuthorName"] = $$createField3_0($$parsedSource["fixedAuthorName"]);
        }
        if ("boundOnLocalAuthorId" in $$parsedSource) {
            $$parsedSource["boundOnLocalAuthorId"] = $$createField4_0($$parsedSource["boundOnLocalAuthorId"]);
        }
        if ("authorName" in $$parsedSource) {
            $$parsedSource["authorName"] = $$createField5_0($$parsedSource["authorName"]);
        }
        if ("introduce" in $$parsedSource) {
            $$parsedSource["introduce"] = $$createField6_0($$parsedSource["introduce"]);
        }
        if ("orderBy" in $$parsedSource) {
            $$parsedSource["orderBy"] = $$createField7_0($$parsedSource["orderBy"]);
        }
        return new SiteAuthorQueryDTO($$parsedSource as Partial<SiteAuthorQueryDTO>);
    }
}

/**
 * SiteAuthorResultDTO 站点作者返回结果DTO（用于屏蔽sql.Null*类型）
 */
export class SiteAuthorResultDTO {
    "id": number;
    "siteId": number | null;
    "siteAuthorId": string | null;
    "authorName": string | null;
    "fixedAuthorName": string | null;
    "siteAuthorNameBefore": string | null;
    "introduce": string | null;
    "localAuthorId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new SiteAuthorResultDTO instance. */
    constructor($$source: Partial<SiteAuthorResultDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("siteId" in $$source)) {
            this["siteId"] = null;
        }
        if (!("siteAuthorId" in $$source)) {
            this["siteAuthorId"] = null;
        }
        if (!("authorName" in $$source)) {
            this["authorName"] = null;
        }
        if (!("fixedAuthorName" in $$source)) {
            this["fixedAuthorName"] = null;
        }
        if (!("siteAuthorNameBefore" in $$source)) {
            this["siteAuthorNameBefore"] = null;
        }
        if (!("introduce" in $$source)) {
            this["introduce"] = null;
        }
        if (!("localAuthorId" in $$source)) {
            this["localAuthorId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SiteAuthorResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): SiteAuthorResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SiteAuthorResultDTO($$parsedSource as Partial<SiteAuthorResultDTO>);
    }
}

// Private type creation functions
const $$createType0 = LocalAuthorDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = query$0.QueryAttribute.createFrom;
