// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 本地标签 Handler
 * 用于 Wails Bind[] 参数，暴露给前端调用
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除本地标签
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1690125945, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<$models.LocalTagResultDTO | null> | null> {
    return $Call.ByID(3237147342, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetTree 获取标签树形结构
 */
export function GetTree(rootId: number, depth: number): $CancellablePromise<model$0.ApiResponse<($models.LocalTagResultDTO | null)[]> | null> {
    return $Call.ByID(4269917526, rootId, depth).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListByWorkId 根据作品ID获取标签列表
 */
export function ListByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<($models.LocalTagResultDTO | null)[]> | null> {
    return $Call.ByID(3732754883, workId).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * ListSelectItems 查询选择项列表
 */
export function ListSelectItems(queryDTO: $models.LocalTagQueryDTO | null): $CancellablePromise<model$0.ApiResponse<(model$1.SelectItem | null)[]> | null> {
    return $Call.ByID(4294102430, queryDTO).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: model$0.Page<$models.LocalTagQueryDTO> | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.LocalTagResultDTO> | null> | null> {
    return $Call.ByID(112028121, page).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * QuerySelectItemPage 分页查询选择项
 */
export function QuerySelectItemPage(page: model$0.Page<$models.LocalTagQueryDTO> | null, secondaryLabel: string): $CancellablePromise<model$0.ApiResponse<model$0.Page<model$1.SelectItem> | null> | null> {
    return $Call.ByID(3654385186, page, secondaryLabel).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * QuerySelectItemPageByWorkId 根据作品ID分页查询选择项
 */
export function QuerySelectItemPageByWorkId(page: model$0.Page<$models.LocalTagQueryDTO> | null, workId: number): $CancellablePromise<model$0.ApiResponse<model$0.Page<model$1.SelectItem> | null> | null> {
    return $Call.ByID(3606327595, page, workId).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * Save 保存本地标签
 */
export function Save(tag: $models.LocalTagDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(2374210955, tag).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * Update 更新本地标签
 */
export function Update(tag: $models.LocalTagDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(336289815, tag).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateLastUse 更新最后使用时间
 */
export function UpdateLastUse(ids: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(620047310, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LocalTagResultDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType3);
const $$createType7 = model$0.ApiResponse.createFrom($$createType6);
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = model$1.SelectItem.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = model$0.ApiResponse.createFrom($$createType11);
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = model$0.Page.createFrom($$createType2);
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = model$0.ApiResponse.createFrom($$createType15);
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = model$0.Page.createFrom($$createType9);
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = model$0.ApiResponse.createFrom($$createType19);
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType23 = $Create.Nullable($$createType22);
