// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LocalTagQueryDTO 本地标签查询条件
 */
export class LocalTagQueryDTO {
    /**
     * 基础本地标签ID
     */
    "baseLocalTagId": number | null;

    /**
     * 本地标签名称（精确匹配）
     */
    "localTagName": string | null;

    /**
     * 模糊查询
     * 本地标签名称（模糊匹配）
     */
    "localTagNameLike": string | null;

    /**
     * 排序字段：create_time, update_time, local_tag_name, last_use
     * 排序字段
     */
    "orderBy": string;

    /**
     * 是否降序
     */
    "orderDesc": boolean;

    /** Creates a new LocalTagQueryDTO instance. */
    constructor($$source: Partial<LocalTagQueryDTO> = {}) {
        if (!("baseLocalTagId" in $$source)) {
            this["baseLocalTagId"] = null;
        }
        if (!("localTagName" in $$source)) {
            this["localTagName"] = null;
        }
        if (!("localTagNameLike" in $$source)) {
            this["localTagNameLike"] = null;
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = "";
        }
        if (!("orderDesc" in $$source)) {
            this["orderDesc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTagQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTagQueryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalTagQueryDTO($$parsedSource as Partial<LocalTagQueryDTO>);
    }
}
