// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LocalTagDTO 本地标签数据传输对象
 */
export class LocalTagDTO {
    "id": number;
    "localTagName": string | null;
    "baseLocalTagId": number | null;

    /** Creates a new LocalTagDTO instance. */
    constructor($$source: Partial<LocalTagDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("localTagName" in $$source)) {
            this["localTagName"] = null;
        }
        if (!("baseLocalTagId" in $$source)) {
            this["baseLocalTagId"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTagDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTagDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalTagDTO($$parsedSource as Partial<LocalTagDTO>);
    }
}

/**
 * LocalTagQueryDTO 本地标签查询条件
 */
export class LocalTagQueryDTO {
    /**
     * 基础本地标签ID
     */
    "baseLocalTagId": number | null;

    /**
     * 本地标签名称（精确匹配）
     */
    "localTagName": string | null;

    /**
     * 模糊查询
     * 本地标签名称（模糊匹配）
     */
    "localTagNameLike": string | null;

    /**
     * 排序字段：create_time, update_time, local_tag_name, last_use
     * 排序字段
     */
    "orderBy": string;

    /**
     * 是否降序
     */
    "orderDesc": boolean;

    /** Creates a new LocalTagQueryDTO instance. */
    constructor($$source: Partial<LocalTagQueryDTO> = {}) {
        if (!("baseLocalTagId" in $$source)) {
            this["baseLocalTagId"] = null;
        }
        if (!("localTagName" in $$source)) {
            this["localTagName"] = null;
        }
        if (!("localTagNameLike" in $$source)) {
            this["localTagNameLike"] = null;
        }
        if (!("orderBy" in $$source)) {
            this["orderBy"] = "";
        }
        if (!("orderDesc" in $$source)) {
            this["orderDesc"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTagQueryDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTagQueryDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalTagQueryDTO($$parsedSource as Partial<LocalTagQueryDTO>);
    }
}

/**
 * LocalTagResultDTO 本地标签返回结果DTO（用于屏蔽sql.Null*类型）
 */
export class LocalTagResultDTO {
    "id": number;
    "localTagName": string | null;
    "baseLocalTagId": number | null;
    "lastUse": number | null;
    "createTime": number;
    "updateTime": number;

    /** Creates a new LocalTagResultDTO instance. */
    constructor($$source: Partial<LocalTagResultDTO> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("localTagName" in $$source)) {
            this["localTagName"] = null;
        }
        if (!("baseLocalTagId" in $$source)) {
            this["baseLocalTagId"] = null;
        }
        if (!("lastUse" in $$source)) {
            this["lastUse"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = 0;
        }
        if (!("updateTime" in $$source)) {
            this["updateTime"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalTagResultDTO instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalTagResultDTO {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalTagResultDTO($$parsedSource as Partial<LocalTagResultDTO>);
    }
}
