// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class FileFilter {
    /**
     * Filter information EG: "Image Files (*.jpg, *.png)"
     */
    "DisplayName": string;

    /**
     * semicolon separated list of extensions, EG: "*.jpg;*.png"
     */
    "Pattern": string;

    /** Creates a new FileFilter instance. */
    constructor($$source: Partial<FileFilter> = {}) {
        if (!("DisplayName" in $$source)) {
            this["DisplayName"] = "";
        }
        if (!("Pattern" in $$source)) {
            this["Pattern"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): FileFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileFilter($$parsedSource as Partial<FileFilter>);
    }
}
