// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler 本地作者 Handler
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../pkg/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Delete 删除作者
 */
export function Delete(id: number): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(991129820, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetById 根据ID获取
 */
export function GetById(id: number): $CancellablePromise<model$0.ApiResponse<$models.LocalAuthorResultDTO | null> | null> {
    return $Call.ByID(3189236341, id).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListByWorkId 根据作品ID获取作者列表
 */
export function ListByWorkId(workId: number): $CancellablePromise<model$0.ApiResponse<(model$0.RankedLocalAuthor | null)[]> | null> {
    return $Call.ByID(3173747322, workId).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * ListSelectItems 查询选择项列表
 */
export function ListSelectItems(queryDTO: $models.LocalAuthorQueryDTO | null): $CancellablePromise<model$0.ApiResponse<(model$1.SelectItem | null)[]> | null> {
    return $Call.ByID(4229405961, queryDTO).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * QueryPage 分页查询
 */
export function QueryPage(page: number, pageSize: number, queryDTO: $models.LocalAuthorQueryDTO | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<$models.LocalAuthorResultDTO> | null> | null> {
    return $Call.ByID(1132350838, page, pageSize, queryDTO).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * QuerySelectItemPage 分页查询选择项
 */
export function QuerySelectItemPage(page: number, pageSize: number, queryDTO: $models.LocalAuthorQueryDTO | null): $CancellablePromise<model$0.ApiResponse<model$0.Page<model$1.SelectItem> | null> | null> {
    return $Call.ByID(1610622229, page, pageSize, queryDTO).then(($result: any) => {
        return $$createType23($result);
    });
}

/**
 * Save 保存作者
 */
export function Save(author: $models.LocalAuthorDTO | null): $CancellablePromise<model$0.ApiResponse<number> | null> {
    return $Call.ByID(363608746, author).then(($result: any) => {
        return $$createType25($result);
    });
}

/**
 * Update 更新作者
 */
export function Update(author: $models.LocalAuthorDTO | null): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1594288814, author).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * UpdateLastUse 更新最后使用时间
 */
export function UpdateLastUse(ids: number[]): $CancellablePromise<model$0.ApiResponse<any> | null> {
    return $Call.ByID(1429824341, ids).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LocalAuthorResultDTO.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.ApiResponse.createFrom($$createType3);
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.RankedLocalAuthor.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = model$0.ApiResponse.createFrom($$createType8);
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = model$1.SelectItem.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = model$0.ApiResponse.createFrom($$createType13);
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = model$0.Page.createFrom($$createType2);
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = model$0.ApiResponse.createFrom($$createType17);
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = model$0.Page.createFrom($$createType11);
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = model$0.ApiResponse.createFrom($$createType21);
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = model$0.ApiResponse.createFrom($Create.Any);
const $$createType25 = $Create.Nullable($$createType24);
